#+TITLE: 部分成就
#+AUTHOR: 李鹄
#+DATE: 2018-12-29

* 人物成长
** 在线
*** 陌上花开·壹
- 再次回到天涯明月刀的世界
#+BEGIN_EXAMPLE
累计登录2天
#+END_EXAMPLE

*** 陌上花开·贰
- 累计在天涯明月刀的世界里游历七天
#+BEGIN_EXAMPLE
累计登录7天
#+END_EXAMPLE

*** 陌上花开·叁
- 累计在天涯明月刀的世界里游历十四天
#+BEGIN_EXAMPLE
累计登录14天
#+END_EXAMPLE

*** 陌上开花·肆
- 累计在天涯明月刀的世界里游历三十天
#+BEGIN_EXAMPLE
累计登录30天
#+END_EXAMPLE

*** 陌上开花·伍
- 累计在天涯明月刀的世界里游历六十天
#+BEGIN_EXAMPLE
累计登录60天
#+END_EXAMPLE

*** 陌上开花·陆
- 累计在天涯明月刀的世界里游历九十天
#+BEGIN_EXAMPLE
累计登录90天
#+END_EXAMPLE

*** 陌上开花·柒
- 累计在天涯明月刀的世界里游历一百八十天
#+BEGIN_EXAMPLE
累计登录180天
#+END_EXAMPLE

*** 陌上开花·捌
- 累计在天涯明月刀的世界里游历二百七十天
#+BEGIN_EXAMPLE
累计登录270天
#+END_EXAMPLE

*** 陌上开花·玖
- 累计在天涯明月刀的世界里游历三百六十天
#+BEGIN_EXAMPLE
累计登录360天
#+END_EXAMPLE

*** 陌上开花·拾
- 累计在天涯明月刀的世界里游历七百二十天
#+BEGIN_EXAMPLE
累计登录720天
#+END_EXAMPLE

*** 蔷薇信使
- 向好友发送一封邮件
#+BEGIN_EXAMPLE
发送一封邮件
#+END_EXAMPLE

*** 累计签到·壹
- 历史累计签到30天
#+BEGIN_EXAMPLE
历史累计签到30天
#+END_EXAMPLE

*** 累计签到·贰
- 历史累计签到365天
#+BEGIN_EXAMPLE
历史累计签到365天
#+END_EXAMPLE

*** 累计签到·叁
- 历史累计签到1000天
#+BEGIN_EXAMPLE
历史累计签到1000天
#+END_EXAMPLE

*** 陌上开花·拾壹
- 累计在天涯明月刀的世界里游历一零八零天
#+BEGIN_EXAMPLE
累计登录1080天
#+END_EXAMPLE

** 见闻
*** 泱泱华夏
- 用工整美观的中文作为自己的游戏昵称
#+BEGIN_EXAMPLE
中文名
#+END_EXAMPLE

*** 夜探郡王府
- 应天波府之邀，趁夜色掩护潜入东平郡王府，终于粉碎赵允弼阴谋
#+BEGIN_EXAMPLE
完成话本“东平郡王府（夜间）”
#+END_EXAMPLE

*** 击退连环使
- 完成“遭遇连环使”系列见闻
#+BEGIN_EXAMPLE
路不平·素手助道人
雀捕蝉·伏击连环使
#+END_EXAMPLE

*** 解谜孔雀门
- 完成“孔雀门人”系列见闻
#+BEGIN_EXAMPLE
孔雀门·舍命报师恩
孔雀门·绝地遇佳人
孔雀门·高谊伴轻风（一）
孔雀门·高谊伴轻风（二）
孔雀门·高谊伴轻风（三）
孔雀门·翎羽生死劫
孔雀门·结草不忘恩
#+END_EXAMPLE

*** 惩治恶衙内
- 完成“恶衙内”系列见闻
#+BEGIN_EXAMPLE
游杭州·初遇小阎王
逛街巷·再行侠义道
行侠道·大闹衙内府
#+END_EXAMPLE

*** 智救痴情侣
- 完成“江洋大盗”系列见闻
#+BEGIN_EXAMPLE
是非直·重金捉大盗
倒黑白·情痴困旧城
喜结缘·天涯有情郎
#+END_EXAMPLE

*** 俏茶娘寻夫
- 完成“茶娘”系列见闻
#+BEGIN_EXAMPLE
凤孤飞·俏茶娘寻夫
机关尽·兄弟阋于墙
鸳梦碎·知会俏茶娘
#+END_EXAMPLE

*** 扑朔迷离
- 完成辨是非·雄兔脚扑朔和辨是非·雌兔眼迷离
#+BEGIN_EXAMPLE
辨是非·雄兔脚扑朔
辨是非·雌兔眼迷离
#+END_EXAMPLE

*** 八骏唏嘘叹
- 完成“八骏图”系列见闻
#+BEGIN_EXAMPLE
红草滩·以武鉴知己
疑云起·八骏成反目
探古镇·真相浮水面
叹唏嘘·江湖多变幻
#+END_EXAMPLE

*** 啼笑定姻缘
- 完成杭州离玉堂与韩莹莹系列见闻
#+BEGIN_EXAMPLE
大闹天波府
萍水逢·招亲惹风波
井底蛙·打擂凤凰集
永兴寺遇袭
#+END_EXAMPLE

*** 谁解美人傲
- 完成美人傲系列见闻
#+BEGIN_EXAMPLE
201个好友
#+END_EXAMPLE

*** 红叶伴青枫
- 完成“青枫焰·临竹醉清风”和“青枫焰·幽花落横笛”
#+BEGIN_EXAMPLE
青枫焰·临竹醉清风
青枫焰·幽花落横笛
#+END_EXAMPLE

*** 杭州逢雅奴
- 完成“雅奴”系列见闻
#+BEGIN_EXAMPLE
薄情儿·西湖殇夜月
会故人·暮雨恨朝云
心难测·执手走天涯
#+END_EXAMPLE

*** 见闻杭州
- 在杭州完成6个单次见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
杭州
#+END_EXAMPLE

*** 见闻江南
- 在江南完成6个故事性见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
江南
#+END_EXAMPLE

*** 见闻东越
- 在东越完成17个故事性见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
东越
#+END_EXAMPLE

*** 见闻徐海
- 在徐海完成7个故事性见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
徐海
#+END_EXAMPLE

*** 问水庄
- 完成问水庄系列见闻
#+BEGIN_EXAMPLE
问水庄
#+END_EXAMPLE

*** 佛语禅心
- 完成九华佛语禅心任务的隐藏分支
#+BEGIN_EXAMPLE
佛语禅心
#+END_EXAMPLE

*** 余音绕梁
- 完成九华君子六艺任务的隐藏分支
#+BEGIN_EXAMPLE
余音绕梁
#+END_EXAMPLE

*** 万点繁星
- 完成唐门门派见闻
#+BEGIN_EXAMPLE
闻旧事·闲潭竹影幽
孝女心·思亲天一房
#+END_EXAMPLE

*** 剑履山河
- 完成太白门派见闻
#+BEGIN_EXAMPLE
祭故人·沉剑池往事
镇蛊毒·终身伴白雪
#+END_EXAMPLE

*** 天地不仁
- 完成真武门派见闻
#+BEGIN_EXAMPLE
道者心·有情亦无情
识蔷薇·人外有高人
#+END_EXAMPLE

*** 星河倒卷
- 完成神威门派见闻
#+BEGIN_EXAMPLE
很难偿·故园失手足
斩奸邪·风沙起大漠
#+END_EXAMPLE

*** 龙震百里
- 完成丐帮门派见闻
#+BEGIN_EXAMPLE
思无邪·无猜亦无忧
风华茂·少年展头角
#+END_EXAMPLE

*** 重华乱舞
- 完成天香门派见闻
#+BEGIN_EXAMPLE
步花间·稚童踪难觅
梦行云·莫问花解语
#+END_EXAMPLE

*** 万里残阳
- 完成杭州系列见闻（低级）
#+BEGIN_EXAMPLE
优昙花·夺花尽心计
缔情缘·永兴寺遇袭
黑与白·子夜露锋芒
#+END_EXAMPLE

*** 谁应帝王
- 完成江南系列见闻
#+BEGIN_EXAMPLE
美人傲·月夜望星河
茶瓶儿·难解女儿心
青枫焰·临竹醉清风
风骤起·携手破连环
何为侠·尽在不言中
照孤星·挥剑破孤星
#+END_EXAMPLE

*** 浪迹天涯
- 完成东越系列见闻
#+BEGIN_EXAMPLE
雀捕蝉·伏击连环使
凤孤飞·知会俏茶娘
是非直·天涯有情郎
#+END_EXAMPLE

*** 独立寒江
- 完成杭州系列见闻（高级）
#+BEGIN_EXAMPLE
心难测·执手走天涯
空余恨·惨雨红衣林
姊妹缘·曲远暗香随
#+END_EXAMPLE

*** 龙吟水上
- 完成九华系列见闻
#+BEGIN_EXAMPLE
酬知己·高谊伴轻风
孔雀门·翎羽生死劫
芳心苦·绝地遇佳人
辨是非·雌兔眼迷离
#+END_EXAMPLE

*** 义薄云天
- 完成徐海系列见闻
#+BEGIN_EXAMPLE
神刀谱·江湖多变幻
江湖醉·一世为兄弟
情两难系列见闻
#+END_EXAMPLE

*** 心如明镜
- 完成开封系列见闻
#+BEGIN_EXAMPLE
双全法·一念在人间
盗有道·赤子起顽心
#+END_EXAMPLE

*** 情天恨海
- 完成秦川系列见闻
#+BEGIN_EXAMPLE
天魔影·一剑荡群魔
白毛怪·此情成追忆
#+END_EXAMPLE

*** 五仙灭地
- 完成五毒门派见闻
#+BEGIN_EXAMPLE
祭亡妻·年年一相聚
讲旧事·代代有传奇
#+END_EXAMPLE

*** 情两难
- 完成情两难系列见闻
#+BEGIN_EXAMPLE
情两难·恩怨总难平
情两难·恩仇多变换
#+END_EXAMPLE

*** 神鬼夜哭
- 完成神刀门派见闻
#+BEGIN_EXAMPLE
万仞峰·饮流怀其源
驯鹰师·神鹰云梦泽
#+END_EXAMPLE

*** 沧溟九歌
- 完成移花门派见闻
#+BEGIN_EXAMPLE
云中词·谁寄锦书来
护花人·轻舟似群星
#+END_EXAMPLE

*** 巨浪白鱼
- 在国风运动节中钓到50条白色大鱼
#+BEGIN_EXAMPLE
白色大鱼50条
#+END_EXAMPLE

*** 巨浪青鲲
- 在国风运动节中钓到50条青色大鱼
#+BEGIN_EXAMPLE
青色大鱼50条
#+END_EXAMPLE

*** 巨浪赤虹
- 在国风运动节中钓到50条赤色大鱼
#+BEGIN_EXAMPLE
赤虹50条
#+END_EXAMPLE

*** 心细如毫
- 在国风运动节中钓到10只籽虾
#+BEGIN_EXAMPLE
籽虾10只
#+END_EXAMPLE

*** 慧眼如炬
- 在国风运动节中钓到10只金色绒毛小蟹
#+BEGIN_EXAMPLE
金色绒毛小蟹10只
#+END_EXAMPLE

*** 时速不限
- 国风运动节中完成5次赛马
#+BEGIN_EXAMPLE
国风运动节中参与5次赛马
#+END_EXAMPLE

*** 百晓全书
- 国风运动节期间完成10次明辨真假
#+BEGIN_EXAMPLE
国风运动节期间完成10次明辨真假
#+END_EXAMPLE

*** 全面发展
- 达成国风运动节期间所有成就
#+BEGIN_EXAMPLE
巨浪白鱼
巨浪青鲲
巨浪赤虹
心细如毫
慧眼如炬
时速不限
百晓全书
#+END_EXAMPLE

*** 吃鱼让我快乐
- 节日期间，鱼类菜式各吃过10份以上
#+BEGIN_EXAMPLE
红烧划水10份
剁椒鱼头10份
萝卜鱼头汤10份
豆瓣全鱼10份
糖醋鱼10份
#+END_EXAMPLE

*** 暖心饺子
- 节日期间，四种饺子各送出一份
#+BEGIN_EXAMPLE
飞剑童的猪肉饺子
飞剑童的牛肉饺子
飞剑童的羊肉饺子
飞剑童的鸡蛋饺子
#+END_EXAMPLE

*** 万物有灵
- 节日期间，飞剑童的饺子喂给小猫或小狗三次
#+BEGIN_EXAMPLE
飞剑童的羊肉饺子
飞剑童的鸡蛋饺子
#+END_EXAMPLE

*** 满头是雪
- 完成五次打雪仗日常任务
#+BEGIN_EXAMPLE
打雪仗5次
#+END_EXAMPLE

*** 玩疯了！
- 在单场打雪仗中获得80分
#+BEGIN_EXAMPLE
打雪仗80分
#+END_EXAMPLE

*** 隐藏菜谱
- 获得隐藏菜谱
#+BEGIN_EXAMPLE
隐藏菜谱
#+END_EXAMPLE

*** 铃儿响叮当
- 为西域老人找回三次铃铛
#+BEGIN_EXAMPLE
圣诞老人的铃铛
#+END_EXAMPLE

*** 是你？
- 完成2018元旦特殊剧情“天上白玉京，人间生死劫”
#+BEGIN_EXAMPLE
天上白玉京人间生死劫
#+END_EXAMPLE

*** 忙碌一冬
- 达成以上所有
#+BEGIN_EXAMPLE
吃鱼让我快乐
暖心饺子
万物有灵
满头是雪
玩疯了！
隐藏菜谱
铃儿响叮当
是你？
#+END_EXAMPLE

*** 堆个大雪人·天峰盟
- 所在服务器的天峰盟的雪人堆成了
#+BEGIN_EXAMPLE
天峰盟雪人
#+END_EXAMPLE

*** 堆个大雪人·青龙会
- 所在服务器的青龙会的雪人堆成了
#+BEGIN_EXAMPLE
青龙会雪人
#+END_EXAMPLE

*** 雪里咕噜
- 上交了五次堆雪人的材料
#+BEGIN_EXAMPLE
帮助天峰盟堆雪人
帮助青龙会堆雪人
#+END_EXAMPLE

*** 越滚越大
- 完成“雪里咕噜”和“堆个大雪人”
#+BEGIN_EXAMPLE
雪里咕噜
雪人堆成
#+END_EXAMPLE

*** 雪人堆成了
- 青龙会或天峰盟的雪人堆成了
#+BEGIN_EXAMPLE
天峰盟雪人
青龙会雪人
#+END_EXAMPLE

** 等级
*** 侠·初入江湖
- 触动初入江湖（30级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 智·江湖百业
- 触动江湖百业（40级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 凛·剑试蔷薇
- 触动剑试蔷薇（50级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 霸·天下盟会
- 触动天下盟会（60级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 策·九华叠翠
- 触动九华叠翠（70级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 舞·天香传世
- 触动天香传世（80级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 暗·东京华梦
- 触动东京华梦（90级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 笑·沧海月明
- 触动沧海月明（100级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 梦·东海极境
- 触动东海极境（终极封印）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

*** 陌上花开
- 不删档侠士专享
#+BEGIN_EXAMPLE
不删档侠士专享
#+END_EXAMPLE

*** 会饮天下
- 会员礼包尊享
#+BEGIN_EXAMPLE
会员礼包尊享
#+END_EXAMPLE

*** 兰陵霸唱
- 豪华蓝钻礼包尊享
#+BEGIN_EXAMPLE
豪华蓝钻礼包尊享
#+END_EXAMPLE

*** 心悦君兮
- 心悦会员尊享
#+BEGIN_EXAMPLE
心悦会员尊享
#+END_EXAMPLE

*** 盛世君临
- 心悦会员尊享2
#+BEGIN_EXAMPLE
心悦会员尊享2
#+END_EXAMPLE

*** 金璧梦回
- 黄钻礼包尊享
#+BEGIN_EXAMPLE
黄钻礼包尊享
#+END_EXAMPLE

*** 翠影菁华
- 绿钻礼包尊享
#+BEGIN_EXAMPLE
绿钻礼包尊享
#+END_EXAMPLE

*** 极地曙光
- TGP礼包尊享
#+BEGIN_EXAMPLE
TGP礼包尊享
#+END_EXAMPLE

*** 初试身手
- 等级达到10级
#+BEGIN_EXAMPLE
达到10级
#+END_EXAMPLE

*** 初入江湖
- 等级达到20级
#+BEGIN_EXAMPLE
达到20级
#+END_EXAMPLE

*** 小有名气
- 等级达到30级
#+BEGIN_EXAMPLE
达到30级
#+END_EXAMPLE

*** 行走江湖
- 等级达到40级
#+BEGIN_EXAMPLE
达到40级
#+END_EXAMPLE

*** 堪负重任
- 等级达到50级
#+BEGIN_EXAMPLE
达到50级
#+END_EXAMPLE

*** 侠行四方
- 等级达到60级
#+BEGIN_EXAMPLE
达到60级
#+END_EXAMPLE

*** 八荒豪杰
- 等级达到70级
#+BEGIN_EXAMPLE
达到70级
#+END_EXAMPLE

*** 独步武林
- 等级达到80级
#+BEGIN_EXAMPLE
达到80级
#+END_EXAMPLE

*** 名动天下
- 等级达到90级
#+BEGIN_EXAMPLE
达到90级
#+END_EXAMPLE

*** 威震江湖
- 等级达到100级
#+BEGIN_EXAMPLE
达到100级
#+END_EXAMPLE

*** 融会贯通
- 学习完毕所有的本门派技能
#+BEGIN_EXAMPLE
门派技能
#+END_EXAMPLE

** 金钱
*** 初识孔方
- 获取金钱达到100金
#+BEGIN_EXAMPLE
100金
#+END_EXAMPLE

*** 积少成多
- 获取金钱达到1000金
#+BEGIN_EXAMPLE
1000金
#+END_EXAMPLE

*** 富甲一方
- 获取金钱达到10000金
#+BEGIN_EXAMPLE
10000金
#+END_EXAMPLE

*** 堆金积玉
- 获取金钱达到100000金
#+BEGIN_EXAMPLE
100000金
#+END_EXAMPLE

*** 腰缠万贯
- 获取金钱达到500000金
#+BEGIN_EXAMPLE
获取金钱达到500000金
#+END_EXAMPLE

*** 富可敌国
- 获取金钱达到1500000金
#+BEGIN_EXAMPLE
获取金钱达到1500000金
#+END_EXAMPLE

*** 纸醉金迷
- 获取金钱达到5000000金
#+BEGIN_EXAMPLE
获取金钱达到5000000金
#+END_EXAMPLE

*** 一掷千金
- 花费超过1000金
#+BEGIN_EXAMPLE
花费1000金
#+END_EXAMPLE

*** 散尽复来
- 花费超过10000金
#+BEGIN_EXAMPLE
花费10000金
#+END_EXAMPLE

*** 挥金如土
- 花费超过100000金
#+BEGIN_EXAMPLE
花费100000金
#+END_EXAMPLE

*** 拨万轮千
- 花费超过500000金
#+BEGIN_EXAMPLE
花费超过500000金
#+END_EXAMPLE

*** 钟鸣鼎食
- 花费超过1500000金
#+BEGIN_EXAMPLE
花费超过1500000金
#+END_EXAMPLE

*** 身外之物
- 花费超过5000000金
#+BEGIN_EXAMPLE
花费超过5000000金
#+END_EXAMPLE

*** 富有四海
- 获取金钱达到10000000金
#+BEGIN_EXAMPLE
获取金钱达到10000000金
#+END_EXAMPLE

*** 身外之物·二
- 花费超过8000000金
#+BEGIN_EXAMPLE
花费超过8000000金
#+END_EXAMPLE

*** 身外之物·三
- 花费超过10000000金
#+BEGIN_EXAMPLE
花费超过10000000金
#+END_EXAMPLE

** 话本
*** 重创神武门
- 神刀堂与神武门的恩怨终需做个了断，经此一战，马芳玲与杜云松虽逃走，但孤魂断常、郝厨子与苗天王伏诛，神武门已元气大伤。\n
#+BEGIN_EXAMPLE
完成话本“普通·强袭神武门”
#+END_EXAMPLE

*** 疾速神武门
- 在半小时的时间内完成话本：普通·强袭神武门
#+BEGIN_EXAMPLE
神武门
#+END_EXAMPLE

*** 疾速夜探郡王府
- 在一刻钟的时间内完成话本：夜探郡王府
#+BEGIN_EXAMPLE
夜探郡王府
#+END_EXAMPLE

*** 强攻郡王府
- 应天波府之邀，强行攻入东平郡王府，击败赵允弼
#+BEGIN_EXAMPLE
完成话本“东平郡王府（白天）”
#+END_EXAMPLE

*** 疾速强攻郡王府
- 在半小时的时间内完成话本：鏖战郡王府
#+BEGIN_EXAMPLE
强攻郡王府
#+END_EXAMPLE

*** 扬威龙首山
- 盘踞在龙首山天泉山庄的十二连环坞老大“鹰眼老七”盗走孔雀翎，杀上龙首山后虽未能夺回，却也震慑了幕后黑手。
#+BEGIN_EXAMPLE
完成话本“龙首山”
#+END_EXAMPLE

*** 疾速龙首山
- 在半小时的时间内完成话本：普通·荡平龙首山
#+BEGIN_EXAMPLE
龙首山
#+END_EXAMPLE

*** 突袭血衣楼
- 血衣楼现今防守空虚。离盟主传书，你可先行集结人马，捣毁其留守部队，为来日总攻奠定胜机
#+BEGIN_EXAMPLE
血衣楼
#+END_EXAMPLE

*** 浴血龙首山
- 前次龙首山扬威，如今鹰眼老七已重整人马再战，浴血龙首山！
#+BEGIN_EXAMPLE
浴血龙首山
#+END_EXAMPLE

*** 雨夜镇天牢
- 蛇王神算子和黑蜈蚣带人趁着雨夜前来劫狱，务必要阻止黑街的这次行动！
#+BEGIN_EXAMPLE
雨夜镇天牢
#+END_EXAMPLE

*** 实至名归
- 以超过95分的分数ROLL到物品
#+BEGIN_EXAMPLE
掷出95点
#+END_EXAMPLE

*** 命中无时莫强求
- 虽然掷出了超过95分，还是未获得物品
#+BEGIN_EXAMPLE
掷出95点
#+END_EXAMPLE

*** 命里有时终须有
- 虽然掷出了不到10分，还是赢得了物品
#+BEGIN_EXAMPLE
掷出10点
#+END_EXAMPLE

*** 手慢无
- 虽然掷出了100分，因为时间顺序原因还是未获得物品
#+BEGIN_EXAMPLE
掷出100点
#+END_EXAMPLE

*** 手快有
- 虽然掷出了1分，因为时间顺序原因还是获得了物品
#+BEGIN_EXAMPLE
掷出1点
#+END_EXAMPLE

*** 血战苍梧城
- 万里杀传出消息，青龙会潜堂所在已经查清，就是位于燕云西南的古城苍梧。萧四无更获得了大悲赋的三式，在其中修炼。苍梧城易守难攻，青龙会卧虎藏龙，此战极其凶险。
#+BEGIN_EXAMPLE
血战苍梧城
#+END_EXAMPLE

*** 挑战·血战苍梧城
- 万里杀传出消息，青龙会潜堂所在已经查清，就是位于燕云西南的古城苍梧。萧四无更获得了大悲赋的三式，在其中修炼。苍梧城易守难攻，青龙会卧虎藏龙，此战极其凶险。
#+BEGIN_EXAMPLE
浴血苍梧城
#+END_EXAMPLE

*** 普通·天峰会八荒
- 八荒本独立世外，如今决意与四盟携手，正面对抗青龙会。八荒师兄师姐们严阵以待，只有通过了他们考验的精锐之师，才有资格前往万雪窟极凶之地一探。
#+BEGIN_EXAMPLE
普通·天峰会八荒
#+END_EXAMPLE

*** 挑战·天峰会八荒
- 八荒本独立世外，如今决意与四盟携手，正面对抗青龙会。八荒师兄师姐们严阵以待，只有通过了他们考验的精锐之师，才有资格前往万雪窟极凶之地一探。
#+BEGIN_EXAMPLE
挑战·天峰会八荒
#+END_EXAMPLE

*** 普通·喋血万雪窟
- 八荒查明，百晓生掳掠八荒弟子炼制药人之所在秘密巢穴，正是万雪窟。万雪窟中无数百晓生座下精英，更有诡奇之物，凶险异常。八荒唯选精锐，结队前往刺探征伐。
#+BEGIN_EXAMPLE
普通·喋血万雪窟
#+END_EXAMPLE

*** 挑战·喋血万雪窟
- 八荒查明，百晓生掳掠八荒弟子炼制药人之所在秘密巢穴，正是万雪窟。万雪窟中无数百晓生座下精英，更有诡奇之物，凶险异常。八荒唯选精锐，结队前往刺探征伐。
#+BEGIN_EXAMPLE
挑战·喋血万雪窟
#+END_EXAMPLE

*** 十二楼五城·修罗
- 十二楼五城是一系列青龙会历经千百年的秘密藏宝之地，只有百晓生知晓其真正秘密。修罗城位于燕云深处，由修罗王镇守炼狱房，极其凶险，其内藏有陨石之焰，可铸神兵。
#+BEGIN_EXAMPLE
十二楼五城·修罗
#+END_EXAMPLE

*** 挑战·琴魔
- 百晓生已走，琴音却未绝。随独孤师兄和公孙师兄去会会这个琴魔！
#+BEGIN_EXAMPLE
挑战·琴魔
#+END_EXAMPLE

*** 普通·开封会八荒
- 叶开约战开封擂台
#+BEGIN_EXAMPLE
普通·开封会八荒
#+END_EXAMPLE

*** 挑战·开封会八荒
- 叶开约战开封擂台
#+BEGIN_EXAMPLE
挑战·开封会八荒
#+END_EXAMPLE

*** 普通·决战嘲天宫
- 青龙会密室
#+BEGIN_EXAMPLE
普通·决战嘲天宫
#+END_EXAMPLE

*** 挑战·决战嘲天宫
- 青龙会密室
#+BEGIN_EXAMPLE
挑战·决战嘲天宫
#+END_EXAMPLE

*** 普通·东海会四盟
- 接受子桑不墨邀请，得四盟主相助，以移花醉心之试的方法，于东海解毒。
#+BEGIN_EXAMPLE
普通·东海会四盟
#+END_EXAMPLE

*** 挑战·东海会四盟
- 接受子桑不墨邀请，得四盟主相助，以移花醉心之试的方法，于东海解毒。
#+BEGIN_EXAMPLE
挑战·东海会四盟
#+END_EXAMPLE

*** 普通·雨夜破天牢
- 受沈孤鸿所托，前往开封大相国寺底下的皇城天牢，救出一众黑街英雄。
#+BEGIN_EXAMPLE
普通·雨夜破天牢
#+END_EXAMPLE

*** 挑战·雨夜破天牢
- 受沈孤鸿所托，前往开封大相国寺底下的皇城天牢，救出一众黑街英雄。
#+BEGIN_EXAMPLE
挑战·雨夜破天牢
#+END_EXAMPLE

** 剧情
*** 天涯蔷薇
- 完成九华剧情章节
#+BEGIN_EXAMPLE
完成九华全部任务
#+END_EXAMPLE

*** 燕云扬沙
- 完成神威门派剧情章节
#+BEGIN_EXAMPLE
完成全部神威任务
#+END_EXAMPLE

*** 秦川逐雪
- 完成太白门派剧情章节
#+BEGIN_EXAMPLE
秦川任务
#+END_EXAMPLE

*** 花海浮灯
- 完成天香门派剧情章节
#+BEGIN_EXAMPLE
天香剧情
#+END_EXAMPLE

*** 竹海微澜
- 完成唐门门派剧情章节
#+BEGIN_EXAMPLE
唐门剧情
#+END_EXAMPLE

*** 荆湖浪迹
- 完成丐帮门派剧情章节
#+BEGIN_EXAMPLE
丐帮剧情
#+END_EXAMPLE

*** 沧山观云
- 完成真武门派剧情章节
#+BEGIN_EXAMPLE
真武剧情
#+END_EXAMPLE

*** 初识刀意
- 完成杭州剧情章节
#+BEGIN_EXAMPLE
完成全部杭州任务
#+END_EXAMPLE

*** 飞燕击水
- 完成江南剧情章节
#+BEGIN_EXAMPLE
完成全部江南任务
#+END_EXAMPLE

*** 曾慕多情
- 完成东越剧情章节
#+BEGIN_EXAMPLE
完成全部东越任务
#+END_EXAMPLE

*** 再见孔雀
- 完成杭州高等级剧情章节
#+BEGIN_EXAMPLE
杭州高等级
#+END_EXAMPLE

*** 剑挑血衣
- 完成九华高等级剧情章节
#+BEGIN_EXAMPLE
九华高等级任务
#+END_EXAMPLE

*** 神刀出鞘
- 完成徐海剧情章节
#+BEGIN_EXAMPLE
完成徐海任务章节
#+END_EXAMPLE

*** 明月含悲
- 完成开封剧情章节
#+BEGIN_EXAMPLE
开封剧情
#+END_EXAMPLE

*** 玉锁冰心
- 完成秦川剧情章节
#+BEGIN_EXAMPLE
秦川剧情
#+END_EXAMPLE

*** 计夺连环
- 完成燕云剧情章节
#+BEGIN_EXAMPLE
燕云剧情
#+END_EXAMPLE

*** 人在天涯
- 完成以下的剧情章节
#+BEGIN_EXAMPLE
天涯蔷薇
初识刀意
飞燕击水
曾慕多情
再见孔雀
剑挑血衣
神刀出鞘
明月含悲
玉锁冰心
横沙血战
#+END_EXAMPLE

*** 日月天华
- 完成五毒门派章节
#+BEGIN_EXAMPLE
五毒门派·日月天华
#+END_EXAMPLE

*** 刀锋再临
- 完成神刀门派章节
#+BEGIN_EXAMPLE
神刀门派·神刀再临
#+END_EXAMPLE

*** 蜀地风流
- 完成巴蜀剧情章节
#+BEGIN_EXAMPLE
巴蜀剧情·蜀地风流
#+END_EXAMPLE

*** 初出茅庐
- 完成九华初出茅庐章节
#+BEGIN_EXAMPLE
神刀门派·神刀再临
#+END_EXAMPLE

*** 天命风流·青龙令
- 完成天命风流剧情章节，并选择了潜入卧底的剧情支线。
#+BEGIN_EXAMPLE
潜龙渊·天命风流
#+END_EXAMPLE

*** 天命风流·盟主令
- 完成天命风流剧情章节，并选择了接应卧底的剧情支线。
#+BEGIN_EXAMPLE
望龙潭·天命风流
#+END_EXAMPLE

*** 归来踏浪
- 完成移花门派章节
#+BEGIN_EXAMPLE
移花门派·归来踏浪
#+END_EXAMPLE

** 经脉
*** 经脉筑基
- 经脉贯通达到等级“经脉筑基”
#+BEGIN_EXAMPLE
经脉筑基
#+END_EXAMPLE

*** 初窥门径
- 经脉贯通达到等级“初窥门径”
#+BEGIN_EXAMPLE
初窥门径
#+END_EXAMPLE

*** 心有所得
- 经脉贯通达到等级“心有所得”
#+BEGIN_EXAMPLE
心有所得
#+END_EXAMPLE

*** 渐入佳境
- 经脉贯通达到等级“渐入佳境”
#+BEGIN_EXAMPLE
渐入佳境
#+END_EXAMPLE

*** 挥洒自如
- 经脉贯通达到等级“挥洒自如”
#+BEGIN_EXAMPLE
挥洒自如
#+END_EXAMPLE

*** 游刃有余
- 经脉贯通达到等级“游刃有余”
#+BEGIN_EXAMPLE
游刃有余
#+END_EXAMPLE

*** 行云流水
- 经脉贯通达到等级“行云流水”
#+BEGIN_EXAMPLE
行云流水
#+END_EXAMPLE

*** 炉火纯青
- 经脉贯通达到等级“炉火纯青”
#+BEGIN_EXAMPLE
炉火纯青
#+END_EXAMPLE

*** 登峰造极
- 经脉贯通达到等级“登峰造极”
#+BEGIN_EXAMPLE
登峰造极
#+END_EXAMPLE

*** 出神入化
- 经脉贯通达到等级“出神入化”
#+BEGIN_EXAMPLE
出神入化
#+END_EXAMPLE

** 功力
*** 初识武道·壹
- 31级后功力达到2000
#+BEGIN_EXAMPLE
功力达到2000
等级到达31级
#+END_EXAMPLE

*** 初识武道·贰
- 31级后功力达到2500
#+BEGIN_EXAMPLE
功力达到2500
等级到达31级
#+END_EXAMPLE

*** 潜心修武·壹
- 41级后功力达到3000
#+BEGIN_EXAMPLE
功力达到3000
等级到达41级
#+END_EXAMPLE

*** 潜心修武·贰
- 41级后功力达到3500
#+BEGIN_EXAMPLE
功力达到3500
等级到达41级
#+END_EXAMPLE

*** 武道初成·壹
- 51级后功力达到4000
#+BEGIN_EXAMPLE
功力达到4000
等级到达51级
#+END_EXAMPLE

*** 武道初成·贰
- 51级后功力达到4500
#+BEGIN_EXAMPLE
功力达到4500
等级到达51级
#+END_EXAMPLE

*** 武道初成·叁
- 51级后功力达到5000
#+BEGIN_EXAMPLE
功力达到5000
等级到达51级
#+END_EXAMPLE

*** 由武窥心·壹
- 61级后功力达到5500
#+BEGIN_EXAMPLE
功力达到5500
等级到达61级
#+END_EXAMPLE

*** 由武窥心·贰
- 61级后功力达到6000
#+BEGIN_EXAMPLE
功力达到6000
等级到达61级
#+END_EXAMPLE

*** 由武窥心·叁
- 61级后功力达到6500
#+BEGIN_EXAMPLE
功力达到6500
等级到达61级
#+END_EXAMPLE

*** 由心窥命·壹
- 71级后功力达到7000
#+BEGIN_EXAMPLE
功力达到7000
等级到达71级
#+END_EXAMPLE

*** 由心窥命·贰
- 71级后功力达到7500
#+BEGIN_EXAMPLE
功力达到7500
等级到达71级
#+END_EXAMPLE

*** 由心窥命·叁
- 71级后功力达到8000
#+BEGIN_EXAMPLE
功力达到8000
等级到达71级
#+END_EXAMPLE

*** 由命窥天·壹
- 81级后功力达到8500
#+BEGIN_EXAMPLE
功力达到8500
等级到达81级
#+END_EXAMPLE

*** 由命窥天·贰
- 81级后功力达到9000
#+BEGIN_EXAMPLE
功力达到9000
等级到达81级
#+END_EXAMPLE

*** 由命窥天·叁
- 81级后功力达到9500
#+BEGIN_EXAMPLE
功力达到9500
等级到达81级
#+END_EXAMPLE

*** 由命窥天·肆
- 81级后功力达到10000
#+BEGIN_EXAMPLE
功力达到10000
等级到达81级
#+END_EXAMPLE

*** 武道登峰·壹
- 85级后功力达到11000
#+BEGIN_EXAMPLE
功力达到11000
等级到达85级
#+END_EXAMPLE

*** 武道登峰·贰
- 85级后功力达到12000
#+BEGIN_EXAMPLE
功力达到12000
等级到达85级
#+END_EXAMPLE

*** 武道登峰·叁
- 90级后功力达到12500
#+BEGIN_EXAMPLE
功力达到12500
等级到达90级
#+END_EXAMPLE

*** 武道登峰·肆
- 90级后功力达到13000
#+BEGIN_EXAMPLE
功力达到13000
等级到达90级
#+END_EXAMPLE

*** 武道登峰·伍
- 90级后功力达到13500
#+BEGIN_EXAMPLE
功力达到13500
等级到达90级
#+END_EXAMPLE

*** 武道登峰·陆
- 90级后功力达到14000
#+BEGIN_EXAMPLE
功力达到14000
等级到达90级
#+END_EXAMPLE

*** 武道登峰·柒
- 90级后功力达到14500
#+BEGIN_EXAMPLE
功力达到14500
等级到达90级
#+END_EXAMPLE

*** 武道登峰·捌
- 90级后功力达到15000
#+BEGIN_EXAMPLE
功力达到15000
等级到达90级
#+END_EXAMPLE

*** 武道登峰·玖
- 90级后功力达到15500
#+BEGIN_EXAMPLE
功力达到15500
等级到达90级
#+END_EXAMPLE

*** 武道登峰·拾
- 90级后功力达到16000
#+BEGIN_EXAMPLE
功力达到16000
等级到达90级
#+END_EXAMPLE

*** 武心造极·壹
- 90级后功力达到16500
#+BEGIN_EXAMPLE
功力达到16500
等级到达90级
#+END_EXAMPLE

*** 武心造极·贰
- 90级后功力达到17000
#+BEGIN_EXAMPLE
功力达到17000
等级到达90级
#+END_EXAMPLE

*** 武心造极·叁
- 90级后功力达到17500
#+BEGIN_EXAMPLE
功力达到17500
等级到达90级
#+END_EXAMPLE

*** 武心造极·肆
- 90级后功力达到18000
#+BEGIN_EXAMPLE
功力达到18000
等级到达90级
#+END_EXAMPLE

*** 武心造极·伍
- 90级后功力达到18250
#+BEGIN_EXAMPLE
功力达到18250
等级到达90级
#+END_EXAMPLE

*** 武心造极·陆
- 90级后功力达到18500
#+BEGIN_EXAMPLE
功力达到18500
等级到达90级
#+END_EXAMPLE

*** 武心造极·柒
- 90级后功力达到18750
#+BEGIN_EXAMPLE
功力达到18750
等级到达90级
#+END_EXAMPLE

*** 武心造极·捌
- 90级后功力达到19000
#+BEGIN_EXAMPLE
功力达到19000
等级到达90级
#+END_EXAMPLE

*** 武心造极·玖
- 90级后功力达到19250
#+BEGIN_EXAMPLE
功力达到19250
等级到达90级
#+END_EXAMPLE

*** 武心造极·拾
- 90级后功力达到19500
#+BEGIN_EXAMPLE
功力达到19500
等级到达90级
#+END_EXAMPLE

*** 武心造极·拾壹
- 90级后功力达到19750
#+BEGIN_EXAMPLE
功力达到19750
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·壹
- 90级后功力达到20000
#+BEGIN_EXAMPLE
功力达到20000
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·贰
- 90级后功力达到20250
#+BEGIN_EXAMPLE
功力达到20250
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·叁
- 90级后功力达到20500
#+BEGIN_EXAMPLE
功力达到20500
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·肆
- 90级后功力达到20750
#+BEGIN_EXAMPLE
功力达到20750
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·伍
- 90级后功力达到21000
#+BEGIN_EXAMPLE
功力达到21000
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·陆
- 90级后功力达到21250
#+BEGIN_EXAMPLE
功力达到21250
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·柒
- 90级后功力达到21500
#+BEGIN_EXAMPLE
功力达到21500
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·捌
- 90级后功力达到21750
#+BEGIN_EXAMPLE
功力达到21750
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·玖
- 90级后功力达到22000
#+BEGIN_EXAMPLE
功力达到22000
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·拾
- 90级后功力达到22100
#+BEGIN_EXAMPLE
功力达到22100
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·拾壹
- 90级后功力达到22200
#+BEGIN_EXAMPLE
功力达到22200
等级到达90级
#+END_EXAMPLE

*** 盖世武魂·拾贰
- 90级后功力达到22300
#+BEGIN_EXAMPLE
功力达到22300
等级到达90级
#+END_EXAMPLE

*** 无双武境
- 95级后功力达到22400
#+BEGIN_EXAMPLE
22400
等级到达95级
#+END_EXAMPLE

*** 无双武境·贰
- 95级后功力达到22500
#+BEGIN_EXAMPLE
22500
等级到达95级
#+END_EXAMPLE

*** 无双武境·叁
- 95级后功力达到22750
#+BEGIN_EXAMPLE
22750
等级到达95级
#+END_EXAMPLE

*** 无双武境·肆
- 95级后功力达到23000
#+BEGIN_EXAMPLE
23000
等级到达95级
#+END_EXAMPLE

*** 无双武境·伍
- 95级后功力达到23250
#+BEGIN_EXAMPLE
23250
等级到达95级
#+END_EXAMPLE

*** 无双武境·陆
- 95级后功力达到23500
#+BEGIN_EXAMPLE
23500
等级到达95级
#+END_EXAMPLE

*** 无双武境·柒
- 95级后功力达到23750
#+BEGIN_EXAMPLE
23750
等级到达95级
#+END_EXAMPLE

*** 无双武境·捌
- 95级后功力达到24000
#+BEGIN_EXAMPLE
24000
等级到达95级
#+END_EXAMPLE

*** 无双武境·玖
- 95级后功力达到24250
#+BEGIN_EXAMPLE
24250
等级到达95级
#+END_EXAMPLE

*** 无双武境·拾
- 95级后功力达到24500
#+BEGIN_EXAMPLE
24500
等级到达95级
#+END_EXAMPLE

*** 无双武境·拾壹
- 95级后功力达到24750
#+BEGIN_EXAMPLE
24750
等级到达95级
#+END_EXAMPLE

*** 无双武境·拾贰
- 95级后功力达到25000
#+BEGIN_EXAMPLE
25000
等级到达95级
#+END_EXAMPLE

*** 剑者·逸
- 功力37000获得头顶图案
#+BEGIN_EXAMPLE
37000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇·壹
- 100级后功力达到25200
#+BEGIN_EXAMPLE
25200
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇·贰
- 100级后功力达到25400
#+BEGIN_EXAMPLE
25400
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇·叁
- 100级后功力达到25600
#+BEGIN_EXAMPLE
25600
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇·肆
- 100级后功力达到25800
#+BEGIN_EXAMPLE
25800
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇·伍
- 100级后功力达到26000
#+BEGIN_EXAMPLE
26000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇陆
- 100级后功力达到26500
#+BEGIN_EXAMPLE
26500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇柒
- 100级后功力达到27000
#+BEGIN_EXAMPLE
27000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇捌
- 100级后功力达到27500
#+BEGIN_EXAMPLE
27500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇玖
- 100级后功力达到28000
#+BEGIN_EXAMPLE
28000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾
- 100级后功力达到28500
#+BEGIN_EXAMPLE
28500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾壹
- 100级后功力达到29000
#+BEGIN_EXAMPLE
29000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾贰
- 100级后功力达到29500
#+BEGIN_EXAMPLE
29500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾叁
- 100级后功力达到30000
#+BEGIN_EXAMPLE
30000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾肆
- 100级后功力达到30500
#+BEGIN_EXAMPLE
30500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾伍
- 100级后功力达到31000
#+BEGIN_EXAMPLE
31000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾陆
- 100级后功力达到31500
#+BEGIN_EXAMPLE
31500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾柒
- 100级后功力达到32000
#+BEGIN_EXAMPLE
32000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾捌
- 100级后功力达到32500
#+BEGIN_EXAMPLE
32500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇拾玖
- 100级后功力达到33000
#+BEGIN_EXAMPLE
33000
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇贰拾
- 100级后功力达到33500
#+BEGIN_EXAMPLE
33500
等级到达100级
#+END_EXAMPLE

*** 武镇寰宇贰拾壹
- 100级后功力达到34000
#+BEGIN_EXAMPLE
34000
等级到达100级
#+END_EXAMPLE

** 战力
*** 初涉正邪·壹
- 31级后战力达到2000
#+BEGIN_EXAMPLE
战力达到2000
等级到达31级
#+END_EXAMPLE

*** 初涉正邪·贰
- 31级后战力达到2500
#+BEGIN_EXAMPLE
战力达到2500
等级到达31级
#+END_EXAMPLE

*** 以武正心·壹
- 41级后战力达到3000
#+BEGIN_EXAMPLE
战力达到3000
等级到达41级
#+END_EXAMPLE

*** 以武正心·贰
- 41级后战力达到3500
#+BEGIN_EXAMPLE
战力达到3500
等级到达41级
#+END_EXAMPLE

*** 侠心初成·壹
- 51级后战力达到4000
#+BEGIN_EXAMPLE
战力达到4000
等级到达51级
#+END_EXAMPLE

*** 侠心初成·贰
- 51级后战力达到4500
#+BEGIN_EXAMPLE
战力达到4500
等级到达51级
#+END_EXAMPLE

*** 侠心初成·叁
- 51级后战力达到5000
#+BEGIN_EXAMPLE
战力达到5000
等级到达51级
#+END_EXAMPLE

*** 侠心炼武·壹
- 61级后战力达到5500
#+BEGIN_EXAMPLE
战力达到5500
等级到达61级
#+END_EXAMPLE

*** 侠心炼武·贰
- 61级后战力达到6000
#+BEGIN_EXAMPLE
战力达到6000
等级到达61级
#+END_EXAMPLE

*** 侠心炼武·叁
- 61级后战力达到6500
#+BEGIN_EXAMPLE
战力达到6500
等级到达61级
#+END_EXAMPLE

*** 侠武破命·壹
- 71级后战力达到7000
#+BEGIN_EXAMPLE
战力达到7000
等级到达71级
#+END_EXAMPLE

*** 侠武破命·贰
- 71级后战力达到7500
#+BEGIN_EXAMPLE
战力达到7500
等级到达71级
#+END_EXAMPLE

*** 侠武破命·叁
- 71级后战力达到8000
#+BEGIN_EXAMPLE
战力达到8000
等级到达71级
#+END_EXAMPLE

*** 侠骨天成·壹
- 81级后战力达到8500
#+BEGIN_EXAMPLE
战力达到8500
等级到达81级
#+END_EXAMPLE

*** 侠骨天成·贰
- 81级后战力达到9000
#+BEGIN_EXAMPLE
战力达到9000
等级到达81级
#+END_EXAMPLE

*** 侠骨天成·叁
- 81级后战力达到9500
#+BEGIN_EXAMPLE
战力达到9500
等级到达81级
#+END_EXAMPLE

*** 侠骨天成·肆
- 81级后战力达到10000
#+BEGIN_EXAMPLE
战力达到10000
等级到达81级
#+END_EXAMPLE

*** 侠行天道·壹
- 85级后战力达到11000
#+BEGIN_EXAMPLE
战力达到11000
等级到达85级
#+END_EXAMPLE

*** 侠行天道·贰
- 85级后战力达到12000
#+BEGIN_EXAMPLE
战力达到12000
等级到达85级
#+END_EXAMPLE

*** 侠行天道·叁
- 90级后战力达到12500
#+BEGIN_EXAMPLE
战力达到12500
等级到达90级
#+END_EXAMPLE

*** 侠行天道·肆
- 90级后战力达到13000
#+BEGIN_EXAMPLE
战力达到13000
等级到达90级
#+END_EXAMPLE

*** 侠行天道·伍
- 90级后战力达到13500
#+BEGIN_EXAMPLE
战力达到13500
等级到达90级
#+END_EXAMPLE

*** 侠行天道·陆
- 90级后战力达到14000
#+BEGIN_EXAMPLE
战力达到14000
等级到达90级
#+END_EXAMPLE

*** 侠行天道·柒
- 90级后战力达到14500
#+BEGIN_EXAMPLE
战力达到14500
等级到达90级
#+END_EXAMPLE

*** 侠行天道·捌
- 90级后战力达到15000
#+BEGIN_EXAMPLE
战力达到15000
等级到达90级
#+END_EXAMPLE

*** 侠行天道·玖
- 90级后战力达到15500
#+BEGIN_EXAMPLE
战力达到15500
等级到达90级
#+END_EXAMPLE

*** 侠行天道·拾
- 90级后战力达到16000
#+BEGIN_EXAMPLE
战力达到16000
等级到达90级
#+END_EXAMPLE

*** 侠念天心·壹
- 90级后战力达到16500
#+BEGIN_EXAMPLE
战力达到16500
等级到达90级
#+END_EXAMPLE

*** 侠念天心·贰
- 90级后战力达到17000
#+BEGIN_EXAMPLE
战力达到17000
等级到达90级
#+END_EXAMPLE

*** 侠念天心·叁
- 90级后战力达到17500
#+BEGIN_EXAMPLE
战力达到17500
等级到达90级
#+END_EXAMPLE

*** 侠念天心·肆
- 90级后战力达到18000
#+BEGIN_EXAMPLE
战力达到18000
等级到达90级
#+END_EXAMPLE

*** 侠念天心·伍
- 90级后战力达到18250
#+BEGIN_EXAMPLE
战力达到18250
等级到达90级
#+END_EXAMPLE

*** 侠念天心·陆
- 90级后战力达到18500
#+BEGIN_EXAMPLE
战力达到18500
等级到达90级
#+END_EXAMPLE

*** 侠念天心·柒
- 90级后战力达到18750
#+BEGIN_EXAMPLE
战力达到18750
等级到达90级
#+END_EXAMPLE

*** 侠念天心·捌
- 90级后战力达到19000
#+BEGIN_EXAMPLE
战力达到19000
等级到达90级
#+END_EXAMPLE

*** 侠念天心·玖
- 90级后战力达到19250
#+BEGIN_EXAMPLE
战力达到19250
等级到达90级
#+END_EXAMPLE

*** 侠念天心·拾
- 90级后战力达到19500
#+BEGIN_EXAMPLE
战力达到19500
等级到达90级
#+END_EXAMPLE

*** 侠念天心·拾壹
- 90级后战力达到19750
#+BEGIN_EXAMPLE
战力达到19750
等级到达90级
#+END_EXAMPLE

*** 绝代侠客·壹
- 90级后战力达到20000
#+BEGIN_EXAMPLE
战力达到20000
等级到达90级
#+END_EXAMPLE

*** 绝代侠客·贰
- 95级后战力达到22500
#+BEGIN_EXAMPLE
22500
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·叁
- 95级后战力达到22750
#+BEGIN_EXAMPLE
22750
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·肆
- 95级后战力达到23000
#+BEGIN_EXAMPLE
23000
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·伍
- 95级后战力达到23250
#+BEGIN_EXAMPLE
23250
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·陆
- 95级后战力达到23500
#+BEGIN_EXAMPLE
23500
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·柒
- 95级后战力达到23750
#+BEGIN_EXAMPLE
23750
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·捌
- 95级后战力达到24000
#+BEGIN_EXAMPLE
24000
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·玖
- 95级后战力达到24250
#+BEGIN_EXAMPLE
24250
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·拾
- 95级后战力达到24500
#+BEGIN_EXAMPLE
24500
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·拾壹
- 95级后战力达到24750
#+BEGIN_EXAMPLE
24750
等级到达95级
#+END_EXAMPLE

*** 绝代侠客·拾贰
- 95级后战力达到25000
#+BEGIN_EXAMPLE
25000
等级到达95级
#+END_EXAMPLE

*** 战者·勇
- 战力42000获得头顶图案
#+BEGIN_EXAMPLE
42000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵·壹
- 100级后战力达到25200
#+BEGIN_EXAMPLE
25200
等级到达100级
#+END_EXAMPLE

*** 侠者天纵·贰
- 100级后战力达到25400
#+BEGIN_EXAMPLE
25400
等级到达100级
#+END_EXAMPLE

*** 侠者天纵·叁
- 100级后战力达到25600
#+BEGIN_EXAMPLE
25600
等级到达100级
#+END_EXAMPLE

*** 侠者天纵·肆
- 100级后战力达到25800
#+BEGIN_EXAMPLE
25800
等级到达100级
#+END_EXAMPLE

*** 侠者天纵·伍
- 100级后战力达到26000
#+BEGIN_EXAMPLE
26000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵陆
- 100级后战力达到26500
#+BEGIN_EXAMPLE
26500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵柒
- 100级后战力达到27000
#+BEGIN_EXAMPLE
27000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵捌
- 100级后战力达到27500
#+BEGIN_EXAMPLE
27500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵玖
- 100级后战力达到28000
#+BEGIN_EXAMPLE
28000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾
- 100级后战力达到28500
#+BEGIN_EXAMPLE
28500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾壹
- 100级后战力达到29000
#+BEGIN_EXAMPLE
29000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾贰
- 100级后战力达到29500
#+BEGIN_EXAMPLE
29500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾叁
- 100级后战力达到30000
#+BEGIN_EXAMPLE
30000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾肆
- 100级后战力达到30500
#+BEGIN_EXAMPLE
30500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾伍
- 100级后战力达到31000
#+BEGIN_EXAMPLE
31000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾陆
- 100级后战力达到31500
#+BEGIN_EXAMPLE
31500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾柒
- 100级后战力达到32000
#+BEGIN_EXAMPLE
32000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾捌
- 100级后战力达到32500
#+BEGIN_EXAMPLE
32500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵拾玖
- 100级后战力达到33000
#+BEGIN_EXAMPLE
33000
等级到达100级
#+END_EXAMPLE

*** 侠者天纵贰拾
- 100级后战力达到33500
#+BEGIN_EXAMPLE
33500
等级到达100级
#+END_EXAMPLE

*** 侠者天纵贰拾壹
- 100级后战力达到34000
#+BEGIN_EXAMPLE
34000
等级到达100级
#+END_EXAMPLE

*** 绝代侠客·贰1
- 战力21000追级成就
#+BEGIN_EXAMPLE
21000
等级到达100级
#+END_EXAMPLE

*** 绝代侠客·贰2
- 战力22000追级成就
#+BEGIN_EXAMPLE
22000
等级到达100级
#+END_EXAMPLE

* 社交
** 帮派
*** 天波府之试
- 28级去杭州找天波府执事参加考验，完成试练后，能得到朝廷的认可，就可以创建属于自己的帮派了！
#+BEGIN_EXAMPLE
天波府之试
#+END_EXAMPLE

*** 初入帮派
- 加入一个帮派，从此不再孤军奋战！
#+BEGIN_EXAMPLE
加入帮派
#+END_EXAMPLE

*** 帮派福利
- 初次领取帮派福利
#+BEGIN_EXAMPLE
领取福利
#+END_EXAMPLE

*** 累计三天
- 领取帮派福利达到3次
#+BEGIN_EXAMPLE
领取福利
#+END_EXAMPLE

*** 累计七天
- 领取帮派福利达到7次
#+BEGIN_EXAMPLE
领取福利
#+END_EXAMPLE

*** 帮派骨干
- 领取帮派福利达到35次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 长情帮众
- 领取帮派福利达到120次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 帮派元老
- 领取帮派福利达到360次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 一级帮派
- 所在的帮派达到1级
#+BEGIN_EXAMPLE
1级帮
#+END_EXAMPLE

*** 二级帮派
- 所在的帮派达到2级
#+BEGIN_EXAMPLE
2级帮
#+END_EXAMPLE

*** 三级帮派
- 所在的帮派达到3级
#+BEGIN_EXAMPLE
3级帮
#+END_EXAMPLE

*** 四级帮派
- 所在的帮派达到4级
#+BEGIN_EXAMPLE
4级帮
#+END_EXAMPLE

*** 五级帮派
- 所在的帮派达到5级
#+BEGIN_EXAMPLE
5级帮
#+END_EXAMPLE

*** 六级帮派
- 所在的帮派达到6级
#+BEGIN_EXAMPLE
6级帮
#+END_EXAMPLE

*** 七级帮派
- 所在的帮派达到7级
#+BEGIN_EXAMPLE
7级帮
#+END_EXAMPLE

*** 八级帮派
- 所在的帮派达到8级
#+BEGIN_EXAMPLE
8级帮
#+END_EXAMPLE

*** 九级帮派
- 所在的帮派达到9级
#+BEGIN_EXAMPLE
9级帮
#+END_EXAMPLE

*** 十级帮派
- 所在的帮派达到10级
#+BEGIN_EXAMPLE
10级帮
#+END_EXAMPLE

*** 十一级帮
- 所在的帮派达到11级
#+BEGIN_EXAMPLE
11级帮
#+END_EXAMPLE

*** 十二级帮
- 所在的帮派达到12级
#+BEGIN_EXAMPLE
12级帮
#+END_EXAMPLE

*** 十三级帮派
- 所在的帮派达到13级
#+BEGIN_EXAMPLE
13级帮
#+END_EXAMPLE

*** 十四级帮派
- 所在的帮派达到14级
#+BEGIN_EXAMPLE
14级帮
#+END_EXAMPLE

*** 十五级帮派
- 所在的帮派达到15级
#+BEGIN_EXAMPLE
15级帮
#+END_EXAMPLE

*** 十六级帮派
- 所在的帮派达到16级
#+BEGIN_EXAMPLE
16级帮
#+END_EXAMPLE

*** 十七级帮派
- 所在的帮派达到17级
#+BEGIN_EXAMPLE
17级帮
#+END_EXAMPLE

*** 十八级帮派
- 所在的帮派达到18级
#+BEGIN_EXAMPLE
18级帮
#+END_EXAMPLE

*** 十九级帮派
- 所在的帮派达到19级
#+BEGIN_EXAMPLE
19级帮
#+END_EXAMPLE

*** 二十级帮派
- 所在的帮派达到20级
#+BEGIN_EXAMPLE
20级帮
#+END_EXAMPLE

*** 二十一级帮派
- 所在的帮派达到21级
#+BEGIN_EXAMPLE
21级帮
#+END_EXAMPLE

*** 二十二级帮派
- 所在的帮派达到22级
#+BEGIN_EXAMPLE
22级帮
#+END_EXAMPLE

*** 二十三级帮派
- 所在的帮派达到23级
#+BEGIN_EXAMPLE
23级帮
#+END_EXAMPLE

*** 二十四级帮派
- 所在的帮派达到24级
#+BEGIN_EXAMPLE
24级帮
#+END_EXAMPLE

*** 二十五级帮派
- 所在的帮派达到25级
#+BEGIN_EXAMPLE
25级帮
#+END_EXAMPLE

** 盟会
*** 斗智斗勇
- 完成5个任意盟会日常
#+BEGIN_EXAMPLE
5个盟会日常
#+END_EXAMPLE

*** 初入盟会
- 第一次加入盟会
#+BEGIN_EXAMPLE
加入盟会
#+END_EXAMPLE

*** 帝王州!
- 加入帝王州
#+BEGIN_EXAMPLE
加入帝王州
#+END_EXAMPLE

*** 寒江城!
- 加入寒江城
#+BEGIN_EXAMPLE
加入寒江城
#+END_EXAMPLE

*** 水龙吟!
- 加入水龙吟
#+BEGIN_EXAMPLE
加入水龙吟
#+END_EXAMPLE

*** 万里杀!
- 加入万里杀
#+BEGIN_EXAMPLE
加入万里杀
#+END_EXAMPLE

*** 尊为盟主
- 盟主:义薄云天气盖世，叱诧风云自生威。
#+BEGIN_EXAMPLE
盟主
#+END_EXAMPLE

*** 尊为副盟主
- 副盟主:   结义之交同手足，励精图治必躬亲。
#+BEGIN_EXAMPLE
副盟主
#+END_EXAMPLE

*** 尊为军师
- 盟会军师:    运筹帷幄定山河，宁静致远淡名利。
#+BEGIN_EXAMPLE
军师
#+END_EXAMPLE

*** 尊为统领
- 盟会统领:    忠肝义胆英雄志，铁血安邦扫千军。
#+BEGIN_EXAMPLE
统领
#+END_EXAMPLE

*** 盟会照拂
- 加入盟会，自然就有盟会俸禄
#+BEGIN_EXAMPLE
领取盟会俸禄
#+END_EXAMPLE

*** 九州帝王
- 加入帝王州并到达35级
#+BEGIN_EXAMPLE
加入帝王州
到达35级
#+END_EXAMPLE

*** 寒雨连江
- 加入寒江城并到达35级
#+BEGIN_EXAMPLE
加入寒江城
到达35级
#+END_EXAMPLE

*** 龙吟水上
- 加入水龙吟并到达35级
#+BEGIN_EXAMPLE
加入水龙吟
到达35级
#+END_EXAMPLE

*** 万里飞沙
- 加入万里杀并到达35级
#+BEGIN_EXAMPLE
加入万里杀
到达35级
#+END_EXAMPLE

*** 顺应天意
- 使用测卦选盟加入盟会
#+BEGIN_EXAMPLE
使用测卦选盟
#+END_EXAMPLE

*** 大道为公·肆
- 成为总舵主并领取一次盟会俸禄（帝王州）
#+BEGIN_EXAMPLE
总舵主
领取一次盟会俸禄
加入帝王州
#+END_EXAMPLE

*** 大道为公·叁
- 成为副舵主并领取一次盟会俸禄（帝王州）
#+BEGIN_EXAMPLE
副舵主
领取一次盟会俸禄
加入帝王州
#+END_EXAMPLE

*** 大道为公·贰
- 成为盟会军师并领取一次盟会俸禄（帝王州）
#+BEGIN_EXAMPLE
盟会军师
领取一次盟会俸禄
加入帝王州
#+END_EXAMPLE

*** 大道为公
- 成为盟会统领并领取一次盟会俸禄（帝王州）
#+BEGIN_EXAMPLE
盟会统领
领取一次盟会俸禄
加入帝王州
#+END_EXAMPLE

*** 玄甲·长宁
- 成为盟会统领（帝王州）
#+BEGIN_EXAMPLE
统领
加入帝王州
#+END_EXAMPLE

*** 君临·寒江
- 寒江城总舵主
#+BEGIN_EXAMPLE
盟主
加入寒江城
#+END_EXAMPLE

*** 君临·帝王
- 帝王州总舵主
#+BEGIN_EXAMPLE
盟主
加入帝王州
#+END_EXAMPLE

*** 君临·万里
- 万里杀总舵主
#+BEGIN_EXAMPLE
盟主
加入万里杀
#+END_EXAMPLE

*** 君临·水龙
- 水龙吟总舵主
#+BEGIN_EXAMPLE
盟主
加入水龙吟
#+END_EXAMPLE

*** 一方之主
- 自己的联盟占有地盘，并且自己身为龙首
#+BEGIN_EXAMPLE
成为龙首
当前占领地盘
#+END_EXAMPLE

** 好友
*** 呼朋唤友
- “从来江湖只一人”？
#+BEGIN_EXAMPLE
1个好友
#+END_EXAMPLE

*** 好友五十人
- 结交拥有了五十个好友，各大门派弟子都有
#+BEGIN_EXAMPLE
50好友
#+END_EXAMPLE

*** 好友二百人
- 结交已经拥有了到达好友上限数目的好友数！
#+BEGIN_EXAMPLE
200好友
#+END_EXAMPLE

*** 挚交好友
- 结交一个友好度达超过23300的好友
#+BEGIN_EXAMPLE
1个好友
#+END_EXAMPLE

*** 金兰之交
- 结交友好度达超过23300的好友5人
#+BEGIN_EXAMPLE
5个好友
#+END_EXAMPLE

*** 断金之友
- 结交友好度达超过23300的好友10人
#+BEGIN_EXAMPLE
10个好友
#+END_EXAMPLE

*** 桃李之馈
- 赠送过礼物给他人
#+BEGIN_EXAMPLE
赠送礼物
#+END_EXAMPLE

*** 礼尚往来
- 收到过他人赠送的礼物
#+BEGIN_EXAMPLE
收到礼物
#+END_EXAMPLE

*** 交际达人
- 赠送过礼物给他人50次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 广受欢迎
- 收到过他人赠送的礼物50次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 出手大方
- 赠送过礼物给他人150次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 门庭若市
- 收到过他人赠送的礼物150次
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 社交达人
- 赠送过礼物给他人200次
#+BEGIN_EXAMPLE
赠送过礼物给他人200次
#+END_EXAMPLE

*** 广结良缘
- 赠送过礼物给他人250次
#+BEGIN_EXAMPLE
赠送过礼物给他人250次
#+END_EXAMPLE

*** 掷果盈车
- 收到过他人赠送的礼物200次
#+BEGIN_EXAMPLE
收到过他人赠送的礼物200次
#+END_EXAMPLE

*** 众星捧月
- 收到过他人赠送的礼物250次
#+BEGIN_EXAMPLE
收到过他人赠送的礼物250次
#+END_EXAMPLE

* 世界成就
** 世界成就
*** 龙首山初捷
- 服务器中有侠士率先通关话本龙首山
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 初探郡王府
- 服务器中有侠士率先通关探索见闻夜探郡王府
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 郡王府初捷
- 服务器中有侠士率先通关话本强攻郡王府
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 神武门初捷
- 服务器中有侠士率先通关话本神武门
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 血衣楼初捷
- 服务器中有侠士率先通关话本血衣楼
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 浴血龙首山初捷
- 服务器中有侠士率先通关浴血龙首山
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 黑狱初捷
- 服务器中有侠士率先通关话本雨夜镇天牢
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 苍梧城初捷
- 服务器中有侠士率先通关话本普通·血战苍梧城
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 浴血郡王府初捷
- 服务器中有侠士率先通关话本挑战·鏖战郡王府
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 浴血血衣楼初捷
- 服务器中有侠士率先通关话本挑战·奇袭血衣楼
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 浴血镇天牢初捷
- 服务器中有侠士率先通关话本挑战·雨夜镇天牢
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 浴血神武门初捷
- 服务器中有侠士率先通关话本挑战·强袭神武门
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 浴血苍梧城初捷
- 服务器中有侠士率先通关话本挑战·血战苍梧城
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 万雪窟初捷
- 服务器中有侠士率先通关话本普通·喋血万雪窟
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 喋血万雪窟初捷
- 服务器中有侠士率先通关话本挑战·喋血万雪窟
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 普通·天峰会八荒初捷
- 服务器中有侠士率先通关话本普通·天峰会八荒
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挑战·天峰会八荒初捷
- 服务器中有侠士率先通关话本挑战·天峰会八荒
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挑战·琴魔初捷
- 服务器中有侠士率先通关话本挑战·琴魔
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 普通·开封会八荒初捷
- 服务器中有侠士率先通关话本普通·开封会八荒
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挑战·开封会八荒初捷
- 服务器中有侠士率先通关话本挑战·开封会八荒
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 普通·决战嘲天宫初捷
- 服务器中有侠士率先通关话本普通·决战嘲天宫
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挑战·决战嘲天宫初捷
- 服务器中有侠士率先通关话本挑战·决战嘲天宫
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 普通·东海会四盟初捷
- 服务器中有侠士率先通关话本普通·东海会四盟
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挑战·东海会四盟初捷
- 服务器中有侠士率先通关话本挑战·东海会四盟
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 普通·雨夜破天牢初捷
- 服务器中有侠士率先通关话本普通·雨夜破天牢
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挑战·雨夜破天牢初捷
- 服务器中有侠士率先通关话本挑战·雨夜破天牢
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 堆个大雪人·天峰盟
- 天峰盟的雪人堆成了！
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 堆个大雪人·青龙会
- 青龙会的雪人堆成了！
#+BEGIN_EXAMPLE
#+END_EXAMPLE

* PVP
** 切磋
*** 小试身手
- 赢得一次切磋
#+BEGIN_EXAMPLE
切磋胜利
#+END_EXAMPLE

*** 不伤和气
- 赢得10次切磋
#+BEGIN_EXAMPLE
赢得10次切磋
#+END_EXAMPLE

*** 技高一筹
- 赢得120次切磋
#+BEGIN_EXAMPLE
赢得120次切磋
#+END_EXAMPLE

*** 初尝败绩
- 输掉一次切磋
#+BEGIN_EXAMPLE
切磋失败
#+END_EXAMPLE

*** 战无不胜
- 切磋连赢3次
#+BEGIN_EXAMPLE
已胜利场次
#+END_EXAMPLE

*** 屡败屡战
- 切磋连输3次
#+BEGIN_EXAMPLE
已经失利场次
#+END_EXAMPLE

*** 疾风骤雨
- 30秒内结束切磋
#+BEGIN_EXAMPLE
极速切磋
#+END_EXAMPLE

** 江湖名望
*** 初入江湖
- 江湖名望达到1级
#+BEGIN_EXAMPLE
江湖名望达到1级
#+END_EXAMPLE

*** 寂寂无名
- 江湖名望达到2级
#+BEGIN_EXAMPLE
江湖名望达到2级
#+END_EXAMPLE

*** 后起之秀
- 江湖名望达到3级
#+BEGIN_EXAMPLE
江湖名望达到3级
#+END_EXAMPLE

*** 江湖少侠
- 江湖名望达到4级
#+BEGIN_EXAMPLE
江湖名望达到4级
#+END_EXAMPLE

*** 武林新贵
- 江湖名望达到5级
#+BEGIN_EXAMPLE
江湖名望达到5级
#+END_EXAMPLE

*** 小有所成
- 江湖名望达到6级
#+BEGIN_EXAMPLE
江湖名望达到6级
#+END_EXAMPLE

*** 武林高手
- 江湖名望达到7级
#+BEGIN_EXAMPLE
江湖名望达到7级
#+END_EXAMPLE

*** 英雄豪杰
- 江湖名望达到8级
#+BEGIN_EXAMPLE
江湖名望达到8级
#+END_EXAMPLE

*** 人中龙凤
- 江湖名望达到9级
#+BEGIN_EXAMPLE
江湖名望达到9级
#+END_EXAMPLE

*** 名震江湖
- 江湖名望达到10级
#+BEGIN_EXAMPLE
江湖名望达到10级
#+END_EXAMPLE

*** 傲视群雄
- 江湖名望达到11级
#+BEGIN_EXAMPLE
江湖名望达到11级
#+END_EXAMPLE

*** 开宗立派
- 江湖名望达到12级
#+BEGIN_EXAMPLE
江湖名望达到12级
#+END_EXAMPLE

*** 一代宗师
- 江湖名望达到13级
#+BEGIN_EXAMPLE
江湖名望达到13级
#+END_EXAMPLE

*** 仗剑天涯
- 江湖名望达到14级
#+BEGIN_EXAMPLE
江湖名望达到14级
#+END_EXAMPLE

*** 笑傲江湖
- 江湖名望达到15级
#+BEGIN_EXAMPLE
江湖名望达到15级
#+END_EXAMPLE

*** 独孤求败
- 江湖名望达到16级
#+BEGIN_EXAMPLE
江湖名望达到16级
#+END_EXAMPLE

*** 激战证明
- 累计获得15000胜负令
#+BEGIN_EXAMPLE
累计获得15000胜负令
#+END_EXAMPLE

*** 激战证明·二
- 累计获得30000胜负令
#+BEGIN_EXAMPLE
累计获得30000胜负令
#+END_EXAMPLE

*** 激战证明·三
- 累计获得100000胜负令
#+BEGIN_EXAMPLE
累计获得100000胜负令
#+END_EXAMPLE

*** 激战证明·四
- 累计获得200000胜负令
#+BEGIN_EXAMPLE
累计获得200000胜负令
#+END_EXAMPLE

*** 激战证明·五
- 累计获得500000胜负令
#+BEGIN_EXAMPLE
累计获得500000胜负令
#+END_EXAMPLE

*** 战绩彪悍
- 累计获得10000名望
#+BEGIN_EXAMPLE
累计获得10000名望
#+END_EXAMPLE

*** 战绩彪悍·二
- 累计获得30000名望
#+BEGIN_EXAMPLE
累计获得30000名望
#+END_EXAMPLE

*** 战绩彪悍·三
- 累计获得80000名望
#+BEGIN_EXAMPLE
累计获得80000名望
#+END_EXAMPLE

*** 战绩彪悍·四
- 累计获得150000名望
#+BEGIN_EXAMPLE
累计获得150000名望
#+END_EXAMPLE

*** 松林之道
- 松林问战获胜60场
#+BEGIN_EXAMPLE
松林问战60场
#+END_EXAMPLE

*** 松林之道·二
- 松林问战获胜100场
#+BEGIN_EXAMPLE
松林问战100场
#+END_EXAMPLE

*** 松林之道·三
- 松林问战获胜150场
#+BEGIN_EXAMPLE
松林问战150场
#+END_EXAMPLE

*** 孤月之道
- 长洲孤月获胜60场
#+BEGIN_EXAMPLE
长洲孤月60场
#+END_EXAMPLE

*** 孤月之道·二
- 长洲孤月获胜100场
#+BEGIN_EXAMPLE
长洲孤月100场
#+END_EXAMPLE

*** 孤月之道·三
- 长洲孤月获胜150场
#+BEGIN_EXAMPLE
长洲孤月150场
#+END_EXAMPLE

*** 松林杀手
- 在松林问战中击杀150人
#+BEGIN_EXAMPLE
在松林问战中击杀150人
#+END_EXAMPLE

*** 松林杀手·二
- 在松林问战中击杀250人
#+BEGIN_EXAMPLE
在松林问战中击杀250人
#+END_EXAMPLE

*** 松林杀手·三
- 在松林问战中击杀450人
#+BEGIN_EXAMPLE
在松林问战中击杀450人
#+END_EXAMPLE

*** 松林杀手·四
- 在松林问战中击杀600人
#+BEGIN_EXAMPLE
在松林问战中击杀600人
#+END_EXAMPLE

*** 孤月杀手
- 长洲孤月中击杀150人
#+BEGIN_EXAMPLE
长洲孤月中击杀150人
#+END_EXAMPLE

*** 孤月杀手·二
- 长洲孤月中击杀250人
#+BEGIN_EXAMPLE
长洲孤月中击杀250人
#+END_EXAMPLE

*** 孤月杀手·三
- 长洲孤月中击杀450人
#+BEGIN_EXAMPLE
长洲孤月中击杀450人
#+END_EXAMPLE

*** 孤月杀手·四
- 长洲孤月中击杀600人
#+BEGIN_EXAMPLE
长洲孤月中击杀600人
#+END_EXAMPLE

*** 联盟勇士
- 掠夺战中击杀150人
#+BEGIN_EXAMPLE
掠夺战中击杀150人
#+END_EXAMPLE

*** 联盟勇士·二
- 掠夺战中击杀250人
#+BEGIN_EXAMPLE
掠夺战中击杀250人
#+END_EXAMPLE

*** 联盟勇士·三
- 掠夺战中击杀450人
#+BEGIN_EXAMPLE
掠夺战中击杀450人
#+END_EXAMPLE

*** 联盟勇士·四
- 掠夺战中击杀600人
#+BEGIN_EXAMPLE
掠夺战中击杀600人
#+END_EXAMPLE

*** 争锋难敌
- 争锋战中击杀150人
#+BEGIN_EXAMPLE
争锋战中击杀150人
#+END_EXAMPLE

*** 争锋难敌·二
- 争锋战中击杀250人
#+BEGIN_EXAMPLE
争锋战中击杀250人
#+END_EXAMPLE

*** 争锋难敌·三
- 争锋战中击杀450人
#+BEGIN_EXAMPLE
争锋战中击杀450人
#+END_EXAMPLE

*** 争锋难敌·四
- 争锋战中击杀600人
#+BEGIN_EXAMPLE
争锋战中击杀600人
#+END_EXAMPLE

** 论剑
*** 一段
- 竞技场1段
#+BEGIN_EXAMPLE
竞技场1段
#+END_EXAMPLE

*** 二段
- 竞技场2段
#+BEGIN_EXAMPLE
竞技场2段
#+END_EXAMPLE

*** 三段
- 竞技场3段
#+BEGIN_EXAMPLE
竞技场3段
#+END_EXAMPLE

*** 四段
- 竞技场4段
#+BEGIN_EXAMPLE
竞技场4段
#+END_EXAMPLE

*** 五段
- 竞技场5段
#+BEGIN_EXAMPLE
竞技场5段
#+END_EXAMPLE

*** 六段
- 竞技场6段
#+BEGIN_EXAMPLE
竞技场6段
#+END_EXAMPLE

*** 七段
- 竞技场7段
#+BEGIN_EXAMPLE
竞技场7段
#+END_EXAMPLE

*** 八段
- 竞技场8段
#+BEGIN_EXAMPLE
竞技场8段
#+END_EXAMPLE

*** 九段
- 竞技场9段
#+BEGIN_EXAMPLE
竞技场9段
#+END_EXAMPLE

*** 试剑
- 竞技场10段
#+BEGIN_EXAMPLE
竞技场10段
#+END_EXAMPLE

*** 利剑
- 竞技场11段
#+BEGIN_EXAMPLE
竞技场11段
#+END_EXAMPLE

*** 快剑
- 竞技场12段
#+BEGIN_EXAMPLE
竞技场12段
#+END_EXAMPLE

*** 飞剑
- 竞技场13段
#+BEGIN_EXAMPLE
竞技场13段
#+END_EXAMPLE

*** 神剑
- 竞技场14段
#+BEGIN_EXAMPLE
竞技场14段
#+END_EXAMPLE

*** 意剑
- 竞技场15段
#+BEGIN_EXAMPLE
竞技场15段
#+END_EXAMPLE

*** 心剑
- 竞技场16段
#+BEGIN_EXAMPLE
竞技场16段
#+END_EXAMPLE

*** 白虹
- 竞技场17段
#+BEGIN_EXAMPLE
竞技场17段
#+END_EXAMPLE

*** 秋水
- 竞技场18段
#+BEGIN_EXAMPLE
竞技场18段
#+END_EXAMPLE

*** 吹雪
- 竞技场19段
#+BEGIN_EXAMPLE
竞技场19段
#+END_EXAMPLE

*** 登峰
- 竞技场20段
#+BEGIN_EXAMPLE
竞技场20段
#+END_EXAMPLE

*** 造极
- 竞技场21段
#+BEGIN_EXAMPLE
竞技场21段
#+END_EXAMPLE

*** 化境
- 竞技场22段
#+BEGIN_EXAMPLE
竞技场22段
#+END_EXAMPLE

*** 武痴
- 竞技场23段
#+BEGIN_EXAMPLE
竞技场23段
#+END_EXAMPLE

*** 武尊
- 竞技场24段
#+BEGIN_EXAMPLE
竞技场24段
#+END_EXAMPLE

*** 武圣
- 竞技场25段
#+BEGIN_EXAMPLE
竞技场25段
#+END_EXAMPLE

*** 求败
- 竞技场26段
#+BEGIN_EXAMPLE
竞技场26段
#+END_EXAMPLE

*** 四海论英雄·新秀
- 四海论英雄活动到达第二关
#+BEGIN_EXAMPLE
四海论英雄活动到达第二关
四海论英雄活动到达第三关
四海论英雄活动到达第四关
四海论英雄活动到达第五关
四海论英雄活动到达第六关
四海论英雄活动到达第七关
#+END_EXAMPLE

*** 四海论英雄·锐气
- 四海论英雄活动到达第三关
#+BEGIN_EXAMPLE
四海论英雄活动到达第三关
四海论英雄活动到达第四关
四海论英雄活动到达第五关
四海论英雄活动到达第六关
四海论英雄活动到达第七关
#+END_EXAMPLE

*** 四海论英雄·英武
- 四海论英雄活动到达第四关
#+BEGIN_EXAMPLE
四海论英雄活动到达第四关
四海论英雄活动到达第五关
四海论英雄活动到达第六关
四海论英雄活动到达第七关
#+END_EXAMPLE

*** 四海论英雄·上游
- 四海论英雄活动到达第五关
#+BEGIN_EXAMPLE
四海论英雄活动到达第五关
四海论英雄活动到达第六关
四海论英雄活动到达第七关
#+END_EXAMPLE

*** 四海论英雄·出众
- 四海论英雄活动到达第六关
#+BEGIN_EXAMPLE
四海论英雄活动到达第六关
四海论英雄活动到达第七关
#+END_EXAMPLE

*** 四海论英雄·卓越
- 四海论英雄活动到达第七关
#+BEGIN_EXAMPLE
四海论英雄活动到达第七关
#+END_EXAMPLE

** 一代宗师
*** 一代宗师·壹
- 一代宗师战场小队第一名1次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名1次
#+END_EXAMPLE

*** 一代宗师·贰
- 一代宗师战场小队第一名3次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名3次
#+END_EXAMPLE

*** 一代宗师·叁
- 一代宗师战场小队第一名5次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名5次
#+END_EXAMPLE

*** 一代宗师·肆
- 一代宗师战场小队第一名10次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名10次
#+END_EXAMPLE

*** 竞秀于林·壹
- 一代宗师战场单局击杀超过10人1次
#+BEGIN_EXAMPLE
一代宗师战场单局击杀超过10人1次
#+END_EXAMPLE

*** 竞秀于林·贰
- 一代宗师战场单局击杀超过10人3次
#+BEGIN_EXAMPLE
一代宗师战场单局击杀超过10人3次
#+END_EXAMPLE

*** 竞秀于林·叁
- 一代宗师战场单局击杀超过10人5次
#+BEGIN_EXAMPLE
一代宗师战场单局击杀超过10人5次
#+END_EXAMPLE

*** 竞秀于林·肆
- 一代宗师战场单局击杀超过10人10次
#+BEGIN_EXAMPLE
一代宗师战场单局击杀超过10人10次
#+END_EXAMPLE

*** 适者生存·壹
- 一代宗师战场累积击杀10人
#+BEGIN_EXAMPLE
一代宗师战场累积击杀10人
#+END_EXAMPLE

*** 适者生存·贰
- 一代宗师战场累积击杀20人
#+BEGIN_EXAMPLE
一代宗师战场累积击杀20人
#+END_EXAMPLE

*** 适者生存·叁
- 一代宗师战场累积击杀50人
#+BEGIN_EXAMPLE
一代宗师战场累积击杀50人
#+END_EXAMPLE

*** 适者生存·肆
- 一代宗师战场累积击杀100人
#+BEGIN_EXAMPLE
一代宗师战场累积击杀100人
#+END_EXAMPLE

*** 适者生存·伍
- 一代宗师战场累积击杀200人
#+BEGIN_EXAMPLE
一代宗师战场累积击杀200人
#+END_EXAMPLE

*** 宗师之路·壹
- 一代宗师积分达到1201
#+BEGIN_EXAMPLE
一代宗师积分达到1201
#+END_EXAMPLE

*** 宗师之路·贰
- 一代宗师积分达到1401
#+BEGIN_EXAMPLE
一代宗师积分达到1401
#+END_EXAMPLE

*** 宗师之路·叁
- 一代宗师积分达到1601
#+BEGIN_EXAMPLE
一代宗师积分达到1601
#+END_EXAMPLE

*** 宗师之路·肆
- 一代宗师积分达到1801
#+BEGIN_EXAMPLE
一代宗师积分达到1801
#+END_EXAMPLE

*** 宗师之路·伍
- 一代宗师积分达到3000
#+BEGIN_EXAMPLE
一代宗师积分达到3000
#+END_EXAMPLE

*** 立地成佛
- 一代宗师战场中0杀获得第一
#+BEGIN_EXAMPLE
一代宗师战场中0杀获得第一
#+END_EXAMPLE

*** 天命龙套
- 一代宗师战场中小队排名倒数第一
#+BEGIN_EXAMPLE
一代宗师战场中小队排名倒数第一
#+END_EXAMPLE

*** 一人之下
- 一代宗师战场中小队排名第二
#+BEGIN_EXAMPLE
一代宗师战场中小队排名第二
#+END_EXAMPLE

*** 一代宗师·伍
- 一代宗师战场小队第一名15次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名15次
#+END_EXAMPLE

*** 一代宗师·陆
- 一代宗师战场小队第一名25次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名25次
#+END_EXAMPLE

*** 一代宗师·柒
- 一代宗师战场小队第一名50次
#+BEGIN_EXAMPLE
一代宗师战场小队第一名50次
#+END_EXAMPLE

*** 竞秀于林·伍
- 一代宗师战场单局击杀超过10人15次
#+BEGIN_EXAMPLE
一代宗师单局击杀10人15次
#+END_EXAMPLE

*** 竞秀于林·陆
- 一代宗师战场单局击杀超过10人25次
#+BEGIN_EXAMPLE
一代宗师单局击杀10人25次
#+END_EXAMPLE

*** 竞秀于林·柒
- 一代宗师战场单局击杀超过10人50次
#+BEGIN_EXAMPLE
一代宗师单局击杀10人50次
#+END_EXAMPLE

*** 竞秀于林·捌
- 一代宗师战场单局击杀超过10人100次
#+BEGIN_EXAMPLE
一代宗师单局击杀10人100次
#+END_EXAMPLE

*** 适者生存·陆
- 一代宗师战场累积击杀250人
#+BEGIN_EXAMPLE
一代宗师战场累计击杀250人
#+END_EXAMPLE

*** 适者生存·柒
- 一代宗师战场累积击杀300人
#+BEGIN_EXAMPLE
一代宗师战场累计击杀300人
#+END_EXAMPLE

*** 适者生存·捌
- 一代宗师战场累积击杀350人
#+BEGIN_EXAMPLE
一代宗师战场累计击杀350人
#+END_EXAMPLE

*** 适者生存·玖
- 一代宗师战场累积击杀500人
#+BEGIN_EXAMPLE
一代宗师战场累计击杀500人
#+END_EXAMPLE

*** 适者生存·拾
- 一代宗师战场累积击杀1000人
#+BEGIN_EXAMPLE
一代宗师战场累计击杀1000人
#+END_EXAMPLE

** 师妹
*** 钟灵毓秀
- 迎接一位师妹
#+BEGIN_EXAMPLE
第一次领养师妹
#+END_EXAMPLE

*** 前程锦绣
- 培养一位师妹至出师
#+BEGIN_EXAMPLE
师妹第一次出师
#+END_EXAMPLE

*** 相忘江湖
- 让一位师妹离开海岛自己闯荡江湖
#+BEGIN_EXAMPLE
第一次解散师妹
#+END_EXAMPLE

*** 游历江湖·壹
- 师妹完成1次游历
#+BEGIN_EXAMPLE
师妹完成1次游历
#+END_EXAMPLE

*** 游历江湖·贰
- 师妹完成10次游历
#+BEGIN_EXAMPLE
师妹完成10次游历
#+END_EXAMPLE

*** 游历江湖·叁
- 师妹完成50次游历
#+BEGIN_EXAMPLE
师妹完成50次游历
#+END_EXAMPLE

*** 游历江湖·肆
- 师妹完成100次游历
#+BEGIN_EXAMPLE
师妹完成100次游历
#+END_EXAMPLE

*** 游历江湖·伍
- 师妹完成200次游历
#+BEGIN_EXAMPLE
师妹完成200次游历
#+END_EXAMPLE

*** 游历江湖·陆
- 师妹完成500次游历
#+BEGIN_EXAMPLE
师妹完成500次游历
#+END_EXAMPLE

*** 名师高徒·壹
- 使用1次名师帖
#+BEGIN_EXAMPLE
使用1次名师帖
#+END_EXAMPLE

*** 名师高徒·贰
- 累计使用15次名师帖
#+BEGIN_EXAMPLE
累计使用15次名师帖
#+END_EXAMPLE

*** 名师高徒·叁
- 累计使用30次名师帖
#+BEGIN_EXAMPLE
累计使用30次名师帖
#+END_EXAMPLE

*** 名师高徒·肆
- 累计使用50次名师帖
#+BEGIN_EXAMPLE
累计使用50次名师帖
#+END_EXAMPLE

*** 清新雅丽
- 为师妹收集一件时装
#+BEGIN_EXAMPLE
收集第一件师妹时装
#+END_EXAMPLE

*** 劳逸结合
- 师妹上一节休息课
#+BEGIN_EXAMPLE
师妹第一次进行休息课
#+END_EXAMPLE

*** 劳形苦心
- 师妹的疲劳值达到100
#+BEGIN_EXAMPLE
师妹疲劳度达到100
#+END_EXAMPLE

*** 侠誉绘采
- 收集到第一张侠誉图
#+BEGIN_EXAMPLE
第一次获得侠誉图
#+END_EXAMPLE

*** 通窍开脉
- 师妹完成游历——通窍开脉
#+BEGIN_EXAMPLE
师妹完成游历——通窍开脉
#+END_EXAMPLE

*** 心助·壹
- 习得蓝色心助技能
#+BEGIN_EXAMPLE
习得蓝色心助技能
#+END_EXAMPLE

*** 心助·贰
- 习得紫色心助技能
#+BEGIN_EXAMPLE
习得紫色心助技能
#+END_EXAMPLE

*** 心助·叁
- 习得金色心助技能
#+BEGIN_EXAMPLE
习得金色心助技能
#+END_EXAMPLE

*** 通力合作
- 习得合击技能
#+BEGIN_EXAMPLE
师妹习得1本合击技能
#+END_EXAMPLE

*** 心领神会·壹
- 将任意蓝色品质心助技能提升至20级
#+BEGIN_EXAMPLE
将任意蓝色心助技能升至满级
#+END_EXAMPLE

*** 心领神会·贰
- 将任意紫色品质心助技能提升至30级
#+BEGIN_EXAMPLE
将任意紫色心助技能升至满级
#+END_EXAMPLE

*** 心领神会·叁
- 将任意金色品质心助技能提升至40级
#+BEGIN_EXAMPLE
将任意金色心助技能升至满级
#+END_EXAMPLE

*** 心领神悟！
- 将任意合击技能提升至30级
#+BEGIN_EXAMPLE
将任意合击技能升至满级
#+END_EXAMPLE

*** 笃实好学
- 使用岁寒系列研习书籍进行1次属性提升
#+BEGIN_EXAMPLE
师妹完成1次研习
#+END_EXAMPLE

*** 学而不厌
- 使用岁寒系列研习书籍进行20次属性提升
#+BEGIN_EXAMPLE
师妹完成20次研习
#+END_EXAMPLE

*** 笃学不倦
- 使用岁寒系列研习书籍进行100次属性提升
#+BEGIN_EXAMPLE
师妹完成100次研习
#+END_EXAMPLE

*** 谋无遗策
- 师妹的韬略属性达到1000点
#+BEGIN_EXAMPLE
师妹的韬略属性达到1000点
#+END_EXAMPLE

*** 典则俊雅
- 师妹的风雅属性达到1000点
#+BEGIN_EXAMPLE
师妹的风雅属性达到1000点
#+END_EXAMPLE

*** 慧心灵性
- 师妹的灵性属性达到1000点
#+BEGIN_EXAMPLE
师妹的灵性属性达到1000点
#+END_EXAMPLE

*** 余音绕梁
- 师妹的乐理属性达到1000点
#+BEGIN_EXAMPLE
师妹的乐理属性达到1000点
#+END_EXAMPLE

*** 目不转睛
- 师妹的专注属性达到1000点
#+BEGIN_EXAMPLE
师妹的专注属性达到1000点
#+END_EXAMPLE

*** 武艺超群·壹
- 师妹武艺总属性达到6000点
#+BEGIN_EXAMPLE
师妹武艺总属性达到6000点
#+END_EXAMPLE

*** 武艺超群·贰
- 师妹武艺总属性达到7500点
#+BEGIN_EXAMPLE
师妹武艺总属性达到7500点
#+END_EXAMPLE

*** 武艺超群·叁
- 师妹武艺总属性达到9000点
#+BEGIN_EXAMPLE
师妹武艺总属性达到9000点
#+END_EXAMPLE

*** 武艺超群·肆
- 师妹武艺总属性达到10500点
#+BEGIN_EXAMPLE
师妹武艺总属性达到10500点
#+END_EXAMPLE

*** 武艺超群·伍
- 师妹武艺总属性达到12000点
#+BEGIN_EXAMPLE
师妹武艺总属性达到12000点
#+END_EXAMPLE

*** 武艺超群·陆
- 师妹武艺总属性达到14000点
#+BEGIN_EXAMPLE
师妹武艺总属性达到14000点
#+END_EXAMPLE

*** 金声玉振·壹
- 师妹才艺总属性达到2500
#+BEGIN_EXAMPLE
师妹才艺总属性达到2500
#+END_EXAMPLE

*** 金声玉振·贰
- 师妹才艺总属性达到3000
#+BEGIN_EXAMPLE
师妹才艺总属性达到3000
#+END_EXAMPLE

*** 金声玉振·叁
- 师妹才艺总属性达到3500
#+BEGIN_EXAMPLE
师妹才艺总属性达到3500
#+END_EXAMPLE

*** 金声玉振·肆
- 师妹才艺总属性达到4000
#+BEGIN_EXAMPLE
师妹才艺总属性达到4000
#+END_EXAMPLE

*** 金声玉振·伍
- 师妹才艺总属性达到4500
#+BEGIN_EXAMPLE
师妹才艺总属性达到4500
#+END_EXAMPLE

*** 金声玉振·陆
- 师妹才艺总属性达到5000
#+BEGIN_EXAMPLE
师妹才艺总属性达到5000
#+END_EXAMPLE

*** 秘会师尊
- 完成游历——秘会师尊
#+BEGIN_EXAMPLE
师妹完成游历——秘会师尊
#+END_EXAMPLE

* 江湖身份
** 身份
*** 千人千面
- 获得江湖身份
#+BEGIN_EXAMPLE
获取江湖身份
#+END_EXAMPLE

*** 猎户
- 成为“猎户”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 杀手
- 获取“杀手”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 游侠
- 成为“游侠”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 镖师
- 获取“镖师”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 乐伶
- 成为“乐伶”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 文士
- 成为“文士”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 捕快
- 成为“捕快”的身份
#+BEGIN_EXAMPLE
江湖身份1级
#+END_EXAMPLE

*** 刺客
- 获取杀手身份中阶能力
#+BEGIN_EXAMPLE
获取杀手身份中阶能力
#+END_EXAMPLE

*** 杀神
- 获取杀手身份高阶能力
#+BEGIN_EXAMPLE
获取杀手身份高阶能力
#+END_EXAMPLE

*** 镖头
- 获取镖师身份中阶能力
#+BEGIN_EXAMPLE
获取镖师身份中阶能力
#+END_EXAMPLE

*** 神镖
- 获取镖师身份高阶能力
#+BEGIN_EXAMPLE
获取镖师身份高阶能力
#+END_EXAMPLE

*** 任侠
- 获取游侠身份的中阶能力
#+BEGIN_EXAMPLE
获取游侠身份的中阶能力
#+END_EXAMPLE

*** 豪侠
- 获取游侠身份的高阶能力
#+BEGIN_EXAMPLE
获取游侠身份的高阶能力
#+END_EXAMPLE

*** 狩矢
- 获取猎户身份的中阶能力
#+BEGIN_EXAMPLE
获取猎户身份的中阶能力
#+END_EXAMPLE

*** 猎圣
- 获取猎户身份的高阶能力
#+BEGIN_EXAMPLE
获取猎户身份的高阶能力
#+END_EXAMPLE

*** 雅士
- 获取文士身份的中阶能力
#+BEGIN_EXAMPLE
获取文士身份的中阶能力
#+END_EXAMPLE

*** 国士
- 获取文士身份的高阶能力
#+BEGIN_EXAMPLE
获取文士身份的高阶能力
#+END_EXAMPLE

*** 优伶
- 获取乐伶身份的中阶能力
#+BEGIN_EXAMPLE
获取乐伶身份的中阶能力
#+END_EXAMPLE

*** 名伶
- 获取乐伶身份的高阶能力
#+BEGIN_EXAMPLE
获取乐伶身份的高阶能力
#+END_EXAMPLE

*** 捕头
- 获取捕快身份的中阶能力
#+BEGIN_EXAMPLE
获取捕快身份的中阶能力
#+END_EXAMPLE

*** 捕神
- 获取捕快身份的高阶能力
#+BEGIN_EXAMPLE
获取捕快身份的高阶能力
#+END_EXAMPLE

** 身份玩法
*** 寻觅宝藏
- 成功完成一次挖宝
#+BEGIN_EXAMPLE
挖宝
#+END_EXAMPLE

*** 一成不变
- 连续三次挖到同样的内容
#+BEGIN_EXAMPLE
相同内容
#+END_EXAMPLE

*** 命中注定
- 连续十次挖到同样的内容
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 初为杀手
- 成功完成一次暗杀
#+BEGIN_EXAMPLE
成功暗杀
#+END_EXAMPLE

*** 刀锋如狂
- 成功完成十次暗杀
#+BEGIN_EXAMPLE
成功完成10次暗杀
#+END_EXAMPLE

*** 暗夜死神
- 成功完成一百次暗杀
#+BEGIN_EXAMPLE
成功完成一百次暗杀
#+END_EXAMPLE

*** 阎王索命
- 成功完成三百五十次暗杀
#+BEGIN_EXAMPLE
成功完成三百五十次暗杀
#+END_EXAMPLE

*** 连环杀劫
- 暗杀连续成功三次
#+BEGIN_EXAMPLE
连续暗杀
#+END_EXAMPLE

*** 从未失手
- 暗杀连续成功十次
#+BEGIN_EXAMPLE
暗杀连续成功十次
#+END_EXAMPLE

*** 准时准刻
- 暗杀连续成功五十次
#+BEGIN_EXAMPLE
暗杀连续成功五十次
#+END_EXAMPLE

*** 避灾解厄
- 成功躲开一次暗杀
#+BEGIN_EXAMPLE
躲开暗杀
#+END_EXAMPLE

*** 狡兔三窟
- 成功躲开三次暗杀
#+BEGIN_EXAMPLE
躲开暗杀
#+END_EXAMPLE

*** 造化通天
- 成功躲开十次暗杀
#+BEGIN_EXAMPLE
躲开暗杀
#+END_EXAMPLE

*** 上天遁地
- 成功躲开五十次暗杀
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 尝试捕猎
- 摆放过所有档次的兽夹
#+BEGIN_EXAMPLE
初级兽夹
中级兽夹
高级兽夹
#+END_EXAMPLE

*** 锦衣玳瑁
- 捕捉到罕见的猫类“锦衣玳瑁”
#+BEGIN_EXAMPLE
锦衣玳瑁
#+END_EXAMPLE

*** 牧野茕茕
- 捕捉到罕见的兔类“牧野茕茕”
#+BEGIN_EXAMPLE
牧野荦荦
#+END_EXAMPLE

*** 百漠青犴
- 捕捉到罕见的犬类“百漠青犴”
#+BEGIN_EXAMPLE
百漠青犴
#+END_EXAMPLE

*** 饮冰飞芒
- 捕捉到罕见的貂类“饮冰飞芒”
#+BEGIN_EXAMPLE
饮冰飞芒
#+END_EXAMPLE

*** 奇珍异兽
- 捕捉到四种罕见动物
#+BEGIN_EXAMPLE
锦衣玳瑁
牧野荦荦
百漠青犴
饮冰飞芒
#+END_EXAMPLE

*** 丰富多彩
- 完成5个任意身份日常
#+BEGIN_EXAMPLE
5个身份日常
#+END_EXAMPLE

*** 繁育后代
- 成功繁殖动物
#+BEGIN_EXAMPLE
繁殖动物
#+END_EXAMPLE

*** 好事成双
- 成功暴击繁殖动物
#+BEGIN_EXAMPLE
动物暴击
#+END_EXAMPLE

*** 幼年伴侣
- 幼年动物伴侣，萌萌哒！
#+BEGIN_EXAMPLE
幼年动物
#+END_EXAMPLE

*** 成年伴侣
- 小动物长大了，萌萌哒！
#+BEGIN_EXAMPLE
成年动物
#+END_EXAMPLE

*** 老年伴侣
- 小动物已经不小了，还是萌萌哒！
#+BEGIN_EXAMPLE
老年动物
#+END_EXAMPLE

*** 一生陪伴
- 天下无不散的宴席，愿再相逢时你我们还能认出彼此
#+BEGIN_EXAMPLE
动物死亡
#+END_EXAMPLE

*** 灵光一闪
- 所拥有的动物学会一个新技能
#+BEGIN_EXAMPLE
动物学会技能
#+END_EXAMPLE

*** 聪明伶俐
- 拥有一只2技能的小宠物
#+BEGIN_EXAMPLE
2技能动物
#+END_EXAMPLE

*** 机灵鬼
- 拥有一只3技能的小宠物
#+BEGIN_EXAMPLE
3技能动物
#+END_EXAMPLE

*** 全能伙伴
- 拥有一只4技能的小宠物
#+BEGIN_EXAMPLE
4技能动物
#+END_EXAMPLE

*** 箭术过人
- 成功在骑射状态下杀死一只动物
#+BEGIN_EXAMPLE
一次骑射
#+END_EXAMPLE

*** 精准无匹
- 成功在骑射状态下杀死十只动物
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 沉迷狩猎
- 成功在骑射状态下杀死一百只动物
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 荒野猎人
- 成功在骑射状态下杀死一千只动物
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 怜花宝藏
- 在发掘怜花宝藏的过程中挖到一次银宝箱
#+BEGIN_EXAMPLE
怜花宝藏
#+END_EXAMPLE

*** 怜花密宝
- 在发掘怜花宝藏的过程中挖到一次金宝箱
#+BEGIN_EXAMPLE
怜花密宝
#+END_EXAMPLE

*** 镖行仁义
- 成功运送过一次仁义镖或威武镖
#+BEGIN_EXAMPLE
镖行仁义
#+END_EXAMPLE

*** 艺高胆大
- 成功运送过五次仁义镖或威武镖
#+BEGIN_EXAMPLE
5次仁义镖
#+END_EXAMPLE

*** 勤勤恳恳
- 成功运送过二十次仁义镖或威武镖
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 生计所迫
- 成功运送过五十次仁义镖或威武镖
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 专业镖师
- 成功运送过五百次仁义镖或威武镖
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 镖行天下
- 成功运送过一次天下镖
#+BEGIN_EXAMPLE
镖行天下
#+END_EXAMPLE

*** 一次不落
- 成功运送过三十五次天下镖
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 拦路横财
- 成功打劫一趟威武镖
#+BEGIN_EXAMPLE
拦路横财
#+END_EXAMPLE

*** 顶风作案
- 成功打劫一趟天下镖
#+BEGIN_EXAMPLE
顶风作案
#+END_EXAMPLE

*** 风雅
- 收藏1处墨宝
#+BEGIN_EXAMPLE
风雅
#+END_EXAMPLE

*** 九华墨宝
- 收藏1条九华的墨宝
#+BEGIN_EXAMPLE
九华墨宝
#+END_EXAMPLE

*** 东越墨宝
- 收藏1条东越的墨宝
#+BEGIN_EXAMPLE
东越墨宝
#+END_EXAMPLE

*** 荆湖墨宝
- 收藏1条荆湖的墨宝
#+BEGIN_EXAMPLE
荆湖墨宝
#+END_EXAMPLE

*** 燕云墨宝
- 收藏1条燕云的墨宝
#+BEGIN_EXAMPLE
燕云墨宝
#+END_EXAMPLE

*** 巴蜀墨宝
- 收藏1条巴蜀的墨宝
#+BEGIN_EXAMPLE
巴蜀墨宝
#+END_EXAMPLE

*** 云滇墨宝
- 收藏1条云滇的墨宝
#+BEGIN_EXAMPLE
云滇墨宝
#+END_EXAMPLE

*** 真武墨宝
- 收藏1条襄州的墨宝
#+BEGIN_EXAMPLE
真武墨宝
#+END_EXAMPLE

*** 秦川墨宝
- 收藏1条秦川的墨宝
#+BEGIN_EXAMPLE
秦川墨宝
#+END_EXAMPLE

*** 杭州墨宝
- 收藏1条杭州的墨宝
#+BEGIN_EXAMPLE
杭州墨宝
#+END_EXAMPLE

*** 江南墨宝
- 收藏1条江南的墨宝
#+BEGIN_EXAMPLE
江南墨宝
#+END_EXAMPLE

*** 开封墨宝
- 收藏1条开封的墨宝
#+BEGIN_EXAMPLE
开封墨宝
#+END_EXAMPLE

*** 徐海墨宝
- 收藏1条徐海的墨宝
#+BEGIN_EXAMPLE
徐海墨宝
#+END_EXAMPLE

*** 文动天下
- 收集过以下地点的墨宝
#+BEGIN_EXAMPLE
九华墨宝
东越墨宝
荆湖墨宝
燕云墨宝
巴蜀墨宝
云滇墨宝
真武墨宝
秦川墨宝
杭州墨宝
江南墨宝
开封墨宝
徐海墨宝
#+END_EXAMPLE

*** 博学
- 收藏墨宝达到35条
#+BEGIN_EXAMPLE
博学
#+END_EXAMPLE

*** 广闻
- 收藏墨宝达到75条
#+BEGIN_EXAMPLE
广闻
#+END_EXAMPLE

*** 智渊
- 收藏墨宝达到110条
#+BEGIN_EXAMPLE
智渊
#+END_EXAMPLE

*** 有问有答
- 成功完成一次答题
#+BEGIN_EXAMPLE
成功完成一次答题
#+END_EXAMPLE

*** 博闻强识
- 成功完成五次答题
#+BEGIN_EXAMPLE
成功完成五次答题
#+END_EXAMPLE

*** 妙笔生花
- 成功完成三十五次答题
#+BEGIN_EXAMPLE
成功完成三十五次答题
#+END_EXAMPLE

*** 文采出众
- 成功完成一百次答题
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 智谋过人
- 成功完成三百次答题
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 替天行道
- 成功完成一轮缉捕
#+BEGIN_EXAMPLE
善恶有报
#+END_EXAMPLE

*** 天网恢恢
- 成功完成五轮缉捕
#+BEGIN_EXAMPLE
成功完成五轮缉捕
#+END_EXAMPLE

*** 善恶有报
- 成功完成二十轮缉捕
#+BEGIN_EXAMPLE
成功完成二十轮缉捕
#+END_EXAMPLE

*** 好运惊人
- 一次射利中获取金奖
#+BEGIN_EXAMPLE
好运惊人
#+END_EXAMPLE

*** 手气尚可
- 一次射利中获取银奖
#+BEGIN_EXAMPLE
手气尚可
#+END_EXAMPLE

*** 聊胜于无
- 一次射利中获取铜奖
#+BEGIN_EXAMPLE
聊胜于无
#+END_EXAMPLE

*** 小奖即安
- 累计中到铜奖十次
#+BEGIN_EXAMPLE
铜奖10次
#+END_EXAMPLE

*** 人品过人
- 累计中到银奖十次
#+BEGIN_EXAMPLE
银奖10次
#+END_EXAMPLE

*** 上天宠儿
- 累计中到金奖十次
#+BEGIN_EXAMPLE
金奖10次
#+END_EXAMPLE

*** 饮血
- 暗杀过NPC
#+BEGIN_EXAMPLE
暗杀NPC
#+END_EXAMPLE

*** 喋血
- 暗杀过10次NPC
#+BEGIN_EXAMPLE
暗杀NPC
#+END_EXAMPLE

*** 嗜血
- 暗杀过50次NPC
#+BEGIN_EXAMPLE
暗杀NPC
#+END_EXAMPLE

*** 渴血
- 暗杀过100次NPC
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 飞血
- 暗杀过500次NPC
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 挺身而出
- 用“抓捕”技能抓捕1个劫匪
#+BEGIN_EXAMPLE
击败劫匪
#+END_EXAMPLE

*** 光明磊落
- 用“抓捕”技能抓捕5个劫匪
#+BEGIN_EXAMPLE
击败劫匪
#+END_EXAMPLE

*** 嫉恶如仇
- 用“抓捕”技能抓捕10个劫匪
#+BEGIN_EXAMPLE
击败劫匪
#+END_EXAMPLE

*** 一马当先
- 用“抓捕”技能抓捕20个劫匪
#+BEGIN_EXAMPLE
击败劫匪
#+END_EXAMPLE

*** 主持正义
- 用“抓捕”技能抓捕50个劫匪
#+BEGIN_EXAMPLE
击败劫匪
#+END_EXAMPLE

*** 寻觅宝藏·二
- 成功完成十次挖宝
#+BEGIN_EXAMPLE
挖宝
#+END_EXAMPLE

*** 寻觅宝藏·三
- 成功完成三十次挖宝
#+BEGIN_EXAMPLE
挖宝
#+END_EXAMPLE

*** 寻觅宝藏·四
- 成功完成五十次挖宝
#+BEGIN_EXAMPLE
挖宝
#+END_EXAMPLE

*** 寻觅宝藏·五
- 成功完成两百次挖宝
#+BEGIN_EXAMPLE
挖宝
#+END_EXAMPLE

*** 暗夜死神·二
- 成功完成两百次暗杀
#+BEGIN_EXAMPLE
成功完成两百次暗杀
#+END_EXAMPLE

*** 暗夜死神·三
- 成功完成三百次暗杀
#+BEGIN_EXAMPLE
成功完成三百次暗杀
#+END_EXAMPLE

*** 暗夜死神·四
- 成功完成四百次暗杀
#+BEGIN_EXAMPLE
成功完成四百次暗杀
#+END_EXAMPLE

*** 暗夜死神·五
- 成功完成五百次暗杀
#+BEGIN_EXAMPLE
成功完成五百次暗杀
#+END_EXAMPLE

*** 敬业镖师
- 成功运送过七百五十次仁义镖或威武镖
#+BEGIN_EXAMPLE
成功运送过七百五十次仁义镖或威武镖
#+END_EXAMPLE

*** 祖传镖师
- 成功运送过一千次仁义镖或威武镖
#+BEGIN_EXAMPLE
成功运送过一千次仁义镖或威武镖
#+END_EXAMPLE

*** 劫道壮士
- 成功打劫十趟威武镖
#+BEGIN_EXAMPLE
成功打劫十趟威武镖
#+END_EXAMPLE

*** 惊天大盗
- 成功打劫二十趟威武镖
#+BEGIN_EXAMPLE
成功打劫二十趟威武镖
#+END_EXAMPLE

*** 胆大包天
- 成功打劫五十趟威武镖
#+BEGIN_EXAMPLE
成功打劫五十趟威武镖
#+END_EXAMPLE

*** 疯狂作案
- 成功打劫三趟天下镖
#+BEGIN_EXAMPLE
成功打劫三趟天下镖
#+END_EXAMPLE

*** 血案连连
- 成功打劫五趟天下镖
#+BEGIN_EXAMPLE
成功打劫五趟天下镖
#+END_EXAMPLE

*** 恶名远昭
- 成功打劫十趟天下镖
#+BEGIN_EXAMPLE
成功打劫十趟天下镖
#+END_EXAMPLE

*** 善恶有报·二
- 成功完成五十轮缉捕
#+BEGIN_EXAMPLE
成功完成五十轮缉捕
#+END_EXAMPLE

*** 善恶有报·三
- 成功完成八十轮缉捕
#+BEGIN_EXAMPLE
成功完成八十轮缉捕
#+END_EXAMPLE

*** 善恶有报·四
- 成功完成一百轮缉捕
#+BEGIN_EXAMPLE
成功完成一百轮缉捕
#+END_EXAMPLE

*** 善恶有报·五
- 成功完成一百五十轮缉捕
#+BEGIN_EXAMPLE
成功完成一百五十轮缉捕
#+END_EXAMPLE

*** 出手好彩
- 二十次射利中获得铜奖
#+BEGIN_EXAMPLE
二十次射利中获得铜奖
#+END_EXAMPLE

*** 华夏天赋
- 照料十次植物
#+BEGIN_EXAMPLE
照料十次植物
#+END_EXAMPLE

*** 华夏天赋·二
- 照料二十五次植物
#+BEGIN_EXAMPLE
照料二十五次植物
#+END_EXAMPLE

*** 华夏天赋·三
- 照料五十次植物
#+BEGIN_EXAMPLE
照料五十次植物
#+END_EXAMPLE

*** 丰收喜悦
- 采摘五次植物
#+BEGIN_EXAMPLE
采摘五次植物
#+END_EXAMPLE

*** 丰收喜悦·二
- 采摘十五次植物
#+BEGIN_EXAMPLE
采摘十五次植物
#+END_EXAMPLE

*** 丰收喜悦·三
- 采摘三十五次植物
#+BEGIN_EXAMPLE
采摘三十五次植物
#+END_EXAMPLE

** 赛马
*** 赛马大赛·连击壹
- 在赛马大赛中连风数达到20
#+BEGIN_EXAMPLE
连击数达到20
#+END_EXAMPLE

*** 赛马大赛·连击贰
- 在赛马大赛中连风数达到50
#+BEGIN_EXAMPLE
连击数达到50
#+END_EXAMPLE

*** 赛马大赛·连击叁
- 在赛马大赛中连风数达到80
#+BEGIN_EXAMPLE
连击数达到80
#+END_EXAMPLE

*** 赛马大赛·名次壹
- 在赛马大赛中获得前十名
#+BEGIN_EXAMPLE
赛马前十名
#+END_EXAMPLE

*** 赛马大赛·名次贰
- 在赛马大赛中获得前五名
#+BEGIN_EXAMPLE
赛马前五名
#+END_EXAMPLE

*** 赛马大赛·名次叁
- 在赛马大赛中获得第一名
#+BEGIN_EXAMPLE
赛马第一名
#+END_EXAMPLE

*** 赛马大赛·时间壹
- 8分钟内完成赛马大赛
#+BEGIN_EXAMPLE
8分钟内完成赛马
#+END_EXAMPLE

*** 赛马大赛·时间贰
- 6分钟内完成赛马大赛
#+BEGIN_EXAMPLE
6分钟内完成赛马
#+END_EXAMPLE

*** 赛马大赛·时间叁
- 4分30秒内完成赛马大赛
#+BEGIN_EXAMPLE
4分30秒内完成赛马
#+END_EXAMPLE

* 游历
** 地图
*** 九华之风
- 曾到达九华的如下地点
#+BEGIN_EXAMPLE
藏峰谷
燕来镇
云笈水榭
朝山路
甘蓬茅屋
华清寺
紫阳观
沅江下游
芳华谷
得意坊
离魂峡
神药峰
#+END_EXAMPLE

*** 九华云起
- 曾到达九华的如下地点
#+BEGIN_EXAMPLE
矿场
孔雀山庄
朝露峰
送君廊
锦燕林
鹧鸪岭
嘉荫镇
叠岭
江音畔
禁地
七星派
回音谷
#+END_EXAMPLE

*** 游历九华
- 完成“九华之风”和“九华云起”两个成就
#+BEGIN_EXAMPLE
九华之风
九华云起
#+END_EXAMPLE

*** 太白剑派
- 曾到达秦川的如下地点
#+BEGIN_EXAMPLE
太白山门
太白剑坪
泼墨岭
凌霄道
弑剑阁
沉剑池
古祭坛
论剑顶
乾坤阁
镜雪湖
银鳞河
#+END_EXAMPLE

*** 雪峦之颠
- 曾到达秦川的如下地点
#+BEGIN_EXAMPLE
太白云海东
蛟龙岭
太白云海西
药王谷
揽月台分舵
玉匣关
玉泉院
醉白池
浩然峰
草海腹地
鹦歌镇
笑月湖
#+END_EXAMPLE

*** 游历秦川
- 完成“太白剑派”和“雪峦之颠”两个成就
#+BEGIN_EXAMPLE
太白剑派
雪峦之颠
#+END_EXAMPLE

*** 神威策马
- 曾到达燕云的如下地点
#+BEGIN_EXAMPLE
神威堡
练兵场
天刀营
地鞘营
#+END_EXAMPLE

*** 大漠孤烟
- 曾到达燕云的如下地点
#+BEGIN_EXAMPLE
沙场
怪石林北
杨家谷
怪石林南
瀚海戈壁
齐暗谷
饮马绿洲
万里杀总舵
万马堂
绝尘镇
#+END_EXAMPLE

*** 长河落日
- 曾到达燕云的如下地点
#+BEGIN_EXAMPLE
神木谷
风鸣绿洲
策马坡
风飞谷
苍梧城
龙山分舵
#+END_EXAMPLE

*** 游历燕云
- 完成“神威策马”、“大漠孤烟”和“长河落日”三个成就
#+BEGIN_EXAMPLE
神威策马
大漠孤烟
长河落日
#+END_EXAMPLE

*** 西子风情
- 曾到达杭州的如下地点
#+BEGIN_EXAMPLE
凤凰集
盘龙岭
慈云林
宁王庄
钱塘门
东平郡王府
淬剑谷
天星阁
吴王陵
讲武堂
杭州城
钱塘江码头
#+END_EXAMPLE

*** 吴越旧韵
- 曾到达杭州的如下地点
#+BEGIN_EXAMPLE
百里荡分舵
一醉轩
落云滩
天绝禅院
问道台
雷峰塔
九曜山分舵
白龙飞瀑
红衣林
西湖
#+END_EXAMPLE

*** 游历杭州
- 完成“西子风情”和“吴越旧韵”
#+BEGIN_EXAMPLE
西子风情
吴越旧韵
#+END_EXAMPLE

*** 铸神山清
- 曾到达江南的如下地点
#+BEGIN_EXAMPLE
飞雪滩
枫桥镇
斜云小径
铸神谷
龙井茶园
松江分舵
龙首山麓
义字坡
天泉山庄
盘龙脊
狮子坡
樱风城
#+END_EXAMPLE

*** 春江如蓝
- 曾到达江南的如下地点
#+BEGIN_EXAMPLE
折之江
四明书院
百花坪
翠荫岭
鲲鹏渡
九回弯
长江分舵
天池分舵
连环坞总舵
霹雳堂旧址
长风林
鸣雷谷
#+END_EXAMPLE

*** 游历江南
- 完成“铸神山清”和“春江如蓝”
#+BEGIN_EXAMPLE
铸神山清
春江如蓝
#+END_EXAMPLE

*** 世外桃源
- 曾到达东越的如下地点
#+BEGIN_EXAMPLE
永清坊
香蝶林
云泥梯田
白鹭洲分舵
迎仙渡
乌金汊
老爷庙
桃源
东湖
闽越旧城
#+END_EXAMPLE

*** 浮天沧海
- 曾到达东越的如下地点
#+BEGIN_EXAMPLE
长乐滩
双龙岛分舵
万象门
野鹤湫
宁海城
青龙潭
七色海
杏林
万蝶坪
东汀渔村
#+END_EXAMPLE

*** 游历东越
- 完成“世外桃源”和“浮天沧海”
#+BEGIN_EXAMPLE
世外桃源
浮天沧海
#+END_EXAMPLE

*** 古驿斜阳
- 曾到达徐海的如下地点
#+BEGIN_EXAMPLE
古陶驿站
乱石滩
古陶官道
古陶镇
天龙古刹
红草滩
杜宅别苑
平阳驿站
#+END_EXAMPLE

*** 古原明月
- 曾到达徐海的如下地点
#+BEGIN_EXAMPLE
藏月湾
无影阁
苍雪岭
狂刀营
骅阳林
龙纹沟
白鹿野分舵
剑绝轩
徐海野
#+END_EXAMPLE

*** 古道远芳
- 曾到达徐海的如下地点
#+BEGIN_EXAMPLE
云眉道
望山道
玄刀阁
断剑阁
神武门
飞仙岭
固北岭分舵
绝情岭
#+END_EXAMPLE

*** 游历徐海
- 完成“古驿斜阳”和“古道月明”和“古道远芳”
#+BEGIN_EXAMPLE
古驿斜阳
古原明月
古道远芳
#+END_EXAMPLE

*** 君山洞庭
- 曾到达荆湖的如下地点
#+BEGIN_EXAMPLE
洞庭山
青螺山
聚贤围
览镜山
青草海
星云坪
朗吟馆
巴陵古镇
水陆洲
#+END_EXAMPLE

*** 故云梦泽
- 曾到达荆湖的如下地点
#+BEGIN_EXAMPLE
烟波尾
栖燕坪分舵
逐浪滩分舵
秋月林
仙泪山
儒溪镇
潇湘集
偃浪坡
玉镜湖
云雾泽
#+END_EXAMPLE

*** 游历荆湖
- 完成“君山洞庭”和“故云梦泽”
#+BEGIN_EXAMPLE
君山洞庭
故云梦泽
#+END_EXAMPLE

*** 巴国奇踪
- 曾到达巴蜀的如下地点
#+BEGIN_EXAMPLE
翠海
烟霞林
御风堂
星云岭
忘忧谷
万青竹海
碎星楼
千佛崖分舵
秦月谷
子午岭
双月湾
皇杉道
#+END_EXAMPLE

*** 蜀中竹趣
- 曾到达巴蜀的如下地点
#+BEGIN_EXAMPLE
凌云壁
朝天峡分舵
龙门山
卧龙谷
剑门关
云来镇
天峡谷
萦岩岭
风啸崖
#+END_EXAMPLE

*** 游历巴蜀
- 完成“巴国奇踪”和“蜀中竹趣”
#+BEGIN_EXAMPLE
巴国奇踪
蜀中竹趣
#+END_EXAMPLE

*** 花海流萤
- 曾到达云滇的如下地点
#+BEGIN_EXAMPLE
伏龙岭总舵
凤鸣谷总舵
罗苏关
饮玉镇
沧月岭
刺竹庄
迷音坡
神柱谷
赤云山
#+END_EXAMPLE

*** 万劫焚断
- 曾到达云滇的如下地点
#+BEGIN_EXAMPLE
天剑峰
万劫海
陨星湖
怒河洲
浣月坝
罗藏山
凤鸣道
卧云岭
星痕谷
#+END_EXAMPLE

*** 游历云滇
- 完成“花海流萤”和“万劫焚断”
#+BEGIN_EXAMPLE
花海流萤
万劫焚断
#+END_EXAMPLE

*** 青龙蟠日
- 曾到达襄州的如下地点
#+BEGIN_EXAMPLE
太极道场
真武殿
三清殿
律令阁
长生楼
万仞石梁
星罗棋布
涵星坊
玉华集
钟台山分舵
问虚道
归元谷
#+END_EXAMPLE

*** 三生万物
- 曾到达襄州的如下地点
#+BEGIN_EXAMPLE
砚首山分舵
松阳岭
鹿鸣谷
武陵峡
无涯峰
落羽谷
鹤峰
燕回岭
杜鹃岗
尘烟峰
天门峰
跃龙峡
#+END_EXAMPLE

*** 游历襄州
- 完成“青龙蟠日”和“三生万物”
#+BEGIN_EXAMPLE
青龙蟠日
三生万物
#+END_EXAMPLE

*** 帝都繁华
- 曾到达开封的如下地点
#+BEGIN_EXAMPLE
黄河
神乐台分舵
飞霞渡
朱仙镇
养心园
西水关
居士林
尧山
开封
问渠林
十八里湾
平逢道
#+END_EXAMPLE

*** 黄河九曲
- 曾到达开封的如下地点
#+BEGIN_EXAMPLE
黄华岭
百鸟林
稽首岭
琼华苑分舵
少室山
淘沙峪
洛河湾
护龙河
相国寺
#+END_EXAMPLE

*** 游历开封
- 完成“帝都繁华”和“黄河九曲”
#+BEGIN_EXAMPLE
帝都繁华
黄河九曲
#+END_EXAMPLE

*** 行在天涯
- 在路上，行者无涯。
#+BEGIN_EXAMPLE
游历九华
游历秦川
游历燕云
游历杭州
游历江南
游历东越
游历徐海
游历荆湖
游历巴蜀
游历云滇
游历襄州
游历开封
#+END_EXAMPLE

*** 山光
- 游历过众多山川
#+BEGIN_EXAMPLE
朝露峰
论剑顶
瀚海戈壁
盘龙岭
铸神谷
苍雪岭
#+END_EXAMPLE

*** 水色
- 游历过众多水系
#+BEGIN_EXAMPLE
江音畔
杭州码头
九回弯
九天阁
藏月湾
#+END_EXAMPLE

*** 极目眺·谷藏锋
- 极目远眺山水，九华之美收录眼底
#+BEGIN_EXAMPLE
凭栏
#+END_EXAMPLE

*** 重岩下·云飞瀑
- 岩下飞瀑湍流，如星云飞洒，美不胜收
#+BEGIN_EXAMPLE
飞瀑
#+END_EXAMPLE

*** 古寺中·佛首瞻
- 登高者望远，在此处可俯览整个九华
#+BEGIN_EXAMPLE
佛头
#+END_EXAMPLE

*** 孤山丘·断栈险
- 孤山中，断栈不知何时建、何时废、何时断
#+BEGIN_EXAMPLE
断栈
#+END_EXAMPLE

*** 石嶙峋·怪树畸
- 怪石嶙峋，枯树干藤死气沉沉，畸形怪树生于乱石上，诡怪异常
#+BEGIN_EXAMPLE
怪树
#+END_EXAMPLE

*** 千丈高·铁索悬
- 脚底即是千丈深渊，此身唯系脚下碗口铁链
#+BEGIN_EXAMPLE
铁索
#+END_EXAMPLE

*** 江音畔·水清波
- 江清波见底，水柔抚如梦
#+BEGIN_EXAMPLE
江畔
#+END_EXAMPLE

*** 水云寒·芦花艳
- 苍白芦花荡中，夹杂艳红花朵，尽得光彩
#+BEGIN_EXAMPLE
芦苇荡
#+END_EXAMPLE

*** 归途远·古藤桥
- 古藤缠绕吊桥，青苔幽怨铺满脚下
#+BEGIN_EXAMPLE
古藤桥
#+END_EXAMPLE

*** 纵横深·孔雀顶
- 孔雀山庄之顶，宏伟壮阔山庄都在睥睨间
#+BEGIN_EXAMPLE
孔雀顶
#+END_EXAMPLE

*** 我为巅·鹧鸪山
- 鹧鸪岭峰上，紫色小花默默绽放，燕来镇就在远处
#+BEGIN_EXAMPLE
鹧鸪岭
#+END_EXAMPLE

*** 江沁月·波碎影
- 在此处可将江青月影尽收眼底
#+BEGIN_EXAMPLE
江沁月·波碎影
#+END_EXAMPLE

*** 总舵遥·危机伏
- 若能避过重重守卫攀上此处，即可远眺对面总舵
#+BEGIN_EXAMPLE
总舵遥·危机伏
#+END_EXAMPLE

*** 湍流疾·奇石凌
- 在狭窄河道内水流飞溅，嶙峋奇石突于河道
#+BEGIN_EXAMPLE
湍流疾·奇石凌
#+END_EXAMPLE

*** 空谷幽·铸神远
- 跃上铸神谷房屋的顶端，空山幽谷皆在眼中
#+BEGIN_EXAMPLE
空谷幽·铸神远
#+END_EXAMPLE

*** 双塔守·水路阔
- 总舵地处江南，除了普通的山门外，水路入口也是一大特色
#+BEGIN_EXAMPLE
双塔守·水路阔
#+END_EXAMPLE

*** 观千山·望万水
- 攀上总舵的高处，平时可赏四面景色，战时可防四周之敌
#+BEGIN_EXAMPLE
观千山·望万水
#+END_EXAMPLE

*** 德甚嘉·行甚懿
- 嘉德懿行，德行美好
#+BEGIN_EXAMPLE
德甚嘉·行甚懿
#+END_EXAMPLE

*** 桃源深·古道观
- 跃上道观顶，重楼飞檐果真灵动
#+BEGIN_EXAMPLE
桃源深·古道观
#+END_EXAMPLE

*** 青苔生·东湖月
- 湖边青石上，静赏湖水美
#+BEGIN_EXAMPLE
青苔生·东湖月
#+END_EXAMPLE

*** 旧城寂·飞瀑疾
- 闽越古城中，一道飞瀑从极高之处落下飞溅
#+BEGIN_EXAMPLE
旧城寂·飞瀑疾
#+END_EXAMPLE

*** 九天顶·望海潮
- 九天阁气度不凡，九天阁之顶视野更是开阔
#+BEGIN_EXAMPLE
九天顶·望海潮
#+END_EXAMPLE

*** 观沧海·浮白沙
- 海边礁石极目远眺，大海蔚蓝壮阔，无边无际
#+BEGIN_EXAMPLE
观沧海·浮白沙
#+END_EXAMPLE

*** 哨岗立·迎白帆
- 岸边泊有大船一艘，跃上岗哨则可以将船上动静悉数收录
#+BEGIN_EXAMPLE
哨岗立·迎白帆
#+END_EXAMPLE

*** 岩上枫·金掩赤
- 悬崖上生出数棵枫树，色极艳丽，岩石陡峭，仅容一人侧立
#+BEGIN_EXAMPLE
岩上枫·金掩赤
#+END_EXAMPLE

*** 登高塔·俯敌营
- 跃上白鹭洲制高处，倭人据点一览无余
#+BEGIN_EXAMPLE
登高塔·俯敌营
#+END_EXAMPLE

*** 海风盛·椰树香
- 海天浩渺，玉屑银末，椰树高耸
#+BEGIN_EXAMPLE
海风盛·椰树香
#+END_EXAMPLE

*** 风沙起·武威扬
- 在此可俯览神威堡
#+BEGIN_EXAMPLE
风沙起·武威扬
#+END_EXAMPLE

*** 山外云·石林孤
- 绿洲饮马诉衷情，残柱矗穿云
#+BEGIN_EXAMPLE
山外云·石林孤
#+END_EXAMPLE

*** 古堡危·砾沙碛
- 千里马场旁古堡，极目远望一片苍黄
#+BEGIN_EXAMPLE
古堡危·砾沙碛
#+END_EXAMPLE

*** 忘来路·苍梧城
- 苍梧城残垣断壁之顶，一片寂静荒凉
#+BEGIN_EXAMPLE
忘来路·苍梧城
#+END_EXAMPLE

*** 阵破乐·神威哨
- 神威堡附近岗哨，可防来犯之敌
#+BEGIN_EXAMPLE
阵破乐·神威哨
#+END_EXAMPLE

*** 乱石滩·芦苇荡
- 冰原雪水，清澈透底，寒冷彻骨
#+BEGIN_EXAMPLE
乱石滩·芦苇荡
#+END_EXAMPLE

*** 山门耸·宝刹丽
- 天龙古刹山门高耸，宝刹庄严
#+BEGIN_EXAMPLE
山门耸·宝刹丽
#+END_EXAMPLE

*** 古陶镇·立高台
- 古陶镇的入口处，来往行人客商都需经由此路
#+BEGIN_EXAMPLE
古陶镇·立高台
#+END_EXAMPLE

*** 时光·剪影
- 桥上离人泪，桥下水自流
#+BEGIN_EXAMPLE
时光·剪影
#+END_EXAMPLE

*** 雪山麓·红草滩
- 一地三季：红草滩、金枫树、积雪山
#+BEGIN_EXAMPLE
雪山麓·红草滩
#+END_EXAMPLE

*** 无影阁·一线天
- 无影阁顶，双檐对供，恰留一线天
#+BEGIN_EXAMPLE
无影阁·一线天
#+END_EXAMPLE

*** 峭壁垂·空中阁
- 神武门最高处，雄伟建筑却是峭壁上凭空而造，精妙异常
#+BEGIN_EXAMPLE
峭壁垂·空中阁
#+END_EXAMPLE

*** 兽獠牙·辟水流
- 雕刻着凶兽图样的厚重门顶端，水流急转而下
#+BEGIN_EXAMPLE
兽獠牙·辟水流
#+END_EXAMPLE

*** 沉剑试·剑坪顶
- 剑坪上发生的一切都尽在眼中！
#+BEGIN_EXAMPLE
沉剑试·剑坪顶
#+END_EXAMPLE

*** 巍峨矗·祭坛顶
- 古祭坛之顶，也是方圆最高的山脉之一
#+BEGIN_EXAMPLE
巍峨矗·祭坛顶
#+END_EXAMPLE

*** 冰晶澈·沉剑池
- 冰原雪化水注入沉剑池中，晶莹透彻
#+BEGIN_EXAMPLE
冰晶澈·沉剑池
#+END_EXAMPLE

*** 逍遥游·剑碑顶
- 除了令狐聪，我也可以上来
#+BEGIN_EXAMPLE
逍遥游·剑碑顶
#+END_EXAMPLE

*** 观云海·蛟龙岭
- 攀蛟龙岭，观太白云海西
#+BEGIN_EXAMPLE
观云海·蛟龙岭
#+END_EXAMPLE

*** 往来繁·巍山门
- 驿站人来人往，山门高耸
#+BEGIN_EXAMPLE
往来繁·巍山门
#+END_EXAMPLE

*** 望杭州·钱塘门
- 钱塘门高耸，如若攀上则可以远望大半个杭州
#+BEGIN_EXAMPLE
望杭州·钱塘门
#+END_EXAMPLE

*** 眺杭州·永兴寺
- 永兴寺凸出的高台上，向下可以看到杭州城
#+BEGIN_EXAMPLE
眺杭州·永兴寺
#+END_EXAMPLE

*** 淬剑谷·剑之顶
- 淬剑谷之巨剑顶，剑柄上仅容一人
#+BEGIN_EXAMPLE
淬剑谷·剑之顶
#+END_EXAMPLE

*** 行龙荡·车水流
- 水车机杼，潺潺水流
#+BEGIN_EXAMPLE
行龙荡·车水流
#+END_EXAMPLE

*** 悬空阁·美雕梁
- 新月山庄最高处的建筑，回廊悬于空中，雕梁画栋精致异常
#+BEGIN_EXAMPLE
悬空阁·美雕梁
#+END_EXAMPLE

*** 晨钟肃·暮鼓鸣
- 庄严肃穆的天绝禅院，华光四射
#+BEGIN_EXAMPLE
晨钟肃·暮鼓鸣
#+END_EXAMPLE

*** 蔷薇之烬
- 不见蔷薇，唯余孤冢。
#+BEGIN_EXAMPLE
发现燕南飞之墓
完成任务：孤燕难飞
#+END_EXAMPLE

*** 嵩高维岳
- 使用龙极图·一
#+BEGIN_EXAMPLE
使用龙极图·一
#+END_EXAMPLE

*** 钟灵应乐
- 使用龙极图·二（地脉）、龙极图·二（玄脉）、龙极图·二（黄脉）
#+BEGIN_EXAMPLE
使用龙极图·二（地脉）
龙极图·二（玄脉）
龙极图·二（黄脉）
#+END_EXAMPLE

*** 绥绥白狐
- 使用龙极图·三（宇脉）、龙极图·三（宙脉）
#+BEGIN_EXAMPLE
使用龙极图·三（宇脉）
龙极图·三（宙脉）
#+END_EXAMPLE

*** 颍水知源
- 使用龙极图·四（玄脉）、龙极图·四（黄脉）
#+BEGIN_EXAMPLE
使用龙极图·四（玄脉）
龙极图·四（黄脉）
#+END_EXAMPLE

*** 太室龙极
- 达成成就嵩高维岳、钟灵应乐、绥绥白狐、颍水知源
#+BEGIN_EXAMPLE
嵩高维岳
钟灵应乐
绥绥白狐
颍水知源
#+END_EXAMPLE

*** 灵妃地脉
- 使用龙极图·二（地脉）
#+BEGIN_EXAMPLE
龙极图·二（地脉）
#+END_EXAMPLE

*** 灵妃玄脉
- 使用龙极图·二（玄脉）
#+BEGIN_EXAMPLE
龙极图·二（玄脉）
#+END_EXAMPLE

*** 灵妃黄脉
- 使用龙极图·二（黄脉）
#+BEGIN_EXAMPLE
龙极图·二（黄脉）
#+END_EXAMPLE

*** 涂山宇脉
- 使用龙极图·三（宇脉）
#+BEGIN_EXAMPLE
龙极图·三（宇脉）
#+END_EXAMPLE

*** 涂山宙脉
- 使用龙极图·三（宙脉）
#+BEGIN_EXAMPLE
龙极图·三（宙脉）
#+END_EXAMPLE

*** 颍水玄脉
- 使用龙极图·四（玄脉）
#+BEGIN_EXAMPLE
龙极图·四（玄脉）
#+END_EXAMPLE

*** 颍水黄脉
- 使用龙极图·四（黄脉）
#+BEGIN_EXAMPLE
龙极图·四（黄脉）
#+END_EXAMPLE

** 四季时辰
*** 烟雨濛
- 经历一次靡靡小雨
#+BEGIN_EXAMPLE
小雨
#+END_EXAMPLE

*** 风雨疾
- 经历一次滂沱大雨
#+BEGIN_EXAMPLE
大雨
#+END_EXAMPLE

*** 雪飘零
- 经历一次小雪
#+BEGIN_EXAMPLE
小雪
#+END_EXAMPLE

*** 雪纷飞
- 遭遇一场鹅毛大雪
#+BEGIN_EXAMPLE
大雪
#+END_EXAMPLE

*** 走龙蛇
- 遭遇一场小型沙尘暴
#+BEGIN_EXAMPLE
小沙尘暴
#+END_EXAMPLE

*** 蔽日月
- 遭遇一场大型沙尘暴
#+BEGIN_EXAMPLE
大沙尘暴
#+END_EXAMPLE

*** 落汤鸡
- 遭遇10次大雨
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 从头淋到脚
- 遭遇100次大雨
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 进砂
- 遭遇10次小型沙尘暴
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 迷眼
- 遭遇100次大型沙尘暴
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 雪漫天
- 遭遇10场大雪
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 雪弥天
- 遭遇100场大雪
#+BEGIN_EXAMPLE
#+END_EXAMPLE

*** 映清晨
- 旭日东升，空气清新，一日之计在于晨
#+BEGIN_EXAMPLE
日出
#+END_EXAMPLE

*** 渐黄昏
- 酉时已至，日渐西沉，黄昏来临
#+BEGIN_EXAMPLE
日落
#+END_EXAMPLE

*** 夜阑珊
- 暮色渐至，居民归家，阑珊夜景中何处是自己的那盏明灯？
#+BEGIN_EXAMPLE
夜里
#+END_EXAMPLE

*** 雪月流光
- 在秦川经历一场漫天大雪
#+BEGIN_EXAMPLE
秦川
大雪
#+END_EXAMPLE

*** 霜天霁月
- 在秦川经历一场小雪
#+BEGIN_EXAMPLE
秦川
小雪
#+END_EXAMPLE

*** 燕云扬沙
- 在燕云经历一场小型沙尘暴
#+BEGIN_EXAMPLE
燕云
小沙尘暴
#+END_EXAMPLE

*** 日月无光
- 在燕云经历一场大型沙尘暴
#+BEGIN_EXAMPLE
燕云
大沙尘暴
#+END_EXAMPLE

*** 秦川晚风
- 在秦川度过一个夜晚
#+BEGIN_EXAMPLE
秦川
夜里
#+END_EXAMPLE

*** 燕云烘月
- 在燕云度过一个夜晚
#+BEGIN_EXAMPLE
燕云
夜里
#+END_EXAMPLE

*** 烟雨江南
- 在江南龙首山天泉山庄经历过一次小雨
#+BEGIN_EXAMPLE
天泉山庄
小雨
#+END_EXAMPLE

*** 望云晚霞
- 在江南折之江经历过一次日落
#+BEGIN_EXAMPLE
折之江
日落
#+END_EXAMPLE

*** 江花胜火
- 在江南塔顶观赏过一次日出
#+BEGIN_EXAMPLE
江南云碧塔
日出
#+END_EXAMPLE

*** 仙山日落
- 在东越海滨经历过一次黄昏
#+BEGIN_EXAMPLE
东越海滨
日落
#+END_EXAMPLE

*** 霞映清永
- 在东越清永坊观赏过一次日出
#+BEGIN_EXAMPLE
永清坊
日出
#+END_EXAMPLE

*** 杭州夜景
- 在杭州城内经历夜晚
#+BEGIN_EXAMPLE
杭州城
夜里
#+END_EXAMPLE

*** 重檐送晓
- 在九华水榭观赏一次日出
#+BEGIN_EXAMPLE
水榭
日出
#+END_EXAMPLE

*** 故道斜阳
- 在徐海骅阳林观赏一次日落
#+BEGIN_EXAMPLE
徐海骅阳林
日落
#+END_EXAMPLE

*** 日出苍雪
- 在徐海苍雪岭观赏一次日出
#+BEGIN_EXAMPLE
徐海苍雪岭
日出
#+END_EXAMPLE

*** 日落藏月
- 在徐海藏月湾经历一次黄昏
#+BEGIN_EXAMPLE
徐海藏月湾
日落
#+END_EXAMPLE

*** 生生不息
- 欣赏过以下全部美景
#+BEGIN_EXAMPLE
雪月流光
霜天霁月
燕云扬沙
日月无光
烟雨江南
重檐送晓
故道斜阳
#+END_EXAMPLE

** 钓鱼
*** 羡鱼
- 完成一次钓鱼大赛
#+BEGIN_EXAMPLE
完成一次钓鱼比赛
#+END_EXAMPLE

*** 闲趣
- 完成五次钓鱼大赛
#+BEGIN_EXAMPLE
完成五次钓鱼比赛
#+END_EXAMPLE

*** 渔趣
- 完成十五次钓鱼大赛
#+BEGIN_EXAMPLE
完成十五次钓鱼比赛
#+END_EXAMPLE

*** 名列前茅
- 钓鱼大赛前10名
#+BEGIN_EXAMPLE
获得比赛前十
#+END_EXAMPLE

*** 聚精会神
- 钓鱼大赛前5名
#+BEGIN_EXAMPLE
获得比赛前五
#+END_EXAMPLE

*** 满载而归
- 钓鱼大赛第3名
#+BEGIN_EXAMPLE
获得比赛第三名
#+END_EXAMPLE

*** 天涯渔夫
- 钓鱼大赛第1名
#+BEGIN_EXAMPLE
获得比赛第一名
#+END_EXAMPLE

* 装备
** 装备
*** 初识良品
- 获得任意部位的良品（绿色）装备
#+BEGIN_EXAMPLE
绿装
#+END_EXAMPLE

*** 初识上品
- 获得任意部位的上品（蓝色）装备
#+BEGIN_EXAMPLE
蓝装
#+END_EXAMPLE

*** 初识精品·主武器
- 穿着精品（紫色）主武器
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·辅武器
- 穿着精品（紫色）辅武器
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·暗器
- 穿着精品（紫色）暗器
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·头饰
- 穿着精品（紫色）头饰
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·上衣
- 穿着精品（紫色）上衣
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·腰饰
- 穿着精品（紫色）腰饰
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·手腕
- 穿着精品（紫色）手腕
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·内衬
- 穿着精品（紫色）内衬
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·下装
- 穿着精品（紫色）下装
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·项链
- 穿着精品（紫色）项链
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·戒指壹
- 穿着精品（紫色）手指戒指·壹
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·戒指贰
- 穿着精品（紫色）手指戒指·贰
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 初识精品·手镯
- 穿着精品（紫色）手镯
#+BEGIN_EXAMPLE
紫装
#+END_EXAMPLE

*** 全身良品
- 全身穿着良品（绿色）装备
#+BEGIN_EXAMPLE
主武器
辅武器
头饰
上衣
腰饰
手腕
内衬
下装
项链
戒指·壹
戒指·贰
手镯
#+END_EXAMPLE

*** 全身上品
- 全身穿着上品（蓝色）装备
#+BEGIN_EXAMPLE
主武器
辅武器
头饰
上衣
腰饰
手腕
内衬
下装
项链
戒指·壹
戒指·贰
手镯
#+END_EXAMPLE

*** 全身精品
- 全身穿着精品（紫色）装备
#+BEGIN_EXAMPLE
主武器
辅武器
头饰
上衣
腰饰
手腕
内衬
下装
项链
戒指·壹
戒指·贰
手镯
#+END_EXAMPLE

*** 神行
- 装备优秀的神驹作为坐骑
#+BEGIN_EXAMPLE
乌云团
白公子
#+END_EXAMPLE

*** 不凡神品·主武器
- 穿着神品（金色）主武器
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·辅武器
- 穿着神品（金色）辅武器
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·暗器
- 穿着神品（金色）暗器
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·头饰
- 穿着神品（金色）头饰
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·上衣
- 穿着神品（金色）上衣
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·腰饰
- 穿着神品（金色）腰饰
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·手腕
- 穿着神品（金色）手腕
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·内衬
- 穿着神品（金色）内衬
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·下装
- 穿着神品（金色）下装
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·项链
- 穿着神品（金色）项链
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·戒指壹
- 穿着神品（金色）手指戒指·壹
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·戒指贰
- 穿着神品（金色）手指戒指·贰
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 不凡神品·手镯
- 穿着神品（金色）手镯
#+BEGIN_EXAMPLE
金装
#+END_EXAMPLE

*** 全身神品
- 全身装备金色装备
#+BEGIN_EXAMPLE
不凡神品·辅武器
不凡神品·暗器
不凡神品·头饰
不凡神品·上衣
不凡神品·腰饰
不凡神品·手腕
不凡神品·内衬
不凡神品·下装
不凡神品·项链
不凡神品·戒指壹
不凡神品·手镯
#+END_EXAMPLE

*** 穿戴一级PVE·上衣
- 穿戴一级PVE上衣（100品）
#+BEGIN_EXAMPLE
天火·萧野争锋袍
金刚·萧野争锋袍
泽兰·萧野争锋袍
#+END_EXAMPLE

*** 穿戴一级PVE·下装
- 穿戴一级PVE下装（100品）
#+BEGIN_EXAMPLE
天火·萧野争锋履
金刚·萧野争锋履
泽兰·萧野争锋履
#+END_EXAMPLE

*** 穿戴一级PVE·头饰
- 穿戴一级PVE头饰（100品）
#+BEGIN_EXAMPLE
天火·萧野争锋冠
金刚·萧野争锋冠
泽兰·萧野争锋冠
#+END_EXAMPLE

*** 穿戴一级PVE·内衬
- 穿戴一级PVE内衬（100品）
#+BEGIN_EXAMPLE
采苹
#+END_EXAMPLE

*** 穿戴一级PVE·衣带
- 穿戴一级PVE衣带（100品）
#+BEGIN_EXAMPLE
天火·萧野争锋带
金刚·萧野争锋带
泽兰·萧野争锋带
#+END_EXAMPLE

*** 穿戴一级PVE·护腕
- 穿戴一级PVE护腕（100品）
#+BEGIN_EXAMPLE
天火·萧野争锋腕
金刚·萧野争锋腕
泽兰·萧野争锋腕
#+END_EXAMPLE

*** 穿戴一级PVE·手镯
- 穿戴一级PVE手镯（100品）
#+BEGIN_EXAMPLE
天火·裂琴镯
金刚·裂琴镯
泽兰·裂琴镯
#+END_EXAMPLE

*** 穿戴一级PVE·戒指
- 穿戴一级PVE戒指（100品）
#+BEGIN_EXAMPLE
天火·裂琴戒
金刚·裂琴戒
泽兰·裂琴戒
#+END_EXAMPLE

*** 穿戴一级PVE·项链
- 穿戴一级PVE项链（100品）
#+BEGIN_EXAMPLE
天火·裂琴链
金刚·裂琴链
泽兰·裂琴链
#+END_EXAMPLE

*** 穿戴一级PVE·辅武器
- 穿戴一级PVE辅武器（100品）
#+BEGIN_EXAMPLE
含悲之鞘
侍月
醉洛阳
惊蛰
交征之匣
入云松
天恨
司长生
#+END_EXAMPLE

*** 穿戴一级PVE·暗器
- 穿戴一级PVE暗器（100品）
#+BEGIN_EXAMPLE
裂琴弦
#+END_EXAMPLE

*** 穿戴一级PVE·主武器
- 穿戴一级PVE主武器（100品）
#+BEGIN_EXAMPLE
含悲
投龙
追欢
鹣鲽
交征
慕芳龄
心魔
听雨
#+END_EXAMPLE

*** 穿戴二级PVE·上衣
- 穿戴二级PVE上衣（105品）
#+BEGIN_EXAMPLE
天火·刀锋之华袍
金刚·刀锋之华袍
泽兰·刀锋之华袍
#+END_EXAMPLE

*** 穿戴二级PVE·下装
- 穿戴二级PVE下装（105品）
#+BEGIN_EXAMPLE
天火·刀锋之华履
金刚·刀锋之华履
泽兰·刀锋之华履
#+END_EXAMPLE

*** 穿戴二级PVE·头饰
- 穿戴二级PVE头饰（105品）
#+BEGIN_EXAMPLE
天火·刀锋之华冠
金刚·刀锋之华冠
泽兰·刀锋之华冠
#+END_EXAMPLE

*** 穿戴二级PVE·内衬
- 穿戴二级PVE内衬（105品）
#+BEGIN_EXAMPLE
罂宁
#+END_EXAMPLE

*** 穿戴二级PVE·衣带
- 穿戴二级PVE衣带（105品）
#+BEGIN_EXAMPLE
天火·刀锋之华带
金刚·刀锋之华带
泽兰·刀锋之华带
#+END_EXAMPLE

*** 穿戴二级PVE·护腕
- 穿戴二级PVE护腕（105品）
#+BEGIN_EXAMPLE
天火·刀锋之华腕
金刚·刀锋之华腕
泽兰·刀锋之华腕
#+END_EXAMPLE

*** 穿戴二级PVE·手镯
- 穿戴二级PVE手镯（105品）
#+BEGIN_EXAMPLE
天火·诛心镯
金刚·诛心镯
泽兰·诛心镯
#+END_EXAMPLE

*** 穿戴二级PVE·戒指
- 穿戴二级PVE戒指（105品）
#+BEGIN_EXAMPLE
天火·诛心戒
金刚·诛心戒
泽兰·诛心戒
#+END_EXAMPLE

*** 穿戴二级PVE·项链
- 穿戴二级PVE项链（105品）
#+BEGIN_EXAMPLE
天火·诛心链
金刚·诛心链
泽兰·诛心链
#+END_EXAMPLE

*** 穿戴二级PVE·辅武器
- 穿戴二级PVE辅武器（105品）
#+BEGIN_EXAMPLE
竞秀之鞘
之莹
问江山
画蓉
笑吾之匣
占梅芳
圣阳
落花风
#+END_EXAMPLE

*** 穿戴二级PVE·暗器
- 穿戴二级PVE暗器（105品）
#+BEGIN_EXAMPLE
诛心雪
#+END_EXAMPLE

*** 穿戴二级PVE·主武器
- 穿戴二级PVE主武器（105品）
#+BEGIN_EXAMPLE
竞秀
寒魄
风岭
小玉
笑吾
暗香浮
祭日
归尘
#+END_EXAMPLE

*** 穿戴三级PVE·上衣
- 穿戴三级PVE上衣（110品）
#+BEGIN_EXAMPLE
天火·战舞霜城袍
金刚·战舞霜城袍
泽兰·战舞霜城袍
#+END_EXAMPLE

*** 穿戴三级PVE·下装
- 穿戴三级PVE下装（110品）
#+BEGIN_EXAMPLE
天火·战舞霜城履
金刚·战舞霜城履
泽兰·战舞霜城履
#+END_EXAMPLE

*** 穿戴三级PVE·头饰
- 穿戴三级PVE头饰（110品）
#+BEGIN_EXAMPLE
天火·战舞霜城冠
金刚·战舞霜城冠
泽兰·战舞霜城冠
#+END_EXAMPLE

*** 穿戴三级PVE·内衬
- 穿戴三级PVE内衬（110品）
#+BEGIN_EXAMPLE
疏玉
#+END_EXAMPLE

*** 穿戴三级PVE·衣带
- 穿戴三级PVE衣带（110品）
#+BEGIN_EXAMPLE
天火·战舞霜城带
金刚·战舞霜城带
泽兰·战舞霜城带
#+END_EXAMPLE

*** 穿戴三级PVE·护腕
- 穿戴三级PVE护腕（110品）
#+BEGIN_EXAMPLE
天火·战舞霜城腕
金刚·战舞霜城腕
泽兰·战舞霜城腕
#+END_EXAMPLE

*** 穿戴三级PVE·手镯
- 穿戴三级PVE手镯（110品）
#+BEGIN_EXAMPLE
天火·天峰镯
金刚·天峰镯
泽兰·天峰镯
#+END_EXAMPLE

*** 穿戴三级PVE·戒指
- 穿戴三级PVE戒指（110品）
#+BEGIN_EXAMPLE
天火·天峰戒
金刚·天峰戒
泽兰·天峰戒
#+END_EXAMPLE

*** 穿戴三级PVE·项链
- 穿戴三级PVE项链（110品）
#+BEGIN_EXAMPLE
天火·天峰链
金刚·天峰链
泽兰·天峰链
#+END_EXAMPLE

*** 穿戴三级PVE·辅武器
- 穿戴三级PVE辅武器（110品）
#+BEGIN_EXAMPLE
碎雪之鞘
五蕴
慕仙衣
百草
弱水之匣
芳魂引
幻生
鸣悲辛
#+END_EXAMPLE

*** 穿戴三级PVE·暗器
- 穿戴三级PVE暗器（110品）
#+BEGIN_EXAMPLE
天峰石
#+END_EXAMPLE

*** 穿戴三级PVE·主武器
- 穿戴三级PVE主武器（110品）
#+BEGIN_EXAMPLE
碎雪
破戒
控鹤
药童
弱水
诉衷情
情劫
夜楼
#+END_EXAMPLE

*** 穿戴四级PVE·上衣
- 穿戴四级PVE上衣（115品）
#+BEGIN_EXAMPLE
冰绡岚影袍
铁血荒漠袍
酣畅名门袍
夜海情心袍
弈墨苍冥袍
雪芷丹华袍
日月通明袍
朱羽刀皇袍
#+END_EXAMPLE

*** 穿戴四级PVE·下装
- 穿戴四级PVE下装（115品）
#+BEGIN_EXAMPLE
冰绡岚影履
铁血荒漠履
酣畅名门履
夜海情心履
弈墨苍冥履
雪芷丹华履
日月通明履
朱羽刀皇履
#+END_EXAMPLE

*** 穿戴四级PVE·头饰
- 穿戴四级PVE头饰（115品）
#+BEGIN_EXAMPLE
冰绡岚影冠
铁血荒漠冠
酣畅名门冠
夜海情心冠
弈墨苍冥冠
雪芷丹华冠
日月通明冠
朱羽刀皇冠
#+END_EXAMPLE

*** 穿戴四级PVE·内衬
- 穿戴四级PVE内衬（115品）
#+BEGIN_EXAMPLE
明纤
#+END_EXAMPLE

*** 穿戴四级PVE·衣带
- 穿戴四级PVE衣带（115品）
#+BEGIN_EXAMPLE
冰绡岚影带
铁血荒漠带
酣畅名门带
夜海情心带
弈墨苍冥带
雪芷丹华带
日月通明带
朱羽刀皇带
#+END_EXAMPLE

*** 穿戴四级PVE·护腕
- 穿戴四级PVE护腕（115品）
#+BEGIN_EXAMPLE
冰绡岚影腕
铁血荒漠腕
酣畅名门腕
夜海情心腕
弈墨苍冥腕
雪芷丹华腕
日月通明腕
朱羽刀皇腕
#+END_EXAMPLE

*** 穿戴四级PVE·手镯
- 穿戴四级PVE手镯（115品）
#+BEGIN_EXAMPLE
天火·四无镯
金刚·四无镯
泽兰·四无镯
#+END_EXAMPLE

*** 穿戴四级PVE·戒指
- 穿戴四级PVE戒指（115品）
#+BEGIN_EXAMPLE
天火·四无戒
金刚·四无戒
泽兰·四无戒
#+END_EXAMPLE

*** 穿戴四级PVE·项链
- 穿戴四级PVE项链（115品）
#+BEGIN_EXAMPLE
天火·四无链
金刚·四无链
泽兰·四无链
#+END_EXAMPLE

*** 穿戴四级PVE·辅武器
- 穿戴四级PVE辅武器（115品）
#+BEGIN_EXAMPLE
弈山之鞘
天元
吟世局
七弦
希音之匣
金缕曲
迷局
呼天晓
#+END_EXAMPLE

*** 穿戴四级PVE·暗器
- 穿戴四级PVE暗器（115品）
#+BEGIN_EXAMPLE
四无刀
#+END_EXAMPLE

*** 穿戴四级PVE·主武器
- 穿戴四级PVE主武器（115品）
#+BEGIN_EXAMPLE
弈山
纵横
落星
琴臣
希音
声声慢
残念
击水
#+END_EXAMPLE

*** 穿戴五级PVE·上衣
- 穿戴五级PVE上衣（120品）
#+BEGIN_EXAMPLE
喋血·雪魄尘光袍
喋血·瀚海驰骋袍
喋血·独酌天下袍
喋血·风露霜晨袍
喋血·神机韬略袍
喋血·臻姿凤仪袍
喋血·枫香泪雨袍
喋血·永夜杀神袍
#+END_EXAMPLE

*** 穿戴五级PVE·下装
- 穿戴五级PVE下装（120品）
#+BEGIN_EXAMPLE
喋血·雪魄尘光履
喋血·瀚海驰骋履
喋血·独酌天下履
喋血·风露霜晨履
喋血·神机韬略履
喋血·臻姿凤仪履
喋血·枫香泪雨履
喋血·永夜杀神履
#+END_EXAMPLE

*** 穿戴五级PVE·头饰
- 穿戴五级PVE头饰（120品）
#+BEGIN_EXAMPLE
喋血·雪魄尘光冠
喋血·瀚海驰骋冠
喋血·独酌天下冠
喋血·风露霜晨冠
喋血·神机韬略冠
喋血·臻姿凤仪冠
喋血·枫香泪雨冠
喋血·永夜杀神冠
#+END_EXAMPLE

*** 穿戴五级PVE·内衬
- 穿戴五级PVE内衬（120品）
#+BEGIN_EXAMPLE
喋血·沾轻衣
#+END_EXAMPLE

*** 穿戴五级PVE·衣带
- 穿戴五级PVE衣带（120品）
#+BEGIN_EXAMPLE
喋血·雪魄尘光带
喋血·瀚海驰骋带
喋血·独酌天下带
喋血·风露霜晨带
喋血·神机韬略带
喋血·臻姿凤仪带
喋血·枫香泪雨带
喋血·永夜杀神带
#+END_EXAMPLE

*** 穿戴五级PVE·护腕
- 穿戴五级PVE护腕（120品）
#+BEGIN_EXAMPLE
喋血·雪魄尘光腕
喋血·瀚海驰骋腕
喋血·独酌天下腕
喋血·风露霜晨腕
喋血·神机韬略腕
喋血·臻姿凤仪腕
喋血·枫香泪雨腕
喋血·永夜杀神腕
#+END_EXAMPLE

*** 穿戴五级PVE·手镯
- 穿戴五级PVE手镯（120品）
#+BEGIN_EXAMPLE
天火·寻花镯
金刚·寻花镯
泽兰·寻花镯
#+END_EXAMPLE

*** 穿戴五级PVE·戒指
- 穿戴五级PVE戒指（120品）
#+BEGIN_EXAMPLE
天火·寻花戒
金刚·寻花戒
泽兰·寻花戒
#+END_EXAMPLE

*** 穿戴五级PVE·项链
- 穿戴五级PVE项链（120品）
#+BEGIN_EXAMPLE
天火·寻花链
金刚·寻花链
泽兰·寻花链
#+END_EXAMPLE

*** 穿戴五级PVE·辅武器
- 穿戴五级PVE辅武器（120品）
#+BEGIN_EXAMPLE
喋血·赤霄之鞘
喋血·碎穹
喋血·饮龙潭
喋血·犹记
喋血·灵宝之匣
喋血·莫思归
喋血·狂澜
喋血·风归云
#+END_EXAMPLE

*** 穿戴五级PVE·暗器
- 穿戴五级PVE暗器（120品）
#+BEGIN_EXAMPLE
天火·寻花间
金刚·寻花间
泽兰·寻花间
#+END_EXAMPLE

*** 穿戴五级PVE·主武器
- 穿戴五级PVE主武器（120品）
#+BEGIN_EXAMPLE
喋血·赤霄
喋血·辟岳
喋血·定坤
喋血·夏芒
喋血·灵宝
喋血·惜寒梅
喋血·逆浪
喋血·转魄
#+END_EXAMPLE

*** 穿戴六级PVE·上衣
- 穿戴六级PVE上衣（125品）
#+BEGIN_EXAMPLE
喋血·月影天霜袍
喋血·九州寸心袍
喋血·梦泽千觞袍
喋血·晓梦寒星袍
喋血·冥鸿归云袍
喋血·瑶台清月袍
喋血·暮鸦苍羽袍
喋血·寂夜劫火袍
#+END_EXAMPLE

*** 穿戴六级PVE·下装
- 穿戴六级PVE下装（125品）
#+BEGIN_EXAMPLE
喋血·月影天霜履
喋血·九州寸心履
喋血·梦泽千觞履
喋血·晓梦寒星履
喋血·冥鸿归云履
喋血·瑶台清月履
喋血·暮鸦苍羽履
喋血·寂夜劫火履
#+END_EXAMPLE

*** 穿戴六级PVE·头饰
- 穿戴六级PVE头饰（125品）
#+BEGIN_EXAMPLE
喋血·月影天霜冠
喋血·九州寸心冠
喋血·梦泽千觞冠
喋血·晓梦寒星冠
喋血·冥鸿归云冠
喋血·瑶台清月冠
喋血·暮鸦苍羽冠
喋血·寂夜劫火冠
#+END_EXAMPLE

*** 穿戴六级PVE·内衬
- 穿戴六级PVE内衬（125品）
#+BEGIN_EXAMPLE
喋血·归永夜
#+END_EXAMPLE

*** 穿戴六级PVE·衣带
- 穿戴六级PVE衣带（125品）
#+BEGIN_EXAMPLE
喋血·月影天霜带
喋血·九州寸心带
喋血·梦泽千觞带
喋血·晓梦寒星带
喋血·冥鸿归云带
喋血·瑶台清月带
喋血·暮鸦苍羽带
喋血·寂夜劫火带
#+END_EXAMPLE

*** 穿戴六级PVE·护腕
- 穿戴六级PVE护腕（125品）
#+BEGIN_EXAMPLE
喋血·月影天霜腕
喋血·九州寸心腕
喋血·梦泽千觞腕
喋血·晓梦寒星腕
喋血·冥鸿归云腕
喋血·瑶台清月腕
喋血·暮鸦苍羽腕
喋血·寂夜劫火腕
#+END_EXAMPLE

*** 穿戴六级PVE·手镯
- 穿戴六级PVE手镯（125品）
#+BEGIN_EXAMPLE
天火·月碎镯
金刚·月碎镯
泽兰·月碎镯
#+END_EXAMPLE

*** 穿戴六级PVE·戒指
- 穿戴六级PVE戒指（125品）
#+BEGIN_EXAMPLE
天火·月碎戒
金刚·月碎戒
泽兰·月碎戒
#+END_EXAMPLE

*** 穿戴六级PVE·项链
- 穿戴六级PVE项链（125品）
#+BEGIN_EXAMPLE
天火·月碎链
金刚·月碎链
泽兰·月碎链
#+END_EXAMPLE

*** 穿戴六级PVE·辅武器
- 穿戴六级PVE辅武器（125品）
#+BEGIN_EXAMPLE
喋血·青霜之鞘
喋血·引凤
喋血·傲王侯
喋血·千生
喋血·扁诸之匣
喋血·广寒秋
喋血·沉香
喋血·唤天星
#+END_EXAMPLE

*** 穿戴六级PVE·暗器
- 穿戴六级PVE暗器（125品）
#+BEGIN_EXAMPLE
天火·明月碎
金刚·明月碎
泽兰·明月碎
#+END_EXAMPLE

*** 穿戴六级PVE·主武器
- 穿戴六级PVE主武器（125品）
#+BEGIN_EXAMPLE
喋血·青霜
喋血·伏龙
喋血·遮天
喋血·玦言
喋血·扁诸
喋血·梦仙游
喋血·寂夜
喋血·酹月
#+END_EXAMPLE

*** 穿戴一级PVP·上衣
- 穿戴一级PVP上衣（97品）
#+BEGIN_EXAMPLE
画水微明袍
剑啸寒川袍
勇冠三军袍
侠骨多情袍
琼宫弄月袍
轻梅映雪袍
飞凤苗银袍
刀锋易冷袍
#+END_EXAMPLE

*** 穿戴一级PVP·下装
- 穿戴一级PVP下装（97品）
#+BEGIN_EXAMPLE
画水微明履
剑啸寒川履
勇冠三军履
侠骨多情履
琼宫弄月履
轻梅映雪履
飞凤苗银履
刀锋易冷履
#+END_EXAMPLE

*** 穿戴一级PVP·头饰
- 穿戴一级PVP头饰（97品）
#+BEGIN_EXAMPLE
画水微明冠
剑啸寒川冠
勇冠三军冠
侠骨多情冠
琼宫弄月冠
轻梅映雪冠
飞凤苗银冠
刀锋易冷冠
#+END_EXAMPLE

*** 穿戴一级PVP·衣带
- 穿戴一级PVP衣带（97品）
#+BEGIN_EXAMPLE
画水微明带
剑啸寒川带
勇冠三军带
侠骨多情带
琼宫弄月带
轻梅映雪带
飞凤苗银带
刀锋易冷带
#+END_EXAMPLE

*** 穿戴一级PVP·护腕
- 穿戴一级PVP护腕（97品）
#+BEGIN_EXAMPLE
画水微明腕
剑啸寒川腕
勇冠三军腕
侠骨多情腕
琼宫弄月腕
轻梅映雪腕
飞凤苗银腕
刀锋易冷腕
#+END_EXAMPLE

*** 穿戴一级PVP·辅武器
- 穿戴一级PVP辅武器（97品）
#+BEGIN_EXAMPLE
洛羽之鞘
破空
文君酿
振羽
唯兵之匣
潇湘雨
溟花
思狡兔
#+END_EXAMPLE

*** 穿戴一级PVP·主武器
- 穿戴一级PVP主武器（97品）
#+BEGIN_EXAMPLE
唯兵
洛羽
诛天
潮鸣
影仆
满庭芳
枭树
血魂
#+END_EXAMPLE

*** 穿戴一级PVP·内衬
- 穿戴一级PVP内衬（97品）
#+BEGIN_EXAMPLE
静庭明雪
#+END_EXAMPLE

*** 穿戴一级PVP·手镯
- 穿戴一级PVP手镯（97品）
#+BEGIN_EXAMPLE
龙翡镯
#+END_EXAMPLE

*** 穿戴一级PVP·戒指
- 穿戴一级PVP戒指（97品）
#+BEGIN_EXAMPLE
龙翡戒
#+END_EXAMPLE

*** 穿戴一级PVP·项链
- 穿戴一级PVP项链（97品）
#+BEGIN_EXAMPLE
龙翡链
#+END_EXAMPLE

*** 穿戴一级PVP·暗器
- 穿戴一级PVP暗器（97品）
#+BEGIN_EXAMPLE
白龙锥
#+END_EXAMPLE

*** 穿戴二级PVP·上衣
- 穿戴二级PVP上衣（105品）
#+BEGIN_EXAMPLE
澹云未雨袍
秦风唱晚袍
扬沙万里袍
醉打西风袍
俪影飞星袍
暮语亭兰袍
彩雉青纹袍
长空寄情袍
#+END_EXAMPLE

*** 穿戴二级PVP·下装
- 穿戴二级PVP下装（105品）
#+BEGIN_EXAMPLE
澹云未雨履
秦风唱晚履
扬沙万里履
醉打西风履
俪影飞星履
暮语亭兰履
彩雉青纹履
长空寄情履
#+END_EXAMPLE

*** 穿戴二级PVP·头饰
- 穿戴二级PVP头饰（105品）
#+BEGIN_EXAMPLE
澹云未雨冠
秦风唱晚冠
扬沙万里冠
醉打西风冠
俪影飞星冠
暮语亭兰冠
彩雉青纹冠
长空寄情冠
#+END_EXAMPLE

*** 穿戴二级PVP·衣带
- 穿戴二级PVP衣带（105品）
#+BEGIN_EXAMPLE
澹云未雨带
秦风唱晚带
扬沙万里带
醉打西风带
俪影飞星带
暮语亭兰带
彩雉青纹带
长空寄情带
#+END_EXAMPLE

*** 穿戴二级PVP·护腕
- 穿戴二级PVP护腕（105品）
#+BEGIN_EXAMPLE
秦风唱晚腕
扬沙万里腕
醉打西风腕
俪影飞星腕
澹云未雨腕
暮语亭兰腕
彩雉青纹腕
长空寄情腕
#+END_EXAMPLE

*** 穿戴二级PVP·辅武器
- 穿戴二级PVP辅武器（105品）
#+BEGIN_EXAMPLE
飞景之鞘
惊心
兰陵醉
禅机
子夜歌
圣泪
止辱之匣
画殊风
#+END_EXAMPLE

*** 穿戴二级PVP·主武器
- 穿戴二级PVP主武器（105品）
#+BEGIN_EXAMPLE
止辱
飞景
裂宇
霹雳
玉刹
菩萨蛮
天哭
惕厉
#+END_EXAMPLE

*** 穿戴二级PVP·内衬
- 穿戴二级PVP内衬（105品）
#+BEGIN_EXAMPLE
云天无迹
#+END_EXAMPLE

*** 穿戴二级PVP·手镯
- 穿戴二级PVP手镯（105品）
#+BEGIN_EXAMPLE
翼蝶镯
#+END_EXAMPLE

*** 穿戴二级PVP·戒指
- 穿戴二级PVP戒指（105品）
#+BEGIN_EXAMPLE
翼蝶戒
#+END_EXAMPLE

*** 穿戴二级PVP·项链
- 穿戴二级PVP项链（105品）
#+BEGIN_EXAMPLE
翼蝶链
#+END_EXAMPLE

*** 穿戴二级PVP·暗器
- 穿戴二级PVP暗器（105品）
#+BEGIN_EXAMPLE
天地搜魂针
#+END_EXAMPLE

*** 穿戴三级PVP·上衣
- 穿戴三级PVP上衣（110品）
#+BEGIN_EXAMPLE
朔风吟月袍
扬名千秋袍
醉卷黄河袍
寒影追魂袍
芳姿盈袖袍
掩海遮风袍
掩日风尘袍
拂雨冲云袍
#+END_EXAMPLE

*** 穿戴三级PVP·下装
- 穿戴三级PVP下装（110品）
#+BEGIN_EXAMPLE
拂雨冲云履
朔风吟月履
扬名千秋履
醉卷黄河履
寒影追魂履
芳姿盈袖履
掩海遮风履
掩日风尘履
#+END_EXAMPLE

*** 穿戴三级PVP·头饰
- 穿戴三级PVP头饰（110品）
#+BEGIN_EXAMPLE
拂雨冲云冠
朔风吟月冠
扬名千秋冠
醉卷黄河冠
寒影追魂冠
芳姿盈袖冠
掩海遮风冠
掩日风尘冠
#+END_EXAMPLE

*** 穿戴三级PVP·衣带
- 穿戴三级PVP衣带（110品）
#+BEGIN_EXAMPLE
拂雨冲云带
朔风吟月带
扬名千秋带
醉卷黄河带
寒影追魂带
芳姿盈袖带
掩海遮风带
掩日风尘带
#+END_EXAMPLE

*** 穿戴三级PVP·护腕
- 穿戴三级PVP护腕（110品）
#+BEGIN_EXAMPLE
朔风吟月腕
扬名千秋腕
醉卷黄河腕
寒影追魂腕
芳姿盈袖腕
掩海遮风腕
掩日风尘腕
拂雨冲云腕
#+END_EXAMPLE

*** 穿戴三级PVP·辅武器
- 穿戴三级PVP辅武器（110品）
#+BEGIN_EXAMPLE
盈天之鞘
无常
罗浮春
赋心
千堆雪
吞明
离婴之匣
雪孤飞
#+END_EXAMPLE

*** 穿戴三级PVP·主武器
- 穿戴三级PVP主武器（110品）
#+BEGIN_EXAMPLE
离婴
盈天
判命
重霄
月奴
念奴娇
咽夜
修罗
#+END_EXAMPLE

*** 穿戴三级PVP·内衬
- 穿戴三级PVP内衬（110品）
#+BEGIN_EXAMPLE
一栊孤烟
#+END_EXAMPLE

*** 穿戴三级PVP·手镯
- 穿戴三级PVP手镯（110品）
#+BEGIN_EXAMPLE
璧光镯
#+END_EXAMPLE

*** 穿戴三级PVP·戒指
- 穿戴三级PVP戒指（110品）
#+BEGIN_EXAMPLE
璧光戒
#+END_EXAMPLE

*** 穿戴三级PVP·项链
- 穿戴三级PVP项链（110品）
#+BEGIN_EXAMPLE
璧光链
#+END_EXAMPLE

*** 穿戴三级PVP·暗器
- 穿戴三级PVP暗器（110品）
#+BEGIN_EXAMPLE
银河星
#+END_EXAMPLE

*** 穿戴四级PVP·上衣
- 穿戴四级PVP上衣（115品）
#+BEGIN_EXAMPLE
孤影极寒袍
碧血铭沙袍
酩酊风流袍
晓月长空袍
碎梦繁花袍
百羽双凤袍
丹凤九转袍
玄机空濛袍
#+END_EXAMPLE

*** 穿戴四级PVP·下装
- 穿戴四级PVP下装（115品）
#+BEGIN_EXAMPLE
孤影极寒履
碧血铭沙履
酩酊风流履
晓月长空履
玄机空濛履
碎梦繁花履
百羽双凤履
丹凤九转履
#+END_EXAMPLE

*** 穿戴四级PVP·头饰
- 穿戴四级PVP头饰（115品）
#+BEGIN_EXAMPLE
孤影极寒冠
碧血铭沙冠
酩酊风流冠
晓月长空冠
碎梦繁花冠
百羽双凤冠
丹凤九转冠
玄机空濛冠
#+END_EXAMPLE

*** 穿戴四级PVP·衣带
- 穿戴四级PVP衣带（115品）
#+BEGIN_EXAMPLE
玄机空濛带
孤影极寒带
碧血铭沙带
酩酊风流带
晓月长空带
碎梦繁花带
百羽双凤带
丹凤九转带
#+END_EXAMPLE

*** 穿戴四级PVP·护腕
- 穿戴四级PVP护腕（115品）
#+BEGIN_EXAMPLE
孤影极寒腕
碧血铭沙腕
酩酊风流腕
晓月长空腕
碎梦繁花腕
百羽双凤腕
丹凤九转腕
玄机空濛腕
#+END_EXAMPLE

*** 穿戴四级PVP·辅武器
- 穿戴四级PVP辅武器（115品）
#+BEGIN_EXAMPLE
弧光之鞘
无悔
快活仙
皇图
纵天狱
卜算子
尘灵
凶年之匣
#+END_EXAMPLE

*** 穿戴四级PVP·主武器
- 穿戴四级PVP主武器（115品）
#+BEGIN_EXAMPLE
凶年
弧光
沥泉
奔雷
魑魅
一剪梅
仙色
角羽
#+END_EXAMPLE

*** 穿戴四级PVP·内衬
- 穿戴四级PVP内衬（115品）
#+BEGIN_EXAMPLE
霜夜无尘
#+END_EXAMPLE

*** 穿戴四级PVP·手镯
- 穿戴四级PVP手镯（115品）
#+BEGIN_EXAMPLE
逆鳞镯
#+END_EXAMPLE

*** 穿戴四级PVP·戒指
- 穿戴四级PVP戒指（115品）
#+BEGIN_EXAMPLE
逆鳞戒
#+END_EXAMPLE

*** 穿戴四级PVP·项链
- 穿戴四级PVP项链（115品）
#+BEGIN_EXAMPLE
逆鳞链
#+END_EXAMPLE

*** 穿戴四级PVP·暗器
- 穿戴四级PVP暗器（115品）
#+BEGIN_EXAMPLE
赤炼金蛇
#+END_EXAMPLE

*** 穿戴五级PVP·上衣
- 穿戴五级PVP上衣（120品）
#+BEGIN_EXAMPLE
武道·雪魄尘光袍
武道·瀚海驰骋袍
武道·独酌天下袍
武道·风露霜晨袍
武道·臻姿凤仪袍
武道·枫香泪雨袍
武道·永夜杀神袍
武道·神机韬略袍
#+END_EXAMPLE

*** 穿戴五级PVP·下装
- 穿戴五级PVP下装（120品）
#+BEGIN_EXAMPLE
武道·雪魄尘光履
武道·瀚海驰骋履
武道·独酌天下履
武道·风露霜晨履
武道·臻姿凤仪履
武道·枫香泪雨履
武道·永夜杀神履
武道·神机韬略履
#+END_EXAMPLE

*** 穿戴五级PVP·头饰
- 穿戴五级PVP头饰（120品）
#+BEGIN_EXAMPLE
武道·雪魄尘光冠
武道·瀚海驰骋冠
武道·独酌天下冠
武道·风露霜晨冠
武道·臻姿凤仪冠
武道·枫香泪雨冠
武道·永夜杀神冠
武道·神机韬略冠
#+END_EXAMPLE

*** 穿戴五级PVP·衣带
- 穿戴五级PVP衣带（120品）
#+BEGIN_EXAMPLE
武道·神机韬略带
武道·雪魄尘光带
武道·瀚海驰骋带
武道·独酌天下带
武道·风露霜晨带
武道·臻姿凤仪带
武道·枫香泪雨带
武道·永夜杀神带
#+END_EXAMPLE

*** 穿戴五级PVP·护腕
- 穿戴五级PVP护腕（120品）
#+BEGIN_EXAMPLE
武道·雪魄尘光腕
武道·瀚海驰骋腕
武道·独酌天下腕
武道·风露霜晨腕
武道·臻姿凤仪腕
武道·枫香泪雨腕
武道·永夜杀神腕
武道·神机韬略腕
#+END_EXAMPLE

*** 穿戴五级PVP·辅武器
- 穿戴五级PVP辅武器（120品）
#+BEGIN_EXAMPLE
武道·晴澜之鞘
武道·逐鹿
武道·吞日月
武道·阑珊
武道·斗百花
武道·夺魄
武道·浪于飞
武道·墨阳之匣
#+END_EXAMPLE

*** 穿戴五级PVP·主武器
- 穿戴五级PVP主武器（120品）
#+BEGIN_EXAMPLE
武道·墨阳
武道·晴澜
武道·破阵
武道·捉月
武道·归雪
武道·钗头凤
武道·裁魂
武道·玄夜
#+END_EXAMPLE

*** 穿戴五级PVP·内衬
- 穿戴五级PVP内衬（120品）
#+BEGIN_EXAMPLE
武道·沾轻衣
#+END_EXAMPLE

*** 穿戴五级PVP·手镯
- 穿戴五级PVP手镯（120品）
#+BEGIN_EXAMPLE
武道·寻花镯
#+END_EXAMPLE

*** 穿戴五级PVP·戒指
- 穿戴五级PVP戒指（120品）
#+BEGIN_EXAMPLE
武道·寻花戒
#+END_EXAMPLE

*** 穿戴五级PVP·项链
- 穿戴五级PVP项链（120品）
#+BEGIN_EXAMPLE
武道·寻花链
#+END_EXAMPLE

*** 穿戴五级PVP·暗器
- 穿戴五级PVP暗器（120品）
#+BEGIN_EXAMPLE
武道·寻花间
#+END_EXAMPLE

*** 穿戴六级PVP·上衣
- 穿戴六级PVP上衣（125品）
#+BEGIN_EXAMPLE
武道·月影天霜袍
武道·九州寸心袍
武道·梦泽千觞袍
武道·晓梦寒星袍
武道·瑶台清月袍
武道·暮鸦苍羽袍
武道·寂夜劫火袍
武道·冥鸿归云袍
#+END_EXAMPLE

*** 穿戴六级PVP·下装
- 穿戴六级PVP下装（125品）
#+BEGIN_EXAMPLE
武道·月影天霜履
武道·九州寸心履
武道·梦泽千觞履
武道·晓梦寒星履
武道·瑶台清月履
武道·暮鸦苍羽履
武道·寂夜劫火履
武道·冥鸿归云履
#+END_EXAMPLE

*** 穿戴六级PVP·头饰
- 穿戴六级PVP头饰（125品）
#+BEGIN_EXAMPLE
武道·月影天霜冠
武道·九州寸心冠
武道·梦泽千觞冠
武道·晓梦寒星冠
武道·瑶台清月冠
武道·暮鸦苍羽冠
武道·寂夜劫火冠
武道·冥鸿归云冠
#+END_EXAMPLE

*** 穿戴六级PVP·衣带
- 穿戴六级PVP衣带（125品）
#+BEGIN_EXAMPLE
武道·月影天霜带
武道·九州寸心带
武道·梦泽千觞带
武道·晓梦寒星带
武道·瑶台清月带
武道·暮鸦苍羽带
武道·寂夜劫火带
武道·冥鸿归云带
#+END_EXAMPLE

*** 穿戴六级PVP·护腕
- 穿戴六级PVP护腕（125品）
#+BEGIN_EXAMPLE
武道·月影天霜腕
武道·九州寸心腕
武道·梦泽千觞腕
武道·晓梦寒星腕
武道·瑶台清月腕
武道·暮鸦苍羽腕
武道·寂夜劫火腕
武道·冥鸿归云腕
#+END_EXAMPLE

*** 穿戴六级PVP·辅武器
- 穿戴六级PVP辅武器（125品）
#+BEGIN_EXAMPLE
武道·步光之鞘
武道·潜渊
武道·醉玲珑
武道·惊梦
武道·君不悟
武道·嘲风
武道·吟沧海
武道·青冥之匣
#+END_EXAMPLE

*** 穿戴六级PVP·主武器
- 穿戴六级PVP主武器（125品）
#+BEGIN_EXAMPLE
武道·步光
武道·恚灭
武道·冽冰
武道·昀离
武道·青冥
武道·别仙子
武道·螭吻
武道·狻齿
#+END_EXAMPLE

*** 穿戴六级PVP·内衬
- 穿戴六级PVP内衬（125品）
#+BEGIN_EXAMPLE
武道·归永夜
#+END_EXAMPLE

*** 穿戴六级PVP·手镯
- 穿戴六级PVP手镯（125品）
#+BEGIN_EXAMPLE
武道·月碎镯
#+END_EXAMPLE

*** 穿戴六级PVP·戒指
- 穿戴六级PVP戒指（125品）
#+BEGIN_EXAMPLE
武道·月碎戒
#+END_EXAMPLE

*** 穿戴六级PVP·项链
- 穿戴六级PVP项链（125品）
#+BEGIN_EXAMPLE
武道·月碎链
#+END_EXAMPLE

*** 穿戴六级PVP·暗器
- 穿戴六级PVP暗器（125品）
#+BEGIN_EXAMPLE
武道·明月碎
#+END_EXAMPLE

*** 一级PVE套装毕业
- 12个部位穿戴一级PVE装备（100品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识一级PVE·上衣
达成初识一级PVE·下装
达成初识一级PVE·头饰
达成初识一级PVE·内衬
达成初识一级PVE·衣带
达成初识一级PVE·护腕
达成初识一级PVE·手镯
达成初识一级PVE·戒指
达成初识一级PVE·项链
达成初识一级PVE·辅武器
达成初识一级PVE·暗器
达成初识一级PVE·主武器
#+END_EXAMPLE

*** 二级PVE套装毕业
- 12个部位穿戴二级PVE装备（105品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识二级PVE·上衣
达成初识二级PVE·下装
达成初识二级PVE·头饰
达成初识二级PVE·内衬
达成初识二级PVE·衣带
达成初识二级PVE·护腕
达成初识二级PVE·手镯
达成初识二级PVE·戒指
达成初识二级PVE·项链
达成初识二级PVE·辅武器
达成初识二级PVE·暗器
达成初识二级PVE·主武器
#+END_EXAMPLE

*** 三级PVE套装毕业
- 12个部位穿戴三级PVE装备（110品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识三级PVE·上衣
达成初识三级PVE·下装
达成初识三级PVE·头饰
达成初识三级PVE·内衬
达成初识三级PVE·衣带
达成初识三级PVE·护腕
达成初识三级PVE·手镯
达成初识三级PVE·戒指
达成初识三级PVE·项链
达成初识三级PVE·辅武器
达成初识三级PVE·暗器
达成初识三级PVE·主武器
#+END_EXAMPLE

*** 四级PVE套装毕业
- 12个部位穿戴四级PVE装备（115品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识四级PVE·上衣
达成初识四级PVE·下装
达成初识四级PVE·头饰
达成初识四级PVE·内衬
达成初识四级PVE·衣带
达成初识四级PVE·护腕
达成初识四级PVE·手镯
达成初识四级PVE·戒指
达成初识四级PVE·项链
达成初识四级PVE·辅武器
达成初识四级PVE·暗器
达成初识四级PVE·主武器
#+END_EXAMPLE

*** 五级PVE套装毕业
- 12个部位穿戴五级PVE装备（120品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识五级PVE·上衣
达成初识五级PVE·下装
达成初识五级PVE·头饰
达成初识五级PVE·内衬
达成初识五级PVE·衣带
达成初识五级PVE·护腕
达成初识五级PVE·手镯
达成初识五级PVE·戒指
达成初识五级PVE·项链
达成初识五级PVE·辅武器
达成初识五级PVE·暗器
达成初识五级PVE·主武器
#+END_EXAMPLE

*** 六级PVE套装毕业
- 12个部位穿戴六级PVE装备（125品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识六级PVE·上衣
达成初识六级PVE·下装
达成初识六级PVE·头饰
达成初识六级PVE·内衬
达成初识六级PVE·衣带
达成初识六级PVE·护腕
达成初识六级PVE·手镯
达成初识六级PVE·戒指
达成初识六级PVE·项链
达成初识六级PVE·辅武器
达成初识六级PVE·暗器
达成初识六级PVE·主武器
#+END_EXAMPLE

*** 一级PVP套装毕业
- 12个部位穿戴一级PVP装备（97品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识一级PVP·上衣
达成初识一级PVP·下装
达成初识一级PVP·头饰
达成初识一级PVP·衣带
达成初识一级PVP·护腕
达成初识一级PVP·辅武器
达成初识一级PVP·主武器
达成初识一级PVP·内衬
达成初识一级PVP·手镯
达成初识一级PVP·戒指
达成初识一级PVP·项链
达成初识一级PVP·暗器
#+END_EXAMPLE

*** 二级PVP套装毕业
- 12个部位穿戴二级PVP装备（105品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识二级PVP·上衣
达成初识二级PVP·下装
达成初识二级PVP·头饰
达成初识二级PVP·衣带
达成初识二级PVP·护腕
达成初识二级PVP·辅武器
达成初识二级PVP·主武器
达成初识二级PVP·内衬
达成初识二级PVP·手镯
达成初识二级PVP·戒指
达成初识二级PVP·项链
达成初识二级PVP·暗器
#+END_EXAMPLE

*** 三级PVP套装毕业
- 12个部位穿戴三级PVP装备（110品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识三级PVP·上衣
达成初识三级PVP·下装
达成初识三级PVP·头饰
达成初识三级PVP·衣带
达成初识三级PVP·护腕
达成初识三级PVP·辅武器
达成初识三级PVP·主武器
达成初识三级PVP·内衬
达成初识三级PVP·手镯
达成初识三级PVP·戒指
达成初识三级PVP·项链
达成初识三级PVP·暗器
#+END_EXAMPLE

*** 四级PVP套装毕业
- 12个部位穿戴四级PVP装备（115品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识四级PVP·上衣
达成初识四级PVP·下装
达成初识四级PVP·头饰
达成初识四级PVP·衣带
达成初识四级PVP·护腕
达成初识四级PVP·辅武器
达成初识四级PVP·主武器
达成初识四级PVP·内衬
达成初识四级PVP·手镯
达成初识四级PVP·戒指
达成初识四级PVP·项链
达成初识四级PVP·暗器
#+END_EXAMPLE

*** 五级PVP套装毕业
- 12个部位穿戴五级PVP装备（120品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识五级PVP·上衣
达成初识五级PVP·下装
达成初识五级PVP·头饰
达成初识五级PVP·衣带
达成初识五级PVP·护腕
达成初识五级PVP·辅武器
达成初识五级PVP·主武器
达成初识五级PVP·内衬
达成初识五级PVP·手镯
达成初识五级PVP·戒指
达成初识五级PVP·项链
达成初识五级PVP·暗器
#+END_EXAMPLE

*** 六级PVP套装毕业
- 12个部位穿戴六级PVP装备（125品）-达成12个子成就
#+BEGIN_EXAMPLE
达成初识六级PVP·上衣
达成初识六级PVP·下装
达成初识六级PVP·头饰
达成初识六级PVP·衣带
达成初识六级PVP·护腕
达成初识六级PVP·辅武器
达成初识六级PVP·主武器
达成初识六级PVP·内衬
达成初识六级PVP·手镯
达成初识六级PVP·戒指
达成初识六级PVP·项链
达成初识六级PVP·暗器
#+END_EXAMPLE

** 制造
*** 分工协作
- 请他人代工完成一件装备
#+BEGIN_EXAMPLE
分工协作
#+END_EXAMPLE

*** 协作分工
- 帮助他人代工完成一件装备
#+BEGIN_EXAMPLE
协作分工
#+END_EXAMPLE

*** 有求必应
- 帮助他人代工完成十件装备
#+BEGIN_EXAMPLE
有求必应
#+END_EXAMPLE

*** 全能制造！
- 帮助他人代工完成一百五十件装备
#+BEGIN_EXAMPLE
全能制造！
#+END_EXAMPLE

*** 利刃出鞘
- 曾经在制造的过程中遇到过3种类型的附加属性
#+BEGIN_EXAMPLE
利刃出鞘
#+END_EXAMPLE

*** 能工巧匠
- 曾经在制造过程中遇到过5种类型的附加属性
#+BEGIN_EXAMPLE
能工巧匠
#+END_EXAMPLE

*** 人靠衣装
- 收集十条附加属性
#+BEGIN_EXAMPLE
附加属性
#+END_EXAMPLE

*** 神器天降
- 产出最高品质装备
#+BEGIN_EXAMPLE
神器天降
#+END_EXAMPLE

*** 定制装备
- 燕南飞有蔷薇剑，我也有定制装备（打出一件装备特技）
#+BEGIN_EXAMPLE
打出一件装备特技
#+END_EXAMPLE

** 衣柜
*** 多彩
- 收集5件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 斑斓
- 收集25件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 霓虹
- 收集50件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 绚烂
- 收集100件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 极致
- 收集150件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 圣绣
- 集齐“圣绣”系列外装。
#+BEGIN_EXAMPLE
圣绣·无缺
圣绣·素问
圣绣·雪宸
圣绣·昭华
圣绣·南唐
圣绣·从龙
#+END_EXAMPLE

*** 心王
- 集齐“心王”系列外装。
#+BEGIN_EXAMPLE
心王·逆鳞
心王·九耀
心王·扶苏
心王·蝶衣
#+END_EXAMPLE

*** 天衣无缝
- 集齐“圣绣”系列与“心王”系列外装。
#+BEGIN_EXAMPLE
圣绣
心王
#+END_EXAMPLE

*** 圣绣·无缺
- 获取“圣绣·无缺”外装。
#+BEGIN_EXAMPLE
圣绣·无缺冠
圣绣·无缺袍
圣绣·无缺腕
圣绣·无缺履
#+END_EXAMPLE

*** 圣绣·素问
- 获取“圣绣·素问”外装。
#+BEGIN_EXAMPLE
圣绣·素问冠
圣绣·素问袍
圣绣·素问腕
圣绣·素问履
#+END_EXAMPLE

*** 圣绣·雪宸
- 获取“圣绣·雪宸”外装。
#+BEGIN_EXAMPLE
圣绣·雪宸冠
圣绣·雪宸袍
圣绣·雪宸腕
圣绣·雪宸履
#+END_EXAMPLE

*** 圣绣·昭华
- 获取“圣绣·昭华”外装。
#+BEGIN_EXAMPLE
圣绣·昭华冠
圣绣·昭华袍
圣绣·昭华腕
圣绣·昭华履
#+END_EXAMPLE

*** 圣绣·南唐
- 获取“圣绣·南唐”外装。
#+BEGIN_EXAMPLE
圣绣·南唐冠
圣绣·南唐袍
圣绣·南唐腕
圣绣·南唐履
#+END_EXAMPLE

*** 圣绣·从龙
- 获取“圣绣·从龙”外装。
#+BEGIN_EXAMPLE
圣绣·从龙冠
圣绣·从龙袍
圣绣·从龙腕
圣绣·从龙履
#+END_EXAMPLE

*** 心王·逆鳞
- 获取“心王·逆鳞”外装。
#+BEGIN_EXAMPLE
心王·逆鳞冠
心王·逆鳞袍
心王·逆鳞腕
心王·逆鳞履
#+END_EXAMPLE

*** 心王·九耀
- 获取“心王·九曜”外装。
#+BEGIN_EXAMPLE
心王·九曜冠
心王·九曜袍
心王·九曜腕
心王·九曜履
#+END_EXAMPLE

*** 心王·扶苏
- 获取“心王·扶苏”外装。
#+BEGIN_EXAMPLE
心王·扶苏冠
心王·扶苏袍
心王·扶苏腕
心王·扶苏履
#+END_EXAMPLE

*** 心王·蝶衣
- 获取“心王·蝶衣”外装。
#+BEGIN_EXAMPLE
心王·蝶衣冠
心王·蝶衣袍
心王·蝶衣腕
心王·蝶衣履
#+END_EXAMPLE

*** 鹰飞
- 集齐“鹰飞”系列挂件。
#+BEGIN_EXAMPLE
鹰飞·咽悲风
鹰飞·震天河
鹰飞·羊腿囊
鹰飞·砧上刀
鹰飞·半月匕
#+END_EXAMPLE

*** 攻玉
- 集齐“攻玉”系列挂件。
#+BEGIN_EXAMPLE
攻玉·醉八荒
攻玉·意凌云
攻玉·防草莽
攻玉·缚锁刺
攻玉·羽擎羊
攻玉·血螺旋
攻玉·断黑熊
攻玉·火童子
攻玉·无鞘戳
#+END_EXAMPLE

*** 点石
- 集齐“点石”系列挂件。
#+BEGIN_EXAMPLE
点石·赤鲛肠
点石·刀丛诗
点石·弃天剑
点石·柳生月
点石·降心魔
点石·新罗鼓
点石·七重武
点石·机关谱
点石·飞天曲
#+END_EXAMPLE

*** 七子
- 集齐“七子”系列挂件。
#+BEGIN_EXAMPLE
七子·壹
七子·贰
七子·叁
七子·肆
七子·伍
七子·陆
七子·柒
#+END_EXAMPLE

*** 七情
- 集齐“七情”系列挂件。
#+BEGIN_EXAMPLE
七情·壹
七情·贰
七情·叁
七情·肆
七情·伍
七情·陆
七情·柒
#+END_EXAMPLE

*** 娃娃控
- 集齐“七子”系列与“七情”系列挂件。
#+BEGIN_EXAMPLE
七子
七情
#+END_EXAMPLE

*** 少年称王
- 获取“灵殊·少年称王”挂件。
#+BEGIN_EXAMPLE
灵殊·少年称王
#+END_EXAMPLE

*** 九龙至尊
- 获取“灵殊·九龙至尊”挂件。
#+BEGIN_EXAMPLE
灵殊·九龙至尊
#+END_EXAMPLE

*** 玄鸟凤凰
- 获取“灵殊·玄鸟凤凰”挂件。
#+BEGIN_EXAMPLE
灵殊·玄鸟凤凰
#+END_EXAMPLE

*** 灵殊
- 集齐全套“灵殊”系列挂件。
#+BEGIN_EXAMPLE
少年称王
九龙至尊
玄鸟凤凰
#+END_EXAMPLE

*** 空雪
- 获取任意一匹“空雪”系列骏马。
#+BEGIN_EXAMPLE
空雪·静深流
空雪·云出川
空雪·乌云团
空雪·白公子
空雪·烛天龙
空雪·烛天龙
#+END_EXAMPLE

*** 玄甲
- 获取任意一套“玄甲”系列马具。
#+BEGIN_EXAMPLE
玄甲·纵猎
玄甲·薄战
玄甲·凉州
玄甲·虎牢
玄甲·清商
#+END_EXAMPLE

*** 红尘
- 集齐全套“红尘”外装
#+BEGIN_EXAMPLE
红尘冠
红尘履
红尘袍
红尘腕
#+END_EXAMPLE

*** 兰陵
- 集齐全套“兰陵”外装
#+BEGIN_EXAMPLE
兰陵冠
兰陵履
兰陵袍
兰陵腕
#+END_EXAMPLE

*** 菁华
- 集齐全套“菁华”外装
#+BEGIN_EXAMPLE
菁华冠
菁华履
菁华袍
菁华腕
#+END_EXAMPLE

*** 金碧
- 集齐全套“金碧”外装
#+BEGIN_EXAMPLE
金璧冠
金璧履
金璧袍
金璧腕
#+END_EXAMPLE

*** 绣美人间
- 集齐“红尘”“兰陵”“菁华”“金碧”外装
#+BEGIN_EXAMPLE
红尘套装
兰陵套装
菁华套装
金碧套装
#+END_EXAMPLE

*** 吹雪霓裳
- 集齐“吹雪霓裳套 ”外装
#+BEGIN_EXAMPLE
吹雪霓裳冠
吹雪霓裳袍
吹雪霓裳腕
吹雪霓裳履
#+END_EXAMPLE

*** 人间梦华
- 集齐“人间梦华套 ”外装
#+BEGIN_EXAMPLE
梦华冠 
梦华袍 
梦华腕 
梦华履
#+END_EXAMPLE

*** 袭光
- 集齐全套非绑定“圣绣·袭光”套装（永久）
#+BEGIN_EXAMPLE
圣绣·袭光冠
圣绣·袭光袍
圣绣·袭光腕
圣绣·袭光履
#+END_EXAMPLE

*** 天岚
- 集齐全套非绑定“圣绣·天岚”套装（永久）
#+BEGIN_EXAMPLE
圣绣·天岚冠
圣绣·天岚袍
圣绣·天岚腕
圣绣·天岚履
#+END_EXAMPLE

*** 国宝
- 获得一只熊猫（60天）
#+BEGIN_EXAMPLE
熊猫
#+END_EXAMPLE

*** 白狐
- 获得心王·独孤套装（永久）
#+BEGIN_EXAMPLE
心王·独孤冠
心王·独孤袍
心王·独孤腕
心王·独孤履
#+END_EXAMPLE

*** 萌趣
- 获取任意一件“萌趣”系列挂件。
#+BEGIN_EXAMPLE
萌趣·离盟主
萌趣·叶大侠
萌趣·唐师兄
萌趣·曲姑娘
#+END_EXAMPLE

*** 博爱
- 集齐全部“萌趣”系列挂件。
#+BEGIN_EXAMPLE
萌趣·离盟主
萌趣·叶大侠
萌趣·唐师兄
萌趣·曲姑娘
#+END_EXAMPLE

*** 天地君王
- 集齐“圣绣·北辰”和“日月当空”外装。
#+BEGIN_EXAMPLE
圣绣·北辰冠
圣绣·北辰袍
圣绣·北辰腕
圣绣·北辰履
日月当空冠
日月当空袍
日月当空腕
日月当空履
#+END_EXAMPLE

*** 张梦白：天高雨歇
- 在“试问天心”中获得了和张梦白相同的结果
#+BEGIN_EXAMPLE
同签成就：张梦白
#+END_EXAMPLE

*** 一云子：五风十雨
- 在“试问天心”中获得了和一云子相同的结果
#+BEGIN_EXAMPLE
同签成就：一云子
#+END_EXAMPLE

*** 龙复兴：雪拥蓝关
- 在“试问天心”中获得了和龙复兴相同的结果
#+BEGIN_EXAMPLE
同签成就：龙复兴
#+END_EXAMPLE

*** 文秀山：把火看花
- 在“试问天心”中获得了和文秀山相同的结果
#+BEGIN_EXAMPLE
同签成就：文秀山
#+END_EXAMPLE

*** 笑道人：道是无情
- 在“试问天心”中获得了和笑道人相同的结果
#+BEGIN_EXAMPLE
同签成就：笑道人
#+END_EXAMPLE

*** 百晓生：疾不可为
- 在“试问天心”中获得了和百晓生相同的结果
#+BEGIN_EXAMPLE
同签成就：百晓生
#+END_EXAMPLE

*** 公子羽：亢龙有悔
- 在“试问天心”中获得了和公子羽相同的结果
#+BEGIN_EXAMPLE
同签成就：公子羽
#+END_EXAMPLE

*** 蓝铮：沧海长风
- 在“试问天心”中获得了和蓝铮相同的结果
#+BEGIN_EXAMPLE
同签成就：蓝铮
#+END_EXAMPLE

*** 白玉京：万国来朝
- 在“试问天心”中获得了和白玉京相同的结果
#+BEGIN_EXAMPLE
同签成就：白玉京
#+END_EXAMPLE

*** 路小佳：洛阳梅花
- 在“试问天心”中获得了和路小佳相同的结果
#+BEGIN_EXAMPLE
同签成就：路小佳
#+END_EXAMPLE

*** 唐灵玉：初见端倪
- 在“试问天心”中获得了和唐灵玉相同的结果
#+BEGIN_EXAMPLE
同签成就：唐灵玉
#+END_EXAMPLE

*** 沈孤鸿：雪泥鸿爪
- 在“试问天心”中获得了和沈孤鸿相同的结果
#+BEGIN_EXAMPLE
同签成就：沈孤鸿
#+END_EXAMPLE

*** 唐青枫：出众风流
- 在“试问天心”中获得了和唐青枫相同的结果
#+BEGIN_EXAMPLE
同签成就：唐青枫
#+END_EXAMPLE

*** 白云轩：碧海青天
- 在“试问天心”中获得了和白云轩相同的结果
#+BEGIN_EXAMPLE
同签成就：白云轩
#+END_EXAMPLE

*** 薛无泪：金玉满堂
- 在“试问天心”中获得了和薛无泪相同的结果
#+BEGIN_EXAMPLE
同签成就：薛无泪
#+END_EXAMPLE

*** 叶知秋：天下归心
- 在“试问天心”中获得了和叶知秋相同的结果
#+BEGIN_EXAMPLE
同签成就：叶知秋
#+END_EXAMPLE

*** 冶儿：五行之秀
- 在“试问天心”中获得了和冶儿相同的结果
#+BEGIN_EXAMPLE
同签成就：冶儿
#+END_EXAMPLE

*** 明月心：明月孤心
- 在“试问天心”中获得了和明月心相同的结果
#+BEGIN_EXAMPLE
同签成就：明月心
#+END_EXAMPLE

*** 曲无忆：忙做嫁衣
- 在“试问天心”中获得了和曲无忆相同的结果
#+BEGIN_EXAMPLE
同签成就：曲无忆
#+END_EXAMPLE

*** 离玉堂：太平盛世
- 在“试问天心”中获得了和离玉堂相同的结果
#+BEGIN_EXAMPLE
同签成就：离玉堂
#+END_EXAMPLE

*** 燕南飞：过尽千帆
- 在“试问天心”中获得了和燕南飞相同的结果
#+BEGIN_EXAMPLE
同签成就：燕南飞
#+END_EXAMPLE

*** 上官小仙：暮春飞花
- 在“试问天心”中获得了和上官小仙相同的结果
#+BEGIN_EXAMPLE
同签成就：上官小仙
#+END_EXAMPLE

*** 杨延玉：沙里淘金
- 在“试问天心”中获得了和杨延玉相同的结果
#+BEGIN_EXAMPLE
同签成就：杨延玉
#+END_EXAMPLE

*** 子桑不寿：曲水流觞
- 在“试问天心”中获得了和子桑不寿相同的结果
#+BEGIN_EXAMPLE
同签成就：子桑不寿
#+END_EXAMPLE

*** 赏玩
- 获取任一载具类型外装。
#+BEGIN_EXAMPLE
吟风·琉璃焰
吟风·琉璃焰
吟风·碧霄诗情
吟风·以梦为马
跷跷板
#+END_EXAMPLE

*** 光鲜
- 收集200件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 阔绰
- 收集250件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

*** 盛装
- 收集300件外装进入衣柜
#+BEGIN_EXAMPLE
外装
#+END_EXAMPLE

