#+TITLE: 人物成长
#+AUTHOR: 李鹄

* 在线
** 陌上花开·壹
- 再次回到天涯明月刀的世界
#+BEGIN_EXAMPLE
累计登录2天
#+END_EXAMPLE

** 陌上花开·贰
- 累计在天涯明月刀的世界里游历七天
#+BEGIN_EXAMPLE
累计登录7天
#+END_EXAMPLE

** 陌上花开·叁
- 累计在天涯明月刀的世界里游历十四天
#+BEGIN_EXAMPLE
累计登录14天
#+END_EXAMPLE

** 陌上开花·肆
- 累计在天涯明月刀的世界里游历三十天
#+BEGIN_EXAMPLE
累计登录30天
#+END_EXAMPLE

** 陌上开花·伍
- 累计在天涯明月刀的世界里游历六十天
#+BEGIN_EXAMPLE
累计登录60天
#+END_EXAMPLE

** 陌上开花·陆
- 累计在天涯明月刀的世界里游历九十天
#+BEGIN_EXAMPLE
累计登录90天
#+END_EXAMPLE

** 陌上开花·柒
- 累计在天涯明月刀的世界里游历一百八十天
#+BEGIN_EXAMPLE
累计登录180天
#+END_EXAMPLE

** 陌上开花·捌
- 累计在天涯明月刀的世界里游历二百七十天
#+BEGIN_EXAMPLE
累计登录270天
#+END_EXAMPLE

** 陌上开花·玖
- 累计在天涯明月刀的世界里游历三百六十天
#+BEGIN_EXAMPLE
累计登录360天
#+END_EXAMPLE

** 陌上开花·拾
- 累计在天涯明月刀的世界里游历七百二十天
#+BEGIN_EXAMPLE
累计登录720天
#+END_EXAMPLE

** 蔷薇信使
- 向好友发送一封邮件
#+BEGIN_EXAMPLE
发送一封邮件
#+END_EXAMPLE

** 累计签到·壹
- 历史累计签到30天
#+BEGIN_EXAMPLE
历史累计签到30天
#+END_EXAMPLE

** 累计签到·贰
- 历史累计签到365天
#+BEGIN_EXAMPLE
历史累计签到365天
#+END_EXAMPLE

** 累计签到·叁
- 历史累计签到1000天
#+BEGIN_EXAMPLE
历史累计签到1000天
#+END_EXAMPLE

** 陌上开花·拾壹
- 累计在天涯明月刀的世界里游历一零八零天
#+BEGIN_EXAMPLE
累计登录1080天
#+END_EXAMPLE

* 见闻
** 泱泱华夏
- 用工整美观的中文作为自己的游戏昵称
#+BEGIN_EXAMPLE
中文名
#+END_EXAMPLE

** 夜探郡王府
- 应天波府之邀，趁夜色掩护潜入东平郡王府，终于粉碎赵允弼阴谋
#+BEGIN_EXAMPLE
完成话本“东平郡王府（夜间）”
#+END_EXAMPLE

** 击退连环使
- 完成“遭遇连环使”系列见闻
#+BEGIN_EXAMPLE
路不平·素手助道人
雀捕蝉·伏击连环使
#+END_EXAMPLE

** 解谜孔雀门
- 完成“孔雀门人”系列见闻
#+BEGIN_EXAMPLE
孔雀门·舍命报师恩
孔雀门·绝地遇佳人
孔雀门·高谊伴轻风（一）
孔雀门·高谊伴轻风（二）
孔雀门·高谊伴轻风（三）
孔雀门·翎羽生死劫
孔雀门·结草不忘恩
#+END_EXAMPLE

** 惩治恶衙内
- 完成“恶衙内”系列见闻
#+BEGIN_EXAMPLE
游杭州·初遇小阎王
逛街巷·再行侠义道
行侠道·大闹衙内府
#+END_EXAMPLE

** 智救痴情侣
- 完成“江洋大盗”系列见闻
#+BEGIN_EXAMPLE
是非直·重金捉大盗
倒黑白·情痴困旧城
喜结缘·天涯有情郎
#+END_EXAMPLE

** 俏茶娘寻夫
- 完成“茶娘”系列见闻
#+BEGIN_EXAMPLE
凤孤飞·俏茶娘寻夫
机关尽·兄弟阋于墙
鸳梦碎·知会俏茶娘
#+END_EXAMPLE

** 扑朔迷离
- 完成辨是非·雄兔脚扑朔和辨是非·雌兔眼迷离
#+BEGIN_EXAMPLE
辨是非·雄兔脚扑朔
辨是非·雌兔眼迷离
#+END_EXAMPLE

** 八骏唏嘘叹
- 完成“八骏图”系列见闻
#+BEGIN_EXAMPLE
红草滩·以武鉴知己
疑云起·八骏成反目
探古镇·真相浮水面
叹唏嘘·江湖多变幻
#+END_EXAMPLE

** 啼笑定姻缘
- 完成杭州离玉堂与韩莹莹系列见闻
#+BEGIN_EXAMPLE
大闹天波府
萍水逢·招亲惹风波
井底蛙·打擂凤凰集
永兴寺遇袭
#+END_EXAMPLE

** 谁解美人傲
- 完成美人傲系列见闻
#+BEGIN_EXAMPLE
201个好友
#+END_EXAMPLE

** 红叶伴青枫
- 完成“青枫焰·临竹醉清风”和“青枫焰·幽花落横笛”
#+BEGIN_EXAMPLE
青枫焰·临竹醉清风
青枫焰·幽花落横笛
#+END_EXAMPLE

** 杭州逢雅奴
- 完成“雅奴”系列见闻
#+BEGIN_EXAMPLE
薄情儿·西湖殇夜月
会故人·暮雨恨朝云
心难测·执手走天涯
#+END_EXAMPLE

** 见闻杭州
- 在杭州完成6个单次见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
杭州
#+END_EXAMPLE

** 见闻江南
- 在江南完成6个故事性见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
江南
#+END_EXAMPLE

** 见闻东越
- 在东越完成17个故事性见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
东越
#+END_EXAMPLE

** 见闻徐海
- 在徐海完成7个故事性见闻（含故事见闻、教学见闻）
#+BEGIN_EXAMPLE
徐海
#+END_EXAMPLE

** 问水庄
- 完成问水庄系列见闻
#+BEGIN_EXAMPLE
问水庄
#+END_EXAMPLE

** 佛语禅心
- 完成九华佛语禅心任务的隐藏分支
#+BEGIN_EXAMPLE
佛语禅心
#+END_EXAMPLE

** 余音绕梁
- 完成九华君子六艺任务的隐藏分支
#+BEGIN_EXAMPLE
余音绕梁
#+END_EXAMPLE

** 万点繁星
- 完成唐门门派见闻
#+BEGIN_EXAMPLE
闻旧事·闲潭竹影幽
孝女心·思亲天一房
#+END_EXAMPLE

** 剑履山河
- 完成太白门派见闻
#+BEGIN_EXAMPLE
祭故人·沉剑池往事
镇蛊毒·终身伴白雪
#+END_EXAMPLE

** 天地不仁
- 完成真武门派见闻
#+BEGIN_EXAMPLE
道者心·有情亦无情
识蔷薇·人外有高人
#+END_EXAMPLE

** 星河倒卷
- 完成神威门派见闻
#+BEGIN_EXAMPLE
很难偿·故园失手足
斩奸邪·风沙起大漠
#+END_EXAMPLE

** 龙震百里
- 完成丐帮门派见闻
#+BEGIN_EXAMPLE
思无邪·无猜亦无忧
风华茂·少年展头角
#+END_EXAMPLE

** 重华乱舞
- 完成天香门派见闻
#+BEGIN_EXAMPLE
步花间·稚童踪难觅
梦行云·莫问花解语
#+END_EXAMPLE

** 万里残阳
- 完成杭州系列见闻（低级）
#+BEGIN_EXAMPLE
优昙花·夺花尽心计
缔情缘·永兴寺遇袭
黑与白·子夜露锋芒
#+END_EXAMPLE

** 谁应帝王
- 完成江南系列见闻
#+BEGIN_EXAMPLE
美人傲·月夜望星河
茶瓶儿·难解女儿心
青枫焰·临竹醉清风
风骤起·携手破连环
何为侠·尽在不言中
照孤星·挥剑破孤星
#+END_EXAMPLE

** 浪迹天涯
- 完成东越系列见闻
#+BEGIN_EXAMPLE
雀捕蝉·伏击连环使
凤孤飞·知会俏茶娘
是非直·天涯有情郎
#+END_EXAMPLE

** 独立寒江
- 完成杭州系列见闻（高级）
#+BEGIN_EXAMPLE
心难测·执手走天涯
空余恨·惨雨红衣林
姊妹缘·曲远暗香随
#+END_EXAMPLE

** 龙吟水上
- 完成九华系列见闻
#+BEGIN_EXAMPLE
酬知己·高谊伴轻风
孔雀门·翎羽生死劫
芳心苦·绝地遇佳人
辨是非·雌兔眼迷离
#+END_EXAMPLE

** 义薄云天
- 完成徐海系列见闻
#+BEGIN_EXAMPLE
神刀谱·江湖多变幻
江湖醉·一世为兄弟
情两难系列见闻
#+END_EXAMPLE

** 心如明镜
- 完成开封系列见闻
#+BEGIN_EXAMPLE
双全法·一念在人间
盗有道·赤子起顽心
#+END_EXAMPLE

** 情天恨海
- 完成秦川系列见闻
#+BEGIN_EXAMPLE
天魔影·一剑荡群魔
白毛怪·此情成追忆
#+END_EXAMPLE

** 五仙灭地
- 完成五毒门派见闻
#+BEGIN_EXAMPLE
祭亡妻·年年一相聚
讲旧事·代代有传奇
#+END_EXAMPLE

** 情两难
- 完成情两难系列见闻
#+BEGIN_EXAMPLE
情两难·恩怨总难平
情两难·恩仇多变换
#+END_EXAMPLE

** 神鬼夜哭
- 完成神刀门派见闻
#+BEGIN_EXAMPLE
万仞峰·饮流怀其源
驯鹰师·神鹰云梦泽
#+END_EXAMPLE

** 沧溟九歌
- 完成移花门派见闻
#+BEGIN_EXAMPLE
云中词·谁寄锦书来
护花人·轻舟似群星
#+END_EXAMPLE

** 巨浪白鱼
- 在国风运动节中钓到50条白色大鱼
#+BEGIN_EXAMPLE
白色大鱼50条
#+END_EXAMPLE

** 巨浪青鲲
- 在国风运动节中钓到50条青色大鱼
#+BEGIN_EXAMPLE
青色大鱼50条
#+END_EXAMPLE

** 巨浪赤虹
- 在国风运动节中钓到50条赤色大鱼
#+BEGIN_EXAMPLE
赤虹50条
#+END_EXAMPLE

** 心细如毫
- 在国风运动节中钓到10只籽虾
#+BEGIN_EXAMPLE
籽虾10只
#+END_EXAMPLE

** 慧眼如炬
- 在国风运动节中钓到10只金色绒毛小蟹
#+BEGIN_EXAMPLE
金色绒毛小蟹10只
#+END_EXAMPLE

** 时速不限
- 国风运动节中完成5次赛马
#+BEGIN_EXAMPLE
国风运动节中参与5次赛马
#+END_EXAMPLE

** 百晓全书
- 国风运动节期间完成10次明辨真假
#+BEGIN_EXAMPLE
国风运动节期间完成10次明辨真假
#+END_EXAMPLE

** 全面发展
- 达成国风运动节期间所有成就
#+BEGIN_EXAMPLE
巨浪白鱼
巨浪青鲲
巨浪赤虹
心细如毫
慧眼如炬
时速不限
百晓全书
#+END_EXAMPLE

** 吃鱼让我快乐
- 节日期间，鱼类菜式各吃过10份以上
#+BEGIN_EXAMPLE
红烧划水10份
剁椒鱼头10份
萝卜鱼头汤10份
豆瓣全鱼10份
糖醋鱼10份
#+END_EXAMPLE

** 暖心饺子
- 节日期间，四种饺子各送出一份
#+BEGIN_EXAMPLE
飞剑童的猪肉饺子
飞剑童的牛肉饺子
飞剑童的羊肉饺子
飞剑童的鸡蛋饺子
#+END_EXAMPLE

** 万物有灵
- 节日期间，飞剑童的饺子喂给小猫或小狗三次
#+BEGIN_EXAMPLE
飞剑童的羊肉饺子
飞剑童的鸡蛋饺子
#+END_EXAMPLE

** 满头是雪
- 完成五次打雪仗日常任务
#+BEGIN_EXAMPLE
打雪仗5次
#+END_EXAMPLE

** 玩疯了！
- 在单场打雪仗中获得80分
#+BEGIN_EXAMPLE
打雪仗80分
#+END_EXAMPLE

** 隐藏菜谱
- 获得隐藏菜谱
#+BEGIN_EXAMPLE
隐藏菜谱
#+END_EXAMPLE

** 铃儿响叮当
- 为西域老人找回三次铃铛
#+BEGIN_EXAMPLE
圣诞老人的铃铛
#+END_EXAMPLE

** 是你？
- 完成2018元旦特殊剧情“天上白玉京，人间生死劫”
#+BEGIN_EXAMPLE
天上白玉京人间生死劫
#+END_EXAMPLE

** 忙碌一冬
- 达成以上所有
#+BEGIN_EXAMPLE
吃鱼让我快乐
暖心饺子
万物有灵
满头是雪
玩疯了！
隐藏菜谱
铃儿响叮当
是你？
#+END_EXAMPLE

** 堆个大雪人·天峰盟
- 所在服务器的天峰盟的雪人堆成了
#+BEGIN_EXAMPLE
天峰盟雪人
#+END_EXAMPLE

** 堆个大雪人·青龙会
- 所在服务器的青龙会的雪人堆成了
#+BEGIN_EXAMPLE
青龙会雪人
#+END_EXAMPLE

** 雪里咕噜
- 上交了五次堆雪人的材料
#+BEGIN_EXAMPLE
帮助天峰盟堆雪人
帮助青龙会堆雪人
#+END_EXAMPLE

** 越滚越大
- 完成“雪里咕噜”和“堆个大雪人”
#+BEGIN_EXAMPLE
雪里咕噜
雪人堆成
#+END_EXAMPLE

** 雪人堆成了
- 青龙会或天峰盟的雪人堆成了
#+BEGIN_EXAMPLE
天峰盟雪人
青龙会雪人
#+END_EXAMPLE

** 滚来滚去·初级
- 踩着雪球飞跃了200米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了200米以上
#+END_EXAMPLE

** 滚来滚去·中级
- 踩着雪球飞跃了300米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了300米以上
#+END_EXAMPLE

** 滚来滚去·高级
- 踩着雪球飞跃了350米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了350米以上
#+END_EXAMPLE

** 滚来滚去·起跳
- 踩着雪球飞跃了380米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了380米以上
#+END_EXAMPLE

** 滚来滚去·起飞
- 踩着雪球飞跃了400米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了400米以上
#+END_EXAMPLE

** 滚来滚去·飞跃
- 踩着雪球飞跃了410米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了410米以上
#+END_EXAMPLE

** 滚来滚去·极限
- 踩着雪球飞跃了420米以上
#+BEGIN_EXAMPLE
踩着雪球飞跃了420米以上
#+END_EXAMPLE

** 滚来滚去·精准命中
- 踩着雪球精准降落在村落的红色圆圈内
#+BEGIN_EXAMPLE
踩着雪球精准降落在村落的红色圆圈内
#+END_EXAMPLE

** 试练·于百石
- 小试牛刀·击败于百石
#+BEGIN_EXAMPLE
于百石
#+END_EXAMPLE

** 试练·黄陶朱
- 小试牛刀·击败黄陶朱
#+BEGIN_EXAMPLE
金煞·黄陶朱
#+END_EXAMPLE

** 试练·白邓通
- 小试牛刀·白邓通
#+BEGIN_EXAMPLE
银煞·白邓通
#+END_EXAMPLE

** 试练·莫川
- 小试牛刀·莫川
#+BEGIN_EXAMPLE
铁眼·莫川
#+END_EXAMPLE

** 试练·齐落梅
- 小试牛刀·击败齐落梅
#+BEGIN_EXAMPLE
齐落梅
#+END_EXAMPLE

** 试练·沐摇光
- 小试牛刀·击败沐摇光
#+BEGIN_EXAMPLE
沐摇光
#+END_EXAMPLE

** 试练·段飞鹏
- 小试牛刀·击败段飞鹏
#+BEGIN_EXAMPLE
段飞鹏
#+END_EXAMPLE

** 试练·霍天鹏
- 小试牛刀·击败霍天鹏
#+BEGIN_EXAMPLE
霍天鹏
#+END_EXAMPLE

** 试练·孟长风
- 小试牛刀·击败孟长风
#+BEGIN_EXAMPLE
孟长风
#+END_EXAMPLE

** 试练·冷不凡
- 小试牛刀·击败冷不凡
#+BEGIN_EXAMPLE
冷不凡
#+END_EXAMPLE

** 试练·白丹青
- 小试牛刀·击败白丹青
#+BEGIN_EXAMPLE
白丹青
#+END_EXAMPLE

** 试练·严泽
- 小试牛刀·击败严泽
#+BEGIN_EXAMPLE
严泽
#+END_EXAMPLE

** 试练·慕容锦
- 小试牛刀·击败慕容锦
#+BEGIN_EXAMPLE
慕容锦
#+END_EXAMPLE

** 试练·子桑不寿
- 小试牛刀·击败子桑不寿
#+BEGIN_EXAMPLE
子桑不寿
#+END_EXAMPLE

** 试练·何盼理
- 小试牛刀·击败何盼理
#+BEGIN_EXAMPLE
何盼理
#+END_EXAMPLE

** 试练·杨尚砚
- 小试牛刀·击败杨尚砚
#+BEGIN_EXAMPLE
杨尚砚
#+END_EXAMPLE

** 试练·柳永
- 小试牛刀·击败柳永
#+BEGIN_EXAMPLE
柳永
#+END_EXAMPLE

** 试练·雅奴二十六
- 小试牛刀·击败雅奴二十六
#+BEGIN_EXAMPLE
雅奴二十六
#+END_EXAMPLE

** 试练·黄元文
- 小试牛刀·击败黄元文
#+BEGIN_EXAMPLE
黄元文
#+END_EXAMPLE

** 试练·扫地僧
- 小试牛刀·击败扫地僧
#+BEGIN_EXAMPLE
扫地僧
#+END_EXAMPLE

** 试练·满天和
- 小试牛刀·击败满天和
#+BEGIN_EXAMPLE
满天和
#+END_EXAMPLE

** 试练·秋宿犁
- 小试牛刀·击败秋宿犁
#+BEGIN_EXAMPLE
秋宿犁
#+END_EXAMPLE

** 试练·南宫玉博
- 小试牛刀·击败南宫玉博
#+BEGIN_EXAMPLE
南宫玉博
#+END_EXAMPLE

** 试练·陶梦翟
- 小试牛刀·击败陶梦翟
#+BEGIN_EXAMPLE
陶梦翟
#+END_EXAMPLE

** 试练·端木横
- 小试牛刀·击败端木横
#+BEGIN_EXAMPLE
端木横
#+END_EXAMPLE

** 试练·秦飞虹
- 小试牛刀·击败秦飞虹
#+BEGIN_EXAMPLE
秦飞虹
#+END_EXAMPLE

** 试练·鸿鹄子
- 小试牛刀·击败鸿鹄子
#+BEGIN_EXAMPLE
鸿鹄子
#+END_EXAMPLE

** 试练·慧远禅师
- 小试牛刀·击败慧远禅师
#+BEGIN_EXAMPLE
慧远禅师
#+END_EXAMPLE

** 试练·郑天石
- 小试牛刀·击败郑天石
#+BEGIN_EXAMPLE
郑天石
#+END_EXAMPLE

** 试练·庞三刀
- 小试牛刀·击败庞三刀
#+BEGIN_EXAMPLE
庞三刀
#+END_EXAMPLE

** 试练·杜十七
- 小试牛刀·击败杜十七
#+BEGIN_EXAMPLE
杜十七
#+END_EXAMPLE

** 试练·渡厄尊者
- 小试牛刀·击败渡厄尊者
#+BEGIN_EXAMPLE
渡厄尊者
#+END_EXAMPLE

** 试练·杜伯
- 小试牛刀·击败杜伯
#+BEGIN_EXAMPLE
杜伯
#+END_EXAMPLE

** 试练·石守信
- 小试牛刀·击败石守信
#+BEGIN_EXAMPLE
石守信
#+END_EXAMPLE

** 试练·范宽
- 小试牛刀·击败范宽
#+BEGIN_EXAMPLE
范宽
#+END_EXAMPLE

** 试练·冷皓轩
- 小试牛刀·击败冷皓轩
#+BEGIN_EXAMPLE
冷皓轩
#+END_EXAMPLE

** 试练·花无心
- 小试牛刀·击败花无心
#+BEGIN_EXAMPLE
花无心
#+END_EXAMPLE

** 试练·陆十八
- 小试牛刀·击败陆十八
#+BEGIN_EXAMPLE
陆十八
#+END_EXAMPLE

** 试练·陆山川
- 小试牛刀·击败陆山川
#+BEGIN_EXAMPLE
陆山川
#+END_EXAMPLE

** 试练·武莫风
- 小试牛刀·击败武莫风
#+BEGIN_EXAMPLE
武莫风
#+END_EXAMPLE

** 试练·笑道人
- 小试牛刀·击败笑道人
#+BEGIN_EXAMPLE
笑道人
#+END_EXAMPLE

** 试练·吴振英
- 小试牛刀·击败吴振英
#+BEGIN_EXAMPLE
吴振英
#+END_EXAMPLE

** 试练·邓心禅
- 小试牛刀·击败邓心禅
#+BEGIN_EXAMPLE
邓心禅
#+END_EXAMPLE

** 试练·塔夫大师
- 小试牛刀·击败塔夫大师
#+BEGIN_EXAMPLE
塔夫大师
#+END_EXAMPLE

** 试练·杨延玉
- 小试牛刀·击败杨延玉
#+BEGIN_EXAMPLE
杨延玉
#+END_EXAMPLE

** 试练·温景梵
- 小试牛刀·温景梵
#+BEGIN_EXAMPLE
温景梵
#+END_EXAMPLE

** 试练·钟舒文
- 小试牛刀·钟舒文
#+BEGIN_EXAMPLE
钟舒文
#+END_EXAMPLE

** 试练·公孙剑
- 小试牛刀·公孙剑
#+BEGIN_EXAMPLE
公孙剑
#+END_EXAMPLE

** 试练·何荐华
- 小试牛刀·何荐华
#+BEGIN_EXAMPLE
何荐华
#+END_EXAMPLE

** 试练·独孤若虚
- 小试牛刀·独孤若虚
#+BEGIN_EXAMPLE
独孤若虚
#+END_EXAMPLE

** 试练·诸葛断
- 小试牛刀·诸葛断
#+BEGIN_EXAMPLE
诸葛断
#+END_EXAMPLE

** 试练·倪慧
- 小试牛刀·倪慧
#+BEGIN_EXAMPLE
倪慧
#+END_EXAMPLE

** 试练·古尔扎
- 小试牛刀·古尔扎
#+BEGIN_EXAMPLE
古尔扎
#+END_EXAMPLE

** 试炼·李元
- 小试牛刀·李元
#+BEGIN_EXAMPLE
李元
#+END_EXAMPLE

** 试炼·赫连达飞
- 小试牛刀·赫连达飞
#+BEGIN_EXAMPLE
赫连达飞
#+END_EXAMPLE

** 试炼·韩思思
- 小试牛刀·韩思思
#+BEGIN_EXAMPLE
韩思思
#+END_EXAMPLE

** 试炼·张文拓
- 小试牛刀·张文拓
#+BEGIN_EXAMPLE
张文拓
#+END_EXAMPLE

** 试炼·韩莹莹
- 小试牛刀·韩莹莹
#+BEGIN_EXAMPLE
韩莹莹
#+END_EXAMPLE

** 试炼·天刀营先锋
- 小试牛刀·天刀营先锋
#+BEGIN_EXAMPLE
天刀营先锋
#+END_EXAMPLE

** 试炼·思成
- 小试牛刀·思成
#+BEGIN_EXAMPLE
思成
#+END_EXAMPLE

** 试炼·萧衍
- 小试牛刀·萧衍
#+BEGIN_EXAMPLE
萧衍
#+END_EXAMPLE

** 试炼·皇甫星
- 小试牛刀·皇甫星
#+BEGIN_EXAMPLE
皇甫星
#+END_EXAMPLE

** 试炼·药九
- 小试牛刀·青龙会药九
#+BEGIN_EXAMPLE
青龙会药九
#+END_EXAMPLE

** 试炼·李红渠
- 小试牛刀·李红渠
#+BEGIN_EXAMPLE
李红渠
#+END_EXAMPLE

** 试炼·唐端
- 小试牛刀·唐端
#+BEGIN_EXAMPLE
唐端
#+END_EXAMPLE

** 试炼·傀儡
- 小试牛刀·青枫傀儡
#+BEGIN_EXAMPLE
唐青枫的傀儡
#+END_EXAMPLE

** 试炼·上官小仙
- 小试牛刀·上官小仙
#+BEGIN_EXAMPLE
上官小仙
#+END_EXAMPLE

** 试炼·百里研阳
- 小试牛刀·百里研阳
#+BEGIN_EXAMPLE
百里研阳
#+END_EXAMPLE

** 试炼·唐啸天弟子
- 小试牛刀·唐啸天弟子
#+BEGIN_EXAMPLE
唐啸天弟子
#+END_EXAMPLE

** 点滴进步
- 试练给予属性点奖励
#+BEGIN_EXAMPLE
唐啸天弟子
#+END_EXAMPLE

** 墨宝收藏
- 收藏墨宝给予属性点奖励
#+BEGIN_EXAMPLE
画卷：忘忧谷
#+END_EXAMPLE

** 完成见闻
- 见闻给予属性点奖励
#+BEGIN_EXAMPLE
少年游·明月似故人
#+END_EXAMPLE

** 独孤不疑！
- 目睹江洋大盗独孤不疑的死亡！
#+BEGIN_EXAMPLE
独孤不疑
到达51级
#+END_EXAMPLE

** 楚天！
- 目睹江洋大盗楚天的死亡！
#+BEGIN_EXAMPLE
楚天
到达51级
#+END_EXAMPLE

** 纪沧海！
- 目睹江洋大盗纪沧海的死亡！
#+BEGIN_EXAMPLE
纪沧海
到达51级
#+END_EXAMPLE

** 李十三！
- 目睹江洋大盗李十三的死亡！
#+BEGIN_EXAMPLE
李十三
到达51级
#+END_EXAMPLE

** 王错！
- 目睹江洋大盗王错的死亡！
#+BEGIN_EXAMPLE
王错
到达51级
#+END_EXAMPLE

** 荆青！
- 目睹江洋大盗荆青的死亡！
#+BEGIN_EXAMPLE
荆青
到达51级
#+END_EXAMPLE

** 慕容天！
- 目睹江洋大盗慕容天的死亡！
#+BEGIN_EXAMPLE
慕容天
到达11级
#+END_EXAMPLE

** 洪震！
- 目睹江洋大盗洪震的死亡！
#+BEGIN_EXAMPLE
洪震
到达11级
#+END_EXAMPLE

** 厉若海！
- 目睹江洋大盗厉若海的死亡！
#+BEGIN_EXAMPLE
厉若海
到达11级
#+END_EXAMPLE

** 莫非！
- 目睹江洋大盗莫非的死亡！
#+BEGIN_EXAMPLE
莫非
到达41级
#+END_EXAMPLE

** 莫名！
- 目睹江洋大盗莫名的死亡！
#+BEGIN_EXAMPLE
莫名
到达41级
#+END_EXAMPLE

** 凌雪城！
- 目睹江洋大盗凌雪城的死亡！
#+BEGIN_EXAMPLE
凌雪城
到达41级
#+END_EXAMPLE

** 莫风！
- 目睹江洋大盗莫风的死亡！
#+BEGIN_EXAMPLE
莫风
到达41级
#+END_EXAMPLE

** 南宫午剑！
- 目睹江洋大盗南宫午剑的死亡！
#+BEGIN_EXAMPLE
南宫午剑
到达41级
#+END_EXAMPLE

** 叶牧天！
- 目睹江洋大盗叶牧天的死亡！
#+BEGIN_EXAMPLE
叶牧天
到达21级
#+END_EXAMPLE

** 裴元术！
- 目睹江洋大盗裴元术的死亡！
#+BEGIN_EXAMPLE
裴元术
到达21级
#+END_EXAMPLE

** 林忆南！
- 目睹江洋大盗林忆南的死亡！
#+BEGIN_EXAMPLE
林忆南
到达21级
#+END_EXAMPLE

** 柳兮！
- 目睹江洋大盗柳兮的死亡！
#+BEGIN_EXAMPLE
柳兮
到达21级
#+END_EXAMPLE

** 沈风洋！
- 目睹江洋大盗沈风洋的死亡！
#+BEGIN_EXAMPLE
沈风洋
到达31级
#+END_EXAMPLE

** 公孙朔！
- 目睹江洋大盗公孙朔的死亡！
#+BEGIN_EXAMPLE
公孙朔
到达31级
#+END_EXAMPLE

** 连归七！
- 目睹江洋大盗连归七的死亡！
#+BEGIN_EXAMPLE
连归七
到达31级
#+END_EXAMPLE

** 严倚枫！
- 目睹江洋大盗严倚枫的死亡！
#+BEGIN_EXAMPLE
严倚枫
到达31级
#+END_EXAMPLE

** 林悔！
- 目睹江洋大盗林悔的死亡！
#+BEGIN_EXAMPLE
林悔
到达31级
#+END_EXAMPLE

** 燕留夜！
- 目睹江洋大盗燕留夜的死亡！
#+BEGIN_EXAMPLE
燕留夜
到达61级
#+END_EXAMPLE

** 张决之！
- 目睹江洋大盗张决之的死亡！
#+BEGIN_EXAMPLE
张决之
到达61级
#+END_EXAMPLE

** 盘云鹤！
- 目睹江洋大盗盘云鹤的死亡！
#+BEGIN_EXAMPLE
盘云鹤
到达61级
#+END_EXAMPLE

** 陆典！
- 目睹江洋大盗陆典的死亡！
#+BEGIN_EXAMPLE
陆典
到达61级
#+END_EXAMPLE

** 叶青竹！
- 目睹江洋大盗叶青竹的死亡！
#+BEGIN_EXAMPLE
叶青竹
到达61级
#+END_EXAMPLE

** 范天行！
- 目睹江洋大盗范天行的死亡！
#+BEGIN_EXAMPLE
范天行
到达61级
#+END_EXAMPLE

** 倪龙涛！
- 目睹江洋大盗倪龙涛的死亡！
#+BEGIN_EXAMPLE
倪龙涛
到达71级
#+END_EXAMPLE

** 龚辰峰！
- 目睹江洋大盗龚辰峰的死亡！
#+BEGIN_EXAMPLE
龚辰峰
到达71级
#+END_EXAMPLE

** 叶奇！
- 目睹江洋大盗叶奇的死亡！
#+BEGIN_EXAMPLE
叶奇
到达71级
#+END_EXAMPLE

** 黄风之！
- 目睹江洋大盗黄风之的死亡！
#+BEGIN_EXAMPLE
黄风之
到达71级
#+END_EXAMPLE

** 邓力彪！
- 目睹江洋大盗邓力彪的死亡！
#+BEGIN_EXAMPLE
邓力彪
到达71级
#+END_EXAMPLE

** 张云星！
- 目睹江洋大盗张云星的死亡！
#+BEGIN_EXAMPLE
张云星
到达71级
#+END_EXAMPLE

** 梁广！
- 目睹江洋大盗梁广的死亡！
#+BEGIN_EXAMPLE
梁广
到达80级
#+END_EXAMPLE

** 曹一凡！
- 目睹江洋大盗曹一凡的死亡！
#+BEGIN_EXAMPLE
曹一凡
到达80级
#+END_EXAMPLE

** 孙仁成！
- 目睹江洋大盗孙仁成的死亡！
#+BEGIN_EXAMPLE
孙仁成
到达80级
#+END_EXAMPLE

** 白芝茂！
- 目睹江洋大盗白芝茂的死亡！
#+BEGIN_EXAMPLE
白芝茂
到达80级
#+END_EXAMPLE

** 邹天！
- 目睹江洋大盗邹天的死亡！
#+BEGIN_EXAMPLE
邹天
到达80级
#+END_EXAMPLE

** 涂清振！
- 目睹江洋大盗涂清振的死亡！
#+BEGIN_EXAMPLE
涂清振
到达80级
#+END_EXAMPLE

** 姜伯天！
- 目睹江洋大盗姜伯天的死亡！
#+BEGIN_EXAMPLE
姜伯天
到达81级
#+END_EXAMPLE

** 贺林士！
- 目睹江洋大盗贺林士的死亡！
#+BEGIN_EXAMPLE
贺林士
到达81级
#+END_EXAMPLE

** 简回！
- 目睹江洋大盗简回的死亡！
#+BEGIN_EXAMPLE
简回
到达81级
#+END_EXAMPLE

** 雷钧义！
- 目睹江洋大盗雷钧义的死亡！
#+BEGIN_EXAMPLE
雷钧义
到达81级
#+END_EXAMPLE

** 雷钧忠！
- 目睹江洋大盗雷钧忠的死亡！
#+BEGIN_EXAMPLE
雷钧忠
到达81级
#+END_EXAMPLE

** 危明武！
- 目睹江洋大盗危明武的死亡！
#+BEGIN_EXAMPLE
危明武
到达81级
#+END_EXAMPLE

** 柳生日月！
- 目睹江洋大盗柳生日月的死亡！
#+BEGIN_EXAMPLE
柳生日月
#+END_EXAMPLE

** 藤原秀哉！
- 目睹江洋大盗藤原秀哉的死亡！
#+BEGIN_EXAMPLE
藤原秀哉
#+END_EXAMPLE

** 近卫慎一郎！
- 目睹江洋大盗近卫慎一郎的死亡！
#+BEGIN_EXAMPLE
近卫慎一郎
#+END_EXAMPLE

** 蛟王 江血海！
- 目睹江洋大盗蛟王 江血海的死亡！
#+BEGIN_EXAMPLE
蛟王 江血海
#+END_EXAMPLE

** 章八脚！
- 目睹江洋大盗章八脚的死亡！
#+BEGIN_EXAMPLE
章八脚
#+END_EXAMPLE

** 龙崇孝！
- 目睹江洋大盗龙崇孝的死亡！
#+BEGIN_EXAMPLE
龙崇孝
#+END_EXAMPLE

** 藤原清涟！
- 目睹江洋大盗藤原清涟的死亡！
#+BEGIN_EXAMPLE
藤原清涟
#+END_EXAMPLE

** 柳生一辉！
- 目睹江洋大盗柳生一辉的死亡！
#+BEGIN_EXAMPLE
柳生一辉
#+END_EXAMPLE

** 柳生千黯！
- 目睹江洋大盗柳生千黯的死亡！
#+BEGIN_EXAMPLE
柳生千黯
#+END_EXAMPLE

** 久蚩长老！
- 目睹江洋大盗久蚩长老的死亡！
#+BEGIN_EXAMPLE
久蚩长老
#+END_EXAMPLE

** 花霜衣！
- 目睹江洋大盗花霜衣的死亡！
#+BEGIN_EXAMPLE
花霜衣
#+END_EXAMPLE

** 飞嫣！
- 目睹江洋大盗飞嫣的死亡！
#+BEGIN_EXAMPLE
飞嫣
#+END_EXAMPLE

** 丁觉！
- 目睹江洋大盗丁觉的死亡！
#+BEGIN_EXAMPLE
丁觉
#+END_EXAMPLE

** 方长恨！
- 目睹江洋大盗方长恨的死亡！
#+BEGIN_EXAMPLE
方长恨
#+END_EXAMPLE

** 灵猫儿！
- 目睹江洋大盗灵猫儿的死亡！
#+BEGIN_EXAMPLE
灵猫儿
#+END_EXAMPLE

** 魔神！
- 目睹江洋大盗魔神的死亡！
#+BEGIN_EXAMPLE
魔神
#+END_EXAMPLE

** 荼毗罗法王！
- 目睹江洋大盗荼毗罗法王的死亡！
#+BEGIN_EXAMPLE
荼毗罗法王
#+END_EXAMPLE

** 肖湘北！
- 目睹江洋大盗肖湘北的死亡！
#+BEGIN_EXAMPLE
肖湘北
#+END_EXAMPLE

** 狼王！
- 目睹江洋大盗狼王的死亡！
#+BEGIN_EXAMPLE
狼王
#+END_EXAMPLE

** 耶律观音奴！
- 目睹江洋大盗耶律观音奴的死亡！
#+BEGIN_EXAMPLE
耶律观音奴
#+END_EXAMPLE

** 韩庶成！
- 目睹江洋大盗韩庶成的死亡！
#+BEGIN_EXAMPLE
韩庶成
#+END_EXAMPLE

** 西海侯！
- 目睹江洋大盗西海侯的死亡！
#+BEGIN_EXAMPLE
西海侯
#+END_EXAMPLE

** 金珠！
- 目睹江洋大盗金珠的死亡！
#+BEGIN_EXAMPLE
金珠
#+END_EXAMPLE

** 瞿塘王 孔铁汉！
- 目睹江洋大盗瞿塘王 孔铁汉的死亡！
#+BEGIN_EXAMPLE
瞿塘王 孔铁汉
#+END_EXAMPLE

** 断天下！
- 目睹江洋大盗断天下的死亡！
#+BEGIN_EXAMPLE
断天下
#+END_EXAMPLE

** 折四盟！
- 目睹江洋大盗折四盟的死亡！
#+BEGIN_EXAMPLE
折四盟
#+END_EXAMPLE

** 灭八荒！
- 目睹江洋大盗灭八荒的死亡！
#+BEGIN_EXAMPLE
灭八荒
#+END_EXAMPLE

** 极乐菩萨 萧宁！
- 目睹江洋大盗极乐菩萨 萧宁的死亡！
#+BEGIN_EXAMPLE
极乐菩萨 萧宁
#+END_EXAMPLE

** 红云！
- 目睹江洋大盗红云的死亡！
#+BEGIN_EXAMPLE
红云
#+END_EXAMPLE

** 绿腰！
- 目睹江洋大盗绿腰的死亡！
#+BEGIN_EXAMPLE
绿腰
#+END_EXAMPLE

** 丁情！
- 目睹江洋大盗丁情的死亡！
#+BEGIN_EXAMPLE
丁情
#+END_EXAMPLE

** 方月夜！
- 目睹江洋大盗方月夜的死亡！
#+BEGIN_EXAMPLE
方月夜
#+END_EXAMPLE

** 秦滔滔！
- 目睹江洋大盗秦滔滔的死亡！
#+BEGIN_EXAMPLE
秦滔滔
#+END_EXAMPLE

** 杨恨
- 目睹州府通缉大盗杨恨的死亡
#+BEGIN_EXAMPLE
杨恨
到达31级
#+END_EXAMPLE

** 龙王 
- 目睹州府通缉大盗龙王的死亡
#+BEGIN_EXAMPLE
龙王 
到达31级
#+END_EXAMPLE

** 郭荣
- 目睹州府通缉大盗郭荣的死亡
#+BEGIN_EXAMPLE
郭荣
到达31级
#+END_EXAMPLE

** 唐害
- 目睹州府通缉大盗唐害的死亡
#+BEGIN_EXAMPLE
唐害
到达31级
#+END_EXAMPLE

** 源小五郎
- 目睹州府通缉大盗源小五郎的死亡
#+BEGIN_EXAMPLE
源小五郎
到达31级
#+END_EXAMPLE

** 刀不异
- 目睹州府通缉大盗刀不异的死亡
#+BEGIN_EXAMPLE
刀不异
到达31级
#+END_EXAMPLE

** 魔神
- 目睹州府通缉大盗魔神的死亡
#+BEGIN_EXAMPLE
魔神
到达31级
#+END_EXAMPLE

** 漆雕狐
- 目睹州府通缉大盗漆雕狐的死亡
#+BEGIN_EXAMPLE
漆雕狐
到达31级
#+END_EXAMPLE

** 无名客
- 目睹州府通缉大盗无名客的死亡
#+BEGIN_EXAMPLE
无名客
到达31级
#+END_EXAMPLE

** 荆似雪
- 目睹州府通缉大盗荆似雪的死亡
#+BEGIN_EXAMPLE
荆似雪
到达31级
#+END_EXAMPLE

** 耶律郑哥
- 目睹州府通缉大盗耶律郑哥的死亡
#+BEGIN_EXAMPLE
耶律郑哥
到达31级
#+END_EXAMPLE

** 豺狼道长
- 目睹州府通缉大盗豺狼道长的死亡
#+BEGIN_EXAMPLE
豺狼道长
到达31级
#+END_EXAMPLE

** 胡不春
- 目睹青龙会头目胡不春的死亡
#+BEGIN_EXAMPLE
胡不春
到达31级
#+END_EXAMPLE

** 狄鹰
- 目睹青龙会头目狄鹰的死亡
#+BEGIN_EXAMPLE
狄鹰
到达31级
#+END_EXAMPLE

** 吴大愚
- 目睹青龙会头目吴大愚的死亡
#+BEGIN_EXAMPLE
吴大愚
到达31级
#+END_EXAMPLE

** 柳炎炎
- 目睹青龙会头目柳炎炎的死亡
#+BEGIN_EXAMPLE
柳炎炎
到达31级
#+END_EXAMPLE

** 绝禅
- 目睹青龙会头目绝禅的死亡
#+BEGIN_EXAMPLE
绝禅
到达31级
#+END_EXAMPLE

** 董乱水
- 目睹青龙会头目董乱水的死亡
#+BEGIN_EXAMPLE
董乱水
到达31级
#+END_EXAMPLE

** 韩恨
- 目睹青龙会头目韩恨的死亡
#+BEGIN_EXAMPLE
韩恨
到达31级
#+END_EXAMPLE

** 盛昭秀
- 目睹青龙会头目盛昭秀的死亡
#+BEGIN_EXAMPLE
盛昭秀
到达31级
#+END_EXAMPLE

** 金俊璧
- 目睹青龙会头目金俊璧的死亡
#+BEGIN_EXAMPLE
金俊璧
到达31级
#+END_EXAMPLE

** 苗龙
- 目睹青龙会头目苗龙的死亡
#+BEGIN_EXAMPLE
苗龙
到达31级
#+END_EXAMPLE

** 杨尚智
- 目睹青龙会头目杨尚智的死亡
#+BEGIN_EXAMPLE
杨尚智
到达31级
#+END_EXAMPLE

** 公西明玉
- 目睹青龙会头目公西明玉的死亡
#+BEGIN_EXAMPLE
公西明玉
到达31级
#+END_EXAMPLE

** 白露
- 目睹青龙会头目白露的死亡
#+BEGIN_EXAMPLE
白露
到达31级
#+END_EXAMPLE

** 叶月色
- 目睹青龙会头目叶月色的死亡
#+BEGIN_EXAMPLE
叶月色
到达31级
#+END_EXAMPLE

** 施初有
- 目睹青龙会头目施初有的死亡
#+BEGIN_EXAMPLE
施初有
到达31级
#+END_EXAMPLE

** 戎冰
- 目睹青龙会头目戎冰的死亡
#+BEGIN_EXAMPLE
戎冰
到达31级
#+END_EXAMPLE

** 马端阳
- 目睹青龙会头目马端阳的死亡
#+BEGIN_EXAMPLE
马端阳
到达31级
#+END_EXAMPLE

** 李鱼
- 目睹青龙会头目李鱼的死亡
#+BEGIN_EXAMPLE
李鱼
到达31级
#+END_EXAMPLE

** 铁老七
- 目睹青龙会头目铁老七的死亡
#+BEGIN_EXAMPLE
铁老七
到达31级
#+END_EXAMPLE

** 酒无常
- 目睹青龙会头目酒无常的死亡
#+BEGIN_EXAMPLE
酒无常
到达31级
#+END_EXAMPLE

** 萧熊
- 目睹青龙会头目萧熊的死亡
#+BEGIN_EXAMPLE
萧熊
到达31级
#+END_EXAMPLE

** 血池尊者
- 目睹青龙会头目血池尊者的死亡
#+BEGIN_EXAMPLE
血池尊者
到达31级
#+END_EXAMPLE

** 皇甫离
- 目睹青龙会头目皇甫离的死亡
#+BEGIN_EXAMPLE
皇甫离
到达31级
#+END_EXAMPLE

** 范千文
- 目睹青龙会头目范千文的死亡
#+BEGIN_EXAMPLE
范千文
到达31级
#+END_EXAMPLE

** 莫折梅
- 目睹青龙会头目莫折梅的死亡
#+BEGIN_EXAMPLE
莫折梅
到达31级
#+END_EXAMPLE

** 肖笑生
- 目睹青龙会头目肖笑生的死亡
#+BEGIN_EXAMPLE
肖笑生
到达31级
#+END_EXAMPLE

** 炼努
- 目睹青龙会头目炼努的死亡
#+BEGIN_EXAMPLE
炼努
到达31级
#+END_EXAMPLE

** 尚碧袍
- 目睹青龙会头目尚碧袍的死亡
#+BEGIN_EXAMPLE
尚碧袍
到达31级
#+END_EXAMPLE

** 焚刀客
- 目睹青龙会头目焚刀客的死亡
#+BEGIN_EXAMPLE
焚刀客
到达31级
#+END_EXAMPLE

** 屠天命
- 目睹青龙会头目屠天命的死亡
#+BEGIN_EXAMPLE
屠天命
到达31级
#+END_EXAMPLE

** 狂煞
- 目睹青龙会头目狂煞的死亡
#+BEGIN_EXAMPLE
狂煞
到达31级
#+END_EXAMPLE

** 王大头
- 目睹青龙会头目王大头的死亡
#+BEGIN_EXAMPLE
王大头
到达31级
#+END_EXAMPLE

** 洪鸣
- 目睹青龙会头目洪鸣的死亡
#+BEGIN_EXAMPLE
洪鸣
到达31级
#+END_EXAMPLE

** 方重衣
- 目睹青龙会头目方重衣的死亡
#+BEGIN_EXAMPLE
方重衣
到达31级
#+END_EXAMPLE

** 拓拔连天
- 目睹青龙会头目拓拔连天的死亡
#+BEGIN_EXAMPLE
拓拔连天
到达31级
#+END_EXAMPLE

** 尹竹溪
- 目睹青龙会头目尹竹溪的死亡
#+BEGIN_EXAMPLE
尹竹溪
到达31级
#+END_EXAMPLE

** 八月初八
- 目睹青龙会首领八月初八的死亡
#+BEGIN_EXAMPLE
八月初八
到达31级
#+END_EXAMPLE

** 二月初三
- 目睹青龙会首领二月初三的死亡
#+BEGIN_EXAMPLE
二月初三
到达31级
#+END_EXAMPLE

** 四月十四
- 目睹青龙会首领四月十四的死亡
#+BEGIN_EXAMPLE
四月十四
到达31级
#+END_EXAMPLE

** 九月初一
- 目睹青龙会首领九月初一的死亡
#+BEGIN_EXAMPLE
九月初一
到达31级
#+END_EXAMPLE

** 五月初五
- 目睹青龙会首领五月初五的死亡
#+BEGIN_EXAMPLE
五月初五
到达31级
#+END_EXAMPLE

** 十一月初二
- 目睹青龙会首领十一月初二的死亡
#+BEGIN_EXAMPLE
十一月初二
到达31级
#+END_EXAMPLE

** 七月十九
- 目睹青龙会首领七月十九的死亡
#+BEGIN_EXAMPLE
七月十九
到达31级
#+END_EXAMPLE

** 腊月十八
- 目睹青龙会首领腊月十八的死亡
#+BEGIN_EXAMPLE
腊月十八
到达31级
#+END_EXAMPLE

** 正月三十
- 目睹青龙会首领正月三十的死亡
#+BEGIN_EXAMPLE
正月三十
到达31级
#+END_EXAMPLE

** 三月廿七
- 目睹青龙会首领三月廿七的死亡
#+BEGIN_EXAMPLE
三月廿七
到达31级
#+END_EXAMPLE

** 十月十五
- 目睹青龙会首领十月十五的死亡
#+BEGIN_EXAMPLE
十月十五
到达31级
#+END_EXAMPLE

** 六月十六
- 目睹青龙会首领六月十六的死亡
#+BEGIN_EXAMPLE
六月十六
到达31级
#+END_EXAMPLE

* 等级
** 侠·初入江湖
- 触动初入江湖（30级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 智·江湖百业
- 触动江湖百业（40级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 凛·剑试蔷薇
- 触动剑试蔷薇（50级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 霸·天下盟会
- 触动天下盟会（60级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 策·九华叠翠
- 触动九华叠翠（70级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 舞·天香传世
- 触动天香传世（80级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 暗·东京华梦
- 触动东京华梦（90级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 笑·沧海月明
- 触动沧海月明（100级）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 梦·东海极境
- 触动东海极境（终极封印）的等级封印
#+BEGIN_EXAMPLE
首个激活等级封印
#+END_EXAMPLE

** 陌上花开
- 不删档侠士专享
#+BEGIN_EXAMPLE
不删档侠士专享
#+END_EXAMPLE

** 会饮天下
- 会员礼包尊享
#+BEGIN_EXAMPLE
会员礼包尊享
#+END_EXAMPLE

** 兰陵霸唱
- 豪华蓝钻礼包尊享
#+BEGIN_EXAMPLE
豪华蓝钻礼包尊享
#+END_EXAMPLE

** 心悦君兮
- 心悦会员尊享
#+BEGIN_EXAMPLE
心悦会员尊享
#+END_EXAMPLE

** 盛世君临
- 心悦会员尊享2
#+BEGIN_EXAMPLE
心悦会员尊享2
#+END_EXAMPLE

** 金璧梦回
- 黄钻礼包尊享
#+BEGIN_EXAMPLE
黄钻礼包尊享
#+END_EXAMPLE

** 翠影菁华
- 绿钻礼包尊享
#+BEGIN_EXAMPLE
绿钻礼包尊享
#+END_EXAMPLE

** 极地曙光
- TGP礼包尊享
#+BEGIN_EXAMPLE
TGP礼包尊享
#+END_EXAMPLE

** 初试身手
- 等级达到10级
#+BEGIN_EXAMPLE
达到10级
#+END_EXAMPLE

** 初入江湖
- 等级达到20级
#+BEGIN_EXAMPLE
达到20级
#+END_EXAMPLE

** 小有名气
- 等级达到30级
#+BEGIN_EXAMPLE
达到30级
#+END_EXAMPLE

** 行走江湖
- 等级达到40级
#+BEGIN_EXAMPLE
达到40级
#+END_EXAMPLE

** 堪负重任
- 等级达到50级
#+BEGIN_EXAMPLE
达到50级
#+END_EXAMPLE

** 侠行四方
- 等级达到60级
#+BEGIN_EXAMPLE
达到60级
#+END_EXAMPLE

** 八荒豪杰
- 等级达到70级
#+BEGIN_EXAMPLE
达到70级
#+END_EXAMPLE

** 独步武林
- 等级达到80级
#+BEGIN_EXAMPLE
达到80级
#+END_EXAMPLE

** 名动天下
- 等级达到90级
#+BEGIN_EXAMPLE
达到90级
#+END_EXAMPLE

** 威震江湖
- 等级达到100级
#+BEGIN_EXAMPLE
达到100级
#+END_EXAMPLE

** 融会贯通
- 学习完毕所有的本门派技能
#+BEGIN_EXAMPLE
门派技能
#+END_EXAMPLE

* 金钱
** 初识孔方
- 获取金钱达到100金
#+BEGIN_EXAMPLE
100金
#+END_EXAMPLE

** 积少成多
- 获取金钱达到1000金
#+BEGIN_EXAMPLE
1000金
#+END_EXAMPLE

** 富甲一方
- 获取金钱达到10000金
#+BEGIN_EXAMPLE
10000金
#+END_EXAMPLE

** 堆金积玉
- 获取金钱达到100000金
#+BEGIN_EXAMPLE
100000金
#+END_EXAMPLE

** 腰缠万贯
- 获取金钱达到500000金
#+BEGIN_EXAMPLE
获取金钱达到500000金
#+END_EXAMPLE

** 富可敌国
- 获取金钱达到1500000金
#+BEGIN_EXAMPLE
获取金钱达到1500000金
#+END_EXAMPLE

** 纸醉金迷
- 获取金钱达到5000000金
#+BEGIN_EXAMPLE
获取金钱达到5000000金
#+END_EXAMPLE

** 一掷千金
- 花费超过1000金
#+BEGIN_EXAMPLE
花费1000金
#+END_EXAMPLE

** 散尽复来
- 花费超过10000金
#+BEGIN_EXAMPLE
花费10000金
#+END_EXAMPLE

** 挥金如土
- 花费超过100000金
#+BEGIN_EXAMPLE
花费100000金
#+END_EXAMPLE

** 拨万轮千
- 花费超过500000金
#+BEGIN_EXAMPLE
花费超过500000金
#+END_EXAMPLE

** 钟鸣鼎食
- 花费超过1500000金
#+BEGIN_EXAMPLE
花费超过1500000金
#+END_EXAMPLE

** 身外之物
- 花费超过5000000金
#+BEGIN_EXAMPLE
花费超过5000000金
#+END_EXAMPLE

** 富有四海
- 获取金钱达到10000000金
#+BEGIN_EXAMPLE
获取金钱达到10000000金
#+END_EXAMPLE

** 身外之物·二
- 花费超过8000000金
#+BEGIN_EXAMPLE
花费超过8000000金
#+END_EXAMPLE

** 身外之物·三
- 花费超过10000000金
#+BEGIN_EXAMPLE
花费超过10000000金
#+END_EXAMPLE

* 话本
** 重创神武门
- 神刀堂与神武门的恩怨终需做个了断，经此一战，马芳玲与杜云松虽逃走，但孤魂断常、郝厨子与苗天王伏诛，神武门已元气大伤。\n
#+BEGIN_EXAMPLE
完成话本“普通·强袭神武门”
#+END_EXAMPLE

** 疾速神武门
- 在半小时的时间内完成话本：普通·强袭神武门
#+BEGIN_EXAMPLE
神武门
#+END_EXAMPLE

** 疾速夜探郡王府
- 在一刻钟的时间内完成话本：夜探郡王府
#+BEGIN_EXAMPLE
夜探郡王府
#+END_EXAMPLE

** 强攻郡王府
- 应天波府之邀，强行攻入东平郡王府，击败赵允弼
#+BEGIN_EXAMPLE
完成话本“东平郡王府（白天）”
#+END_EXAMPLE

** 疾速强攻郡王府
- 在半小时的时间内完成话本：鏖战郡王府
#+BEGIN_EXAMPLE
强攻郡王府
#+END_EXAMPLE

** 扬威龙首山
- 盘踞在龙首山天泉山庄的十二连环坞老大“鹰眼老七”盗走孔雀翎，杀上龙首山后虽未能夺回，却也震慑了幕后黑手。
#+BEGIN_EXAMPLE
完成话本“龙首山”
#+END_EXAMPLE

** 疾速龙首山
- 在半小时的时间内完成话本：普通·荡平龙首山
#+BEGIN_EXAMPLE
龙首山
#+END_EXAMPLE

** 突袭血衣楼
- 血衣楼现今防守空虚。离盟主传书，你可先行集结人马，捣毁其留守部队，为来日总攻奠定胜机
#+BEGIN_EXAMPLE
血衣楼
#+END_EXAMPLE

** 浴血龙首山
- 前次龙首山扬威，如今鹰眼老七已重整人马再战，浴血龙首山！
#+BEGIN_EXAMPLE
浴血龙首山
#+END_EXAMPLE

** 雨夜镇天牢
- 蛇王神算子和黑蜈蚣带人趁着雨夜前来劫狱，务必要阻止黑街的这次行动！
#+BEGIN_EXAMPLE
雨夜镇天牢
#+END_EXAMPLE

** 实至名归
- 以超过95分的分数ROLL到物品
#+BEGIN_EXAMPLE
掷出95点
#+END_EXAMPLE

** 命中无时莫强求
- 虽然掷出了超过95分，还是未获得物品
#+BEGIN_EXAMPLE
掷出95点
#+END_EXAMPLE

** 命里有时终须有
- 虽然掷出了不到10分，还是赢得了物品
#+BEGIN_EXAMPLE
掷出10点
#+END_EXAMPLE

** 手慢无
- 虽然掷出了100分，因为时间顺序原因还是未获得物品
#+BEGIN_EXAMPLE
掷出100点
#+END_EXAMPLE

** 手快有
- 虽然掷出了1分，因为时间顺序原因还是获得了物品
#+BEGIN_EXAMPLE
掷出1点
#+END_EXAMPLE

** 血战苍梧城
- 万里杀传出消息，青龙会潜堂所在已经查清，就是位于燕云西南的古城苍梧。萧四无更获得了大悲赋的三式，在其中修炼。苍梧城易守难攻，青龙会卧虎藏龙，此战极其凶险。
#+BEGIN_EXAMPLE
血战苍梧城
#+END_EXAMPLE

** 挑战·血战苍梧城
- 万里杀传出消息，青龙会潜堂所在已经查清，就是位于燕云西南的古城苍梧。萧四无更获得了大悲赋的三式，在其中修炼。苍梧城易守难攻，青龙会卧虎藏龙，此战极其凶险。
#+BEGIN_EXAMPLE
浴血苍梧城
#+END_EXAMPLE

** 普通·天峰会八荒
- 八荒本独立世外，如今决意与四盟携手，正面对抗青龙会。八荒师兄师姐们严阵以待，只有通过了他们考验的精锐之师，才有资格前往万雪窟极凶之地一探。
#+BEGIN_EXAMPLE
普通·天峰会八荒
#+END_EXAMPLE

** 挑战·天峰会八荒
- 八荒本独立世外，如今决意与四盟携手，正面对抗青龙会。八荒师兄师姐们严阵以待，只有通过了他们考验的精锐之师，才有资格前往万雪窟极凶之地一探。
#+BEGIN_EXAMPLE
挑战·天峰会八荒
#+END_EXAMPLE

** 普通·喋血万雪窟
- 八荒查明，百晓生掳掠八荒弟子炼制药人之所在秘密巢穴，正是万雪窟。万雪窟中无数百晓生座下精英，更有诡奇之物，凶险异常。八荒唯选精锐，结队前往刺探征伐。
#+BEGIN_EXAMPLE
普通·喋血万雪窟
#+END_EXAMPLE

** 挑战·喋血万雪窟
- 八荒查明，百晓生掳掠八荒弟子炼制药人之所在秘密巢穴，正是万雪窟。万雪窟中无数百晓生座下精英，更有诡奇之物，凶险异常。八荒唯选精锐，结队前往刺探征伐。
#+BEGIN_EXAMPLE
挑战·喋血万雪窟
#+END_EXAMPLE

** 十二楼五城·修罗
- 十二楼五城是一系列青龙会历经千百年的秘密藏宝之地，只有百晓生知晓其真正秘密。修罗城位于燕云深处，由修罗王镇守炼狱房，极其凶险，其内藏有陨石之焰，可铸神兵。
#+BEGIN_EXAMPLE
十二楼五城·修罗
#+END_EXAMPLE

** 挑战·琴魔
- 百晓生已走，琴音却未绝。随独孤师兄和公孙师兄去会会这个琴魔！
#+BEGIN_EXAMPLE
挑战·琴魔
#+END_EXAMPLE

** 普通·开封会八荒
- 叶开约战开封擂台
#+BEGIN_EXAMPLE
普通·开封会八荒
#+END_EXAMPLE

** 挑战·开封会八荒
- 叶开约战开封擂台
#+BEGIN_EXAMPLE
挑战·开封会八荒
#+END_EXAMPLE

** 普通·决战嘲天宫
- 青龙会密室
#+BEGIN_EXAMPLE
普通·决战嘲天宫
#+END_EXAMPLE

** 挑战·决战嘲天宫
- 青龙会密室
#+BEGIN_EXAMPLE
挑战·决战嘲天宫
#+END_EXAMPLE

** 普通·东海会四盟
- 接受子桑不墨邀请，得四盟主相助，以移花醉心之试的方法，于东海解毒。
#+BEGIN_EXAMPLE
普通·东海会四盟
#+END_EXAMPLE

** 挑战·东海会四盟
- 接受子桑不墨邀请，得四盟主相助，以移花醉心之试的方法，于东海解毒。
#+BEGIN_EXAMPLE
挑战·东海会四盟
#+END_EXAMPLE

** 普通·雨夜破天牢
- 受沈孤鸿所托，前往开封大相国寺底下的皇城天牢，救出一众黑街英雄。
#+BEGIN_EXAMPLE
普通·雨夜破天牢
#+END_EXAMPLE

** 挑战·雨夜破天牢
- 受沈孤鸿所托，前往开封大相国寺底下的皇城天牢，救出一众黑街英雄。
#+BEGIN_EXAMPLE
挑战·雨夜破天牢
#+END_EXAMPLE

* 剧情
** 天涯蔷薇
- 完成九华剧情章节
#+BEGIN_EXAMPLE
完成九华全部任务
#+END_EXAMPLE

** 燕云扬沙
- 完成神威门派剧情章节
#+BEGIN_EXAMPLE
完成全部神威任务
#+END_EXAMPLE

** 秦川逐雪
- 完成太白门派剧情章节
#+BEGIN_EXAMPLE
秦川任务
#+END_EXAMPLE

** 花海浮灯
- 完成天香门派剧情章节
#+BEGIN_EXAMPLE
天香剧情
#+END_EXAMPLE

** 竹海微澜
- 完成唐门门派剧情章节
#+BEGIN_EXAMPLE
唐门剧情
#+END_EXAMPLE

** 荆湖浪迹
- 完成丐帮门派剧情章节
#+BEGIN_EXAMPLE
丐帮剧情
#+END_EXAMPLE

** 沧山观云
- 完成真武门派剧情章节
#+BEGIN_EXAMPLE
真武剧情
#+END_EXAMPLE

** 初识刀意
- 完成杭州剧情章节
#+BEGIN_EXAMPLE
完成全部杭州任务
#+END_EXAMPLE

** 飞燕击水
- 完成江南剧情章节
#+BEGIN_EXAMPLE
完成全部江南任务
#+END_EXAMPLE

** 曾慕多情
- 完成东越剧情章节
#+BEGIN_EXAMPLE
完成全部东越任务
#+END_EXAMPLE

** 再见孔雀
- 完成杭州高等级剧情章节
#+BEGIN_EXAMPLE
杭州高等级
#+END_EXAMPLE

** 剑挑血衣
- 完成九华高等级剧情章节
#+BEGIN_EXAMPLE
九华高等级任务
#+END_EXAMPLE

** 神刀出鞘
- 完成徐海剧情章节
#+BEGIN_EXAMPLE
完成徐海任务章节
#+END_EXAMPLE

** 明月含悲
- 完成开封剧情章节
#+BEGIN_EXAMPLE
开封剧情
#+END_EXAMPLE

** 玉锁冰心
- 完成秦川剧情章节
#+BEGIN_EXAMPLE
秦川剧情
#+END_EXAMPLE

** 计夺连环
- 完成燕云剧情章节
#+BEGIN_EXAMPLE
燕云剧情
#+END_EXAMPLE

** 人在天涯
- 完成以下的剧情章节
#+BEGIN_EXAMPLE
天涯蔷薇
初识刀意
飞燕击水
曾慕多情
再见孔雀
剑挑血衣
神刀出鞘
明月含悲
玉锁冰心
横沙血战
#+END_EXAMPLE

** 日月天华
- 完成五毒门派章节
#+BEGIN_EXAMPLE
五毒门派·日月天华
#+END_EXAMPLE

** 刀锋再临
- 完成神刀门派章节
#+BEGIN_EXAMPLE
神刀门派·神刀再临
#+END_EXAMPLE

** 蜀地风流
- 完成巴蜀剧情章节
#+BEGIN_EXAMPLE
巴蜀剧情·蜀地风流
#+END_EXAMPLE

** 初出茅庐
- 完成九华初出茅庐章节
#+BEGIN_EXAMPLE
神刀门派·神刀再临
#+END_EXAMPLE

** 天命风流·青龙令
- 完成天命风流剧情章节，并选择了潜入卧底的剧情支线。
#+BEGIN_EXAMPLE
潜龙渊·天命风流
#+END_EXAMPLE

** 天命风流·盟主令
- 完成天命风流剧情章节，并选择了接应卧底的剧情支线。
#+BEGIN_EXAMPLE
望龙潭·天命风流
#+END_EXAMPLE

** 归来踏浪
- 完成移花门派章节
#+BEGIN_EXAMPLE
移花门派·归来踏浪
#+END_EXAMPLE

* 经脉
** 经脉筑基
- 经脉贯通达到等级“经脉筑基”
#+BEGIN_EXAMPLE
经脉筑基
#+END_EXAMPLE

** 初窥门径
- 经脉贯通达到等级“初窥门径”
#+BEGIN_EXAMPLE
初窥门径
#+END_EXAMPLE

** 心有所得
- 经脉贯通达到等级“心有所得”
#+BEGIN_EXAMPLE
心有所得
#+END_EXAMPLE

** 渐入佳境
- 经脉贯通达到等级“渐入佳境”
#+BEGIN_EXAMPLE
渐入佳境
#+END_EXAMPLE

** 挥洒自如
- 经脉贯通达到等级“挥洒自如”
#+BEGIN_EXAMPLE
挥洒自如
#+END_EXAMPLE

** 游刃有余
- 经脉贯通达到等级“游刃有余”
#+BEGIN_EXAMPLE
游刃有余
#+END_EXAMPLE

** 行云流水
- 经脉贯通达到等级“行云流水”
#+BEGIN_EXAMPLE
行云流水
#+END_EXAMPLE

** 炉火纯青
- 经脉贯通达到等级“炉火纯青”
#+BEGIN_EXAMPLE
炉火纯青
#+END_EXAMPLE

** 登峰造极
- 经脉贯通达到等级“登峰造极”
#+BEGIN_EXAMPLE
登峰造极
#+END_EXAMPLE

** 出神入化
- 经脉贯通达到等级“出神入化”
#+BEGIN_EXAMPLE
出神入化
#+END_EXAMPLE

* 功力
** 初识武道·壹
- 31级后功力达到2000
#+BEGIN_EXAMPLE
功力达到2000
等级到达31级
#+END_EXAMPLE

** 初识武道·贰
- 31级后功力达到2500
#+BEGIN_EXAMPLE
功力达到2500
等级到达31级
#+END_EXAMPLE

** 潜心修武·壹
- 41级后功力达到3000
#+BEGIN_EXAMPLE
功力达到3000
等级到达41级
#+END_EXAMPLE

** 潜心修武·贰
- 41级后功力达到3500
#+BEGIN_EXAMPLE
功力达到3500
等级到达41级
#+END_EXAMPLE

** 武道初成·壹
- 51级后功力达到4000
#+BEGIN_EXAMPLE
功力达到4000
等级到达51级
#+END_EXAMPLE

** 武道初成·贰
- 51级后功力达到4500
#+BEGIN_EXAMPLE
功力达到4500
等级到达51级
#+END_EXAMPLE

** 武道初成·叁
- 51级后功力达到5000
#+BEGIN_EXAMPLE
功力达到5000
等级到达51级
#+END_EXAMPLE

** 由武窥心·壹
- 61级后功力达到5500
#+BEGIN_EXAMPLE
功力达到5500
等级到达61级
#+END_EXAMPLE

** 由武窥心·贰
- 61级后功力达到6000
#+BEGIN_EXAMPLE
功力达到6000
等级到达61级
#+END_EXAMPLE

** 由武窥心·叁
- 61级后功力达到6500
#+BEGIN_EXAMPLE
功力达到6500
等级到达61级
#+END_EXAMPLE

** 由心窥命·壹
- 71级后功力达到7000
#+BEGIN_EXAMPLE
功力达到7000
等级到达71级
#+END_EXAMPLE

** 由心窥命·贰
- 71级后功力达到7500
#+BEGIN_EXAMPLE
功力达到7500
等级到达71级
#+END_EXAMPLE

** 由心窥命·叁
- 71级后功力达到8000
#+BEGIN_EXAMPLE
功力达到8000
等级到达71级
#+END_EXAMPLE

** 由命窥天·壹
- 81级后功力达到8500
#+BEGIN_EXAMPLE
功力达到8500
等级到达81级
#+END_EXAMPLE

** 由命窥天·贰
- 81级后功力达到9000
#+BEGIN_EXAMPLE
功力达到9000
等级到达81级
#+END_EXAMPLE

** 由命窥天·叁
- 81级后功力达到9500
#+BEGIN_EXAMPLE
功力达到9500
等级到达81级
#+END_EXAMPLE

** 由命窥天·肆
- 81级后功力达到10000
#+BEGIN_EXAMPLE
功力达到10000
等级到达81级
#+END_EXAMPLE

** 武道登峰·壹
- 85级后功力达到11000
#+BEGIN_EXAMPLE
功力达到11000
等级到达85级
#+END_EXAMPLE

** 武道登峰·贰
- 85级后功力达到12000
#+BEGIN_EXAMPLE
功力达到12000
等级到达85级
#+END_EXAMPLE

** 武道登峰·叁
- 90级后功力达到12500
#+BEGIN_EXAMPLE
功力达到12500
等级到达90级
#+END_EXAMPLE

** 武道登峰·肆
- 90级后功力达到13000
#+BEGIN_EXAMPLE
功力达到13000
等级到达90级
#+END_EXAMPLE

** 武道登峰·伍
- 90级后功力达到13500
#+BEGIN_EXAMPLE
功力达到13500
等级到达90级
#+END_EXAMPLE

** 武道登峰·陆
- 90级后功力达到14000
#+BEGIN_EXAMPLE
功力达到14000
等级到达90级
#+END_EXAMPLE

** 武道登峰·柒
- 90级后功力达到14500
#+BEGIN_EXAMPLE
功力达到14500
等级到达90级
#+END_EXAMPLE

** 武道登峰·捌
- 90级后功力达到15000
#+BEGIN_EXAMPLE
功力达到15000
等级到达90级
#+END_EXAMPLE

** 武道登峰·玖
- 90级后功力达到15500
#+BEGIN_EXAMPLE
功力达到15500
等级到达90级
#+END_EXAMPLE

** 武道登峰·拾
- 90级后功力达到16000
#+BEGIN_EXAMPLE
功力达到16000
等级到达90级
#+END_EXAMPLE

** 武心造极·壹
- 90级后功力达到16500
#+BEGIN_EXAMPLE
功力达到16500
等级到达90级
#+END_EXAMPLE

** 武心造极·贰
- 90级后功力达到17000
#+BEGIN_EXAMPLE
功力达到17000
等级到达90级
#+END_EXAMPLE

** 武心造极·叁
- 90级后功力达到17500
#+BEGIN_EXAMPLE
功力达到17500
等级到达90级
#+END_EXAMPLE

** 武心造极·肆
- 90级后功力达到18000
#+BEGIN_EXAMPLE
功力达到18000
等级到达90级
#+END_EXAMPLE

** 武心造极·伍
- 90级后功力达到18250
#+BEGIN_EXAMPLE
功力达到18250
等级到达90级
#+END_EXAMPLE

** 武心造极·陆
- 90级后功力达到18500
#+BEGIN_EXAMPLE
功力达到18500
等级到达90级
#+END_EXAMPLE

** 武心造极·柒
- 90级后功力达到18750
#+BEGIN_EXAMPLE
功力达到18750
等级到达90级
#+END_EXAMPLE

** 武心造极·捌
- 90级后功力达到19000
#+BEGIN_EXAMPLE
功力达到19000
等级到达90级
#+END_EXAMPLE

** 武心造极·玖
- 90级后功力达到19250
#+BEGIN_EXAMPLE
功力达到19250
等级到达90级
#+END_EXAMPLE

** 武心造极·拾
- 90级后功力达到19500
#+BEGIN_EXAMPLE
功力达到19500
等级到达90级
#+END_EXAMPLE

** 武心造极·拾壹
- 90级后功力达到19750
#+BEGIN_EXAMPLE
功力达到19750
等级到达90级
#+END_EXAMPLE

** 盖世武魂·壹
- 90级后功力达到20000
#+BEGIN_EXAMPLE
功力达到20000
等级到达90级
#+END_EXAMPLE

** 盖世武魂·贰
- 90级后功力达到20250
#+BEGIN_EXAMPLE
功力达到20250
等级到达90级
#+END_EXAMPLE

** 盖世武魂·叁
- 90级后功力达到20500
#+BEGIN_EXAMPLE
功力达到20500
等级到达90级
#+END_EXAMPLE

** 盖世武魂·肆
- 90级后功力达到20750
#+BEGIN_EXAMPLE
功力达到20750
等级到达90级
#+END_EXAMPLE

** 盖世武魂·伍
- 90级后功力达到21000
#+BEGIN_EXAMPLE
功力达到21000
等级到达90级
#+END_EXAMPLE

** 盖世武魂·陆
- 90级后功力达到21250
#+BEGIN_EXAMPLE
功力达到21250
等级到达90级
#+END_EXAMPLE

** 盖世武魂·柒
- 90级后功力达到21500
#+BEGIN_EXAMPLE
功力达到21500
等级到达90级
#+END_EXAMPLE

** 盖世武魂·捌
- 90级后功力达到21750
#+BEGIN_EXAMPLE
功力达到21750
等级到达90级
#+END_EXAMPLE

** 盖世武魂·玖
- 90级后功力达到22000
#+BEGIN_EXAMPLE
功力达到22000
等级到达90级
#+END_EXAMPLE

** 盖世武魂·拾
- 90级后功力达到22100
#+BEGIN_EXAMPLE
功力达到22100
等级到达90级
#+END_EXAMPLE

** 盖世武魂·拾壹
- 90级后功力达到22200
#+BEGIN_EXAMPLE
功力达到22200
等级到达90级
#+END_EXAMPLE

** 盖世武魂·拾贰
- 90级后功力达到22300
#+BEGIN_EXAMPLE
功力达到22300
等级到达90级
#+END_EXAMPLE

** 无双武境
- 95级后功力达到22400
#+BEGIN_EXAMPLE
22400
等级到达95级
#+END_EXAMPLE

** 无双武境·贰
- 95级后功力达到22500
#+BEGIN_EXAMPLE
22500
等级到达95级
#+END_EXAMPLE

** 无双武境·叁
- 95级后功力达到22750
#+BEGIN_EXAMPLE
22750
等级到达95级
#+END_EXAMPLE

** 无双武境·肆
- 95级后功力达到23000
#+BEGIN_EXAMPLE
23000
等级到达95级
#+END_EXAMPLE

** 无双武境·伍
- 95级后功力达到23250
#+BEGIN_EXAMPLE
23250
等级到达95级
#+END_EXAMPLE

** 无双武境·陆
- 95级后功力达到23500
#+BEGIN_EXAMPLE
23500
等级到达95级
#+END_EXAMPLE

** 无双武境·柒
- 95级后功力达到23750
#+BEGIN_EXAMPLE
23750
等级到达95级
#+END_EXAMPLE

** 无双武境·捌
- 95级后功力达到24000
#+BEGIN_EXAMPLE
24000
等级到达95级
#+END_EXAMPLE

** 无双武境·玖
- 95级后功力达到24250
#+BEGIN_EXAMPLE
24250
等级到达95级
#+END_EXAMPLE

** 无双武境·拾
- 95级后功力达到24500
#+BEGIN_EXAMPLE
24500
等级到达95级
#+END_EXAMPLE

** 无双武境·拾壹
- 95级后功力达到24750
#+BEGIN_EXAMPLE
24750
等级到达95级
#+END_EXAMPLE

** 无双武境·拾贰
- 95级后功力达到25000
#+BEGIN_EXAMPLE
25000
等级到达95级
#+END_EXAMPLE

** 剑者·逸
- 功力37000获得头顶图案
#+BEGIN_EXAMPLE
37000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇·壹
- 100级后功力达到25200
#+BEGIN_EXAMPLE
25200
等级到达100级
#+END_EXAMPLE

** 武镇寰宇·贰
- 100级后功力达到25400
#+BEGIN_EXAMPLE
25400
等级到达100级
#+END_EXAMPLE

** 武镇寰宇·叁
- 100级后功力达到25600
#+BEGIN_EXAMPLE
25600
等级到达100级
#+END_EXAMPLE

** 武镇寰宇·肆
- 100级后功力达到25800
#+BEGIN_EXAMPLE
25800
等级到达100级
#+END_EXAMPLE

** 武镇寰宇·伍
- 100级后功力达到26000
#+BEGIN_EXAMPLE
26000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇陆
- 100级后功力达到26500
#+BEGIN_EXAMPLE
26500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇柒
- 100级后功力达到27000
#+BEGIN_EXAMPLE
27000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇捌
- 100级后功力达到27500
#+BEGIN_EXAMPLE
27500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇玖
- 100级后功力达到28000
#+BEGIN_EXAMPLE
28000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾
- 100级后功力达到28500
#+BEGIN_EXAMPLE
28500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾壹
- 100级后功力达到29000
#+BEGIN_EXAMPLE
29000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾贰
- 100级后功力达到29500
#+BEGIN_EXAMPLE
29500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾叁
- 100级后功力达到30000
#+BEGIN_EXAMPLE
30000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾肆
- 100级后功力达到30500
#+BEGIN_EXAMPLE
30500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾伍
- 100级后功力达到31000
#+BEGIN_EXAMPLE
31000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾陆
- 100级后功力达到31500
#+BEGIN_EXAMPLE
31500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾柒
- 100级后功力达到32000
#+BEGIN_EXAMPLE
32000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾捌
- 100级后功力达到32500
#+BEGIN_EXAMPLE
32500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇拾玖
- 100级后功力达到33000
#+BEGIN_EXAMPLE
33000
等级到达100级
#+END_EXAMPLE

** 武镇寰宇贰拾
- 100级后功力达到33500
#+BEGIN_EXAMPLE
33500
等级到达100级
#+END_EXAMPLE

** 武镇寰宇贰拾壹
- 100级后功力达到34000
#+BEGIN_EXAMPLE
34000
等级到达100级
#+END_EXAMPLE

* 战力
** 初涉正邪·壹
- 31级后战力达到2000
#+BEGIN_EXAMPLE
战力达到2000
等级到达31级
#+END_EXAMPLE

** 初涉正邪·贰
- 31级后战力达到2500
#+BEGIN_EXAMPLE
战力达到2500
等级到达31级
#+END_EXAMPLE

** 以武正心·壹
- 41级后战力达到3000
#+BEGIN_EXAMPLE
战力达到3000
等级到达41级
#+END_EXAMPLE

** 以武正心·贰
- 41级后战力达到3500
#+BEGIN_EXAMPLE
战力达到3500
等级到达41级
#+END_EXAMPLE

** 侠心初成·壹
- 51级后战力达到4000
#+BEGIN_EXAMPLE
战力达到4000
等级到达51级
#+END_EXAMPLE

** 侠心初成·贰
- 51级后战力达到4500
#+BEGIN_EXAMPLE
战力达到4500
等级到达51级
#+END_EXAMPLE

** 侠心初成·叁
- 51级后战力达到5000
#+BEGIN_EXAMPLE
战力达到5000
等级到达51级
#+END_EXAMPLE

** 侠心炼武·壹
- 61级后战力达到5500
#+BEGIN_EXAMPLE
战力达到5500
等级到达61级
#+END_EXAMPLE

** 侠心炼武·贰
- 61级后战力达到6000
#+BEGIN_EXAMPLE
战力达到6000
等级到达61级
#+END_EXAMPLE

** 侠心炼武·叁
- 61级后战力达到6500
#+BEGIN_EXAMPLE
战力达到6500
等级到达61级
#+END_EXAMPLE

** 侠武破命·壹
- 71级后战力达到7000
#+BEGIN_EXAMPLE
战力达到7000
等级到达71级
#+END_EXAMPLE

** 侠武破命·贰
- 71级后战力达到7500
#+BEGIN_EXAMPLE
战力达到7500
等级到达71级
#+END_EXAMPLE

** 侠武破命·叁
- 71级后战力达到8000
#+BEGIN_EXAMPLE
战力达到8000
等级到达71级
#+END_EXAMPLE

** 侠骨天成·壹
- 81级后战力达到8500
#+BEGIN_EXAMPLE
战力达到8500
等级到达81级
#+END_EXAMPLE

** 侠骨天成·贰
- 81级后战力达到9000
#+BEGIN_EXAMPLE
战力达到9000
等级到达81级
#+END_EXAMPLE

** 侠骨天成·叁
- 81级后战力达到9500
#+BEGIN_EXAMPLE
战力达到9500
等级到达81级
#+END_EXAMPLE

** 侠骨天成·肆
- 81级后战力达到10000
#+BEGIN_EXAMPLE
战力达到10000
等级到达81级
#+END_EXAMPLE

** 侠行天道·壹
- 85级后战力达到11000
#+BEGIN_EXAMPLE
战力达到11000
等级到达85级
#+END_EXAMPLE

** 侠行天道·贰
- 85级后战力达到12000
#+BEGIN_EXAMPLE
战力达到12000
等级到达85级
#+END_EXAMPLE

** 侠行天道·叁
- 90级后战力达到12500
#+BEGIN_EXAMPLE
战力达到12500
等级到达90级
#+END_EXAMPLE

** 侠行天道·肆
- 90级后战力达到13000
#+BEGIN_EXAMPLE
战力达到13000
等级到达90级
#+END_EXAMPLE

** 侠行天道·伍
- 90级后战力达到13500
#+BEGIN_EXAMPLE
战力达到13500
等级到达90级
#+END_EXAMPLE

** 侠行天道·陆
- 90级后战力达到14000
#+BEGIN_EXAMPLE
战力达到14000
等级到达90级
#+END_EXAMPLE

** 侠行天道·柒
- 90级后战力达到14500
#+BEGIN_EXAMPLE
战力达到14500
等级到达90级
#+END_EXAMPLE

** 侠行天道·捌
- 90级后战力达到15000
#+BEGIN_EXAMPLE
战力达到15000
等级到达90级
#+END_EXAMPLE

** 侠行天道·玖
- 90级后战力达到15500
#+BEGIN_EXAMPLE
战力达到15500
等级到达90级
#+END_EXAMPLE

** 侠行天道·拾
- 90级后战力达到16000
#+BEGIN_EXAMPLE
战力达到16000
等级到达90级
#+END_EXAMPLE

** 侠念天心·壹
- 90级后战力达到16500
#+BEGIN_EXAMPLE
战力达到16500
等级到达90级
#+END_EXAMPLE

** 侠念天心·贰
- 90级后战力达到17000
#+BEGIN_EXAMPLE
战力达到17000
等级到达90级
#+END_EXAMPLE

** 侠念天心·叁
- 90级后战力达到17500
#+BEGIN_EXAMPLE
战力达到17500
等级到达90级
#+END_EXAMPLE

** 侠念天心·肆
- 90级后战力达到18000
#+BEGIN_EXAMPLE
战力达到18000
等级到达90级
#+END_EXAMPLE

** 侠念天心·伍
- 90级后战力达到18250
#+BEGIN_EXAMPLE
战力达到18250
等级到达90级
#+END_EXAMPLE

** 侠念天心·陆
- 90级后战力达到18500
#+BEGIN_EXAMPLE
战力达到18500
等级到达90级
#+END_EXAMPLE

** 侠念天心·柒
- 90级后战力达到18750
#+BEGIN_EXAMPLE
战力达到18750
等级到达90级
#+END_EXAMPLE

** 侠念天心·捌
- 90级后战力达到19000
#+BEGIN_EXAMPLE
战力达到19000
等级到达90级
#+END_EXAMPLE

** 侠念天心·玖
- 90级后战力达到19250
#+BEGIN_EXAMPLE
战力达到19250
等级到达90级
#+END_EXAMPLE

** 侠念天心·拾
- 90级后战力达到19500
#+BEGIN_EXAMPLE
战力达到19500
等级到达90级
#+END_EXAMPLE

** 侠念天心·拾壹
- 90级后战力达到19750
#+BEGIN_EXAMPLE
战力达到19750
等级到达90级
#+END_EXAMPLE

** 绝代侠客·壹
- 90级后战力达到20000
#+BEGIN_EXAMPLE
战力达到20000
等级到达90级
#+END_EXAMPLE

** 绝代侠客·贰
- 95级后战力达到22500
#+BEGIN_EXAMPLE
22500
等级到达95级
#+END_EXAMPLE

** 绝代侠客·叁
- 95级后战力达到22750
#+BEGIN_EXAMPLE
22750
等级到达95级
#+END_EXAMPLE

** 绝代侠客·肆
- 95级后战力达到23000
#+BEGIN_EXAMPLE
23000
等级到达95级
#+END_EXAMPLE

** 绝代侠客·伍
- 95级后战力达到23250
#+BEGIN_EXAMPLE
23250
等级到达95级
#+END_EXAMPLE

** 绝代侠客·陆
- 95级后战力达到23500
#+BEGIN_EXAMPLE
23500
等级到达95级
#+END_EXAMPLE

** 绝代侠客·柒
- 95级后战力达到23750
#+BEGIN_EXAMPLE
23750
等级到达95级
#+END_EXAMPLE

** 绝代侠客·捌
- 95级后战力达到24000
#+BEGIN_EXAMPLE
24000
等级到达95级
#+END_EXAMPLE

** 绝代侠客·玖
- 95级后战力达到24250
#+BEGIN_EXAMPLE
24250
等级到达95级
#+END_EXAMPLE

** 绝代侠客·拾
- 95级后战力达到24500
#+BEGIN_EXAMPLE
24500
等级到达95级
#+END_EXAMPLE

** 绝代侠客·拾壹
- 95级后战力达到24750
#+BEGIN_EXAMPLE
24750
等级到达95级
#+END_EXAMPLE

** 绝代侠客·拾贰
- 95级后战力达到25000
#+BEGIN_EXAMPLE
25000
等级到达95级
#+END_EXAMPLE

** 战者·勇
- 战力42000获得头顶图案
#+BEGIN_EXAMPLE
42000
等级到达100级
#+END_EXAMPLE

** 侠者天纵·壹
- 100级后战力达到25200
#+BEGIN_EXAMPLE
25200
等级到达100级
#+END_EXAMPLE

** 侠者天纵·贰
- 100级后战力达到25400
#+BEGIN_EXAMPLE
25400
等级到达100级
#+END_EXAMPLE

** 侠者天纵·叁
- 100级后战力达到25600
#+BEGIN_EXAMPLE
25600
等级到达100级
#+END_EXAMPLE

** 侠者天纵·肆
- 100级后战力达到25800
#+BEGIN_EXAMPLE
25800
等级到达100级
#+END_EXAMPLE

** 侠者天纵·伍
- 100级后战力达到26000
#+BEGIN_EXAMPLE
26000
等级到达100级
#+END_EXAMPLE

** 侠者天纵陆
- 100级后战力达到26500
#+BEGIN_EXAMPLE
26500
等级到达100级
#+END_EXAMPLE

** 侠者天纵柒
- 100级后战力达到27000
#+BEGIN_EXAMPLE
27000
等级到达100级
#+END_EXAMPLE

** 侠者天纵捌
- 100级后战力达到27500
#+BEGIN_EXAMPLE
27500
等级到达100级
#+END_EXAMPLE

** 侠者天纵玖
- 100级后战力达到28000
#+BEGIN_EXAMPLE
28000
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾
- 100级后战力达到28500
#+BEGIN_EXAMPLE
28500
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾壹
- 100级后战力达到29000
#+BEGIN_EXAMPLE
29000
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾贰
- 100级后战力达到29500
#+BEGIN_EXAMPLE
29500
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾叁
- 100级后战力达到30000
#+BEGIN_EXAMPLE
30000
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾肆
- 100级后战力达到30500
#+BEGIN_EXAMPLE
30500
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾伍
- 100级后战力达到31000
#+BEGIN_EXAMPLE
31000
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾陆
- 100级后战力达到31500
#+BEGIN_EXAMPLE
31500
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾柒
- 100级后战力达到32000
#+BEGIN_EXAMPLE
32000
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾捌
- 100级后战力达到32500
#+BEGIN_EXAMPLE
32500
等级到达100级
#+END_EXAMPLE

** 侠者天纵拾玖
- 100级后战力达到33000
#+BEGIN_EXAMPLE
33000
等级到达100级
#+END_EXAMPLE

** 侠者天纵贰拾
- 100级后战力达到33500
#+BEGIN_EXAMPLE
33500
等级到达100级
#+END_EXAMPLE

** 侠者天纵贰拾壹
- 100级后战力达到34000
#+BEGIN_EXAMPLE
34000
等级到达100级
#+END_EXAMPLE

** 绝代侠客·贰1
- 战力21000追级成就
#+BEGIN_EXAMPLE
21000
等级到达100级
#+END_EXAMPLE

** 绝代侠客·贰2
- 战力22000追级成就
#+BEGIN_EXAMPLE
22000
等级到达100级
#+END_EXAMPLE

* 投资
** 点滴进步
- 海岛投资给予属性点奖励
#+BEGIN_EXAMPLE
东海玉涡
#+END_EXAMPLE

